server:
  port: 8085

spring:
  application:
    name: doctor-service
  datasource:
    url: jdbc:postgresql://localhost:5432/clinic_db?currentSchema=doctor
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: doctor
  flyway:
    enabled: true
    schemas: doctor
    locations: classpath:db/migration

app:
  security:
    jwt:
      secret: 0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF
      access-token-expiration-minutes: 60
      refresh-token-expiration-days: 7

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

services:
  identity-url: ${SERVICES_IDENTITY_URL:http://localhost:8083}
