server:
  port: 8086

spring:
  application:
    name: appointment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/clinic_db?currentSchema=appointment
    username: postgres
    password: ${SPRING_DATASOURCE_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: appointment

  flyway:
    enabled: true
    schemas: appointment
    locations: classpath:db/migration

services:
  patient:
    url: http://localhost:8084
  doctor:
    url: http://localhost:8085

management:
  endpoints:
    web:
      exposure:
        include: health,info