package com.clinic.v2.encounter.api;
import com.clinic.v2.encounter.api.EncounterDto.*;
import com.clinic.v2.encounter.security.Actor;
import com.clinic.v2.encounter.service.EncounterService;
import jakarta.validation.Valid;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;
import java.util.*;
import java.time.LocalDate;
@RestController
@RequestMapping("/api/v2/clinics/{clinicId}/branches/{branchId}")
public class EncounterController {
 private final EncounterService service;public EncounterController(EncounterService service){this.service=service;}
 @PostMapping("/service-points") public PointView point(@AuthenticationPrincipal Actor actor,@PathVariable UUID clinicId,@PathVariable UUID branchId,@Valid @RequestBody PointInput in){return service.point(actor,clinicId,branchId,in);}
 @GetMapping("/service-points") public List<PointView> points(@AuthenticationPrincipal Actor actor,@PathVariable UUID clinicId,@PathVariable UUID branchId){return service.points(actor,clinicId,branchId);}
 @GetMapping("/reception/appointments") public List<com.clinic.v2.encounter.service.EncounterSources.ArrivalItem> appointments(@AuthenticationPrincipal Actor actor,@PathVariable UUID clinicId,@PathVariable UUID branchId,@RequestParam LocalDate date){return service.appointments(actor,clinicId,branchId,date);}
 @PostMapping("/doctor-absences/{id}/apply") public EncounterService.AbsenceBatch applyAbsence(@AuthenticationPrincipal Actor actor,@PathVariable UUID clinicId,@PathVariable UUID branchId,@PathVariable UUID id){return service.applyAbsence(actor,clinicId,branchId,id);}
 @GetMapping("/reception/arrivals") public List<EncounterService.ArrivalRecovery> arrivals(@AuthenticationPrincipal Actor actor,@PathVariable UUID clinicId,@PathVariable UUID branchId,@RequestParam LocalDate date){return service.arrivals(actor,clinicId,branchId,date);}
 @PostMapping("/reception/arrivals/{id}/recover") public VisitView recover(@AuthenticationPrincipal Actor actor,@PathVariable UUID clinicId,@PathVariable UUID branchId,@PathVariable UUID id,@Valid @RequestBody QueueInput input){return service.recoverArrival(actor,clinicId,branchId,id,input);}
 @GetMapping("/reception/pending-arrivals") public EncounterService.PendingPage pending(@AuthenticationPrincipal Actor actor,@PathVariable UUID clinicId,@PathVariable UUID branchId,@RequestParam(required=false) UUID after,@RequestParam(defaultValue="25") int limit){return service.pending(actor,clinicId,branchId,after,limit);}
 @PostMapping("/reception/pending-arrivals/{id}/recover") public VisitView supervise(@AuthenticationPrincipal Actor actor,@PathVariable UUID clinicId,@PathVariable UUID branchId,@PathVariable UUID id,@RequestHeader("Idempotency-Key") String key,@Valid @RequestBody QueueInput input){return service.superviseArrival(actor,clinicId,branchId,id,key,input);}
 @GetMapping("/appointments/{appointmentId}/exceptions") public List<com.clinic.v2.encounter.service.EncounterSources.ExceptionView> exceptions(@AuthenticationPrincipal Actor actor,@PathVariable UUID clinicId,@PathVariable UUID branchId,@PathVariable UUID appointmentId){return service.exceptions(actor,clinicId,branchId,appointmentId);}
 @PostMapping("/appointments/{appointmentId}/exceptions") public com.clinic.v2.encounter.service.EncounterSources.ExceptionView exception(@AuthenticationPrincipal Actor actor,@PathVariable UUID clinicId,@PathVariable UUID branchId,@PathVariable UUID appointmentId,@RequestHeader("Idempotency-Key") String key,@Valid @RequestBody EncounterService.ExceptionInput in){return service.exception(actor,clinicId,branchId,appointmentId,key,in);}
 @PostMapping("/appointments/{appointmentId}/exceptions/{exceptionId}/resolve") public com.clinic.v2.encounter.service.EncounterSources.ExceptionView resolve(@AuthenticationPrincipal Actor actor,@PathVariable UUID clinicId,@PathVariable UUID branchId,@PathVariable UUID appointmentId,@PathVariable UUID exceptionId,@RequestHeader("Idempotency-Key") String key,@Valid @RequestBody EncounterService.ResolutionInput in){return service.resolve(actor,clinicId,branchId,appointmentId,exceptionId,key,in);}
 @PostMapping("/visits/walk-in") public VisitView walkIn(@AuthenticationPrincipal Actor actor,@PathVariable UUID clinicId,@PathVariable UUID branchId,@RequestHeader("Idempotency-Key") String key,@Valid @RequestBody WalkInInput in){return service.walkIn(actor,clinicId,branchId,key,in);}
 @PostMapping("/appointments/{appointmentId}/check-in") public VisitView checkIn(@AuthenticationPrincipal Actor actor,@PathVariable UUID clinicId,@PathVariable UUID branchId,@PathVariable UUID appointmentId,@RequestHeader("Idempotency-Key") String key,@Valid @RequestBody CheckInInput in){return service.checkIn(actor,clinicId,branchId,appointmentId,key,in);}
 @GetMapping("/visits/{id}") public VisitView read(@AuthenticationPrincipal Actor actor,@PathVariable UUID clinicId,@PathVariable UUID branchId,@PathVariable UUID id){return service.read(actor,clinicId,branchId,id);}
 @GetMapping("/queue") public List<TicketView> queue(@AuthenticationPrincipal Actor actor,@PathVariable UUID clinicId,@PathVariable UUID branchId,@RequestParam UUID servicePointId,@RequestParam LocalDate date){return service.queue(actor,clinicId,branchId,servicePointId,date);}
 @GetMapping("/queue/page") public EncounterService.QueuePage queuePage(@AuthenticationPrincipal Actor actor,@PathVariable UUID clinicId,@PathVariable UUID branchId,@RequestParam UUID servicePointId,@RequestParam LocalDate date,@RequestParam(defaultValue="0") int afterNumber,@RequestParam(defaultValue="50") int limit){return service.queuePage(actor,clinicId,branchId,servicePointId,date,afterNumber,limit);}
 @PostMapping("/queue/{id}/roll-forward") public TicketView rollForward(@AuthenticationPrincipal Actor actor,@PathVariable UUID clinicId,@PathVariable UUID branchId,@PathVariable UUID id,@RequestHeader("Idempotency-Key") String key,@Valid @RequestBody QueueInput input){return service.rollForward(actor,clinicId,branchId,id,key,input);}
 @PostMapping("/queue/{id}/{action:call|skip|transfer}") public TicketView move(@AuthenticationPrincipal Actor actor,@PathVariable UUID clinicId,@PathVariable UUID branchId,@PathVariable UUID id,@PathVariable String action,@Valid @RequestBody QueueInput in){return service.move(actor,clinicId,branchId,id,action,in);}
 @GetMapping("/doctor/worklist") public List<VisitView> worklist(@AuthenticationPrincipal Actor actor,@PathVariable UUID clinicId,@PathVariable UUID branchId){return service.worklist(actor,clinicId,branchId);}
 @GetMapping("/doctor/worklist/page") public EncounterService.WorklistPage worklistPage(@AuthenticationPrincipal Actor actor,@PathVariable UUID clinicId,@PathVariable UUID branchId,@RequestParam(required=false) UUID after,@RequestParam(defaultValue="200") int limit){return service.worklistPage(actor,clinicId,branchId,after,limit);}
 @GetMapping("/doctor/visits/{id}") public VisitView doctorRead(@AuthenticationPrincipal Actor actor,@PathVariable UUID clinicId,@PathVariable UUID branchId,@PathVariable UUID id){return service.doctorRead(actor,clinicId,branchId,id);}
 @GetMapping("/doctor/service-points") public List<PointView> carePoints(@AuthenticationPrincipal Actor actor,@PathVariable UUID clinicId,@PathVariable UUID branchId){return service.carePoints(actor,clinicId,branchId);}
 @PostMapping("/doctor/visits/{id}/{action:start|await-results|resume-queue}") public VisitView care(@AuthenticationPrincipal Actor actor,@PathVariable UUID clinicId,@PathVariable UUID branchId,@PathVariable UUID id,@PathVariable String action,@RequestHeader("Idempotency-Key") String key,@Valid @RequestBody CareInput in){return service.care(actor,clinicId,branchId,id,action,key,in);}
 @PostMapping("/doctor/visits/{id}/complete") public VisitView complete(@AuthenticationPrincipal Actor actor,@PathVariable UUID clinicId,@PathVariable UUID branchId,@PathVariable UUID id,@RequestHeader("Idempotency-Key") String key,@Valid @RequestBody CompletionInput in){return service.complete(actor,clinicId,branchId,id,key,in);}
 @PostMapping("/doctor/visits/{id}/close") public VisitView close(@AuthenticationPrincipal Actor actor,@PathVariable UUID clinicId,@PathVariable UUID branchId,@PathVariable UUID id,@RequestHeader("Idempotency-Key") String key,@Valid @RequestBody ClosureInput in){return service.close(actor,clinicId,branchId,id,key,in);}
 @PostMapping("/visits/{id}/start") public VisitView start(@AuthenticationPrincipal Actor actor,@PathVariable UUID clinicId,@PathVariable UUID branchId,@PathVariable UUID id,@Valid @RequestBody QueueInput in){return service.start(actor,clinicId,branchId,id,in);}
}
