import {useDraftGuard} from './DraftBoundary';
import { useState } from 'react';
import {Pencil,Tags} from 'lucide-react';
import {ManagementTable,ManagementToolbar,ManagementDetail,matchesQuery} from './ManagementTable';
import {parseVnd} from '../utils/vnd';
import * as api from '../api/configuration';
import { ConfigurationForm,type Field } from './ConfigurationForm';
import { useConfigurationSource,type ConfigurationProps } from './ConfigurationPanel';
const fields:Field[]=[{key:'name',label:'Tên dịch vụ',required:true,maxLength:220},{key:'description',label:'Mô tả dịch vụ',type:'textarea',maxLength:1000},{key:'specialtyCode',label:'Chuyên khoa của dịch vụ',maxLength:60},{key:'active',label:'Dịch vụ đang hoạt động',type:'checkbox'}];
const assignmentFields:Field[]=[{key:'durationMinutes',label:'Thời lượng (phút)',type:'number',min:5,max:720,required:true},{key:'active',label:'Cung cấp tại địa điểm này',type:'checkbox'},{key:'publicVisible',label:'Hiển thị dịch vụ công khai',type:'checkbox'}];
const money=(amount:number)=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND'}).format(amount);
const currentPrice=(prices:api.Price[])=>[...prices].filter(p=>new Date(p.effectiveFrom).getTime()<=Date.now()).sort((a,b)=>new Date(b.effectiveFrom).getTime()-new Date(a.effectiveFrom).getTime())[0];
export function CatalogConfiguration(props:ConfigurationProps){
 const drafts=useDraftGuard();const {session,disabled,revision,act}=props;
 const [selected,setSelected]=useState(''),[query,setQuery]=useState(''),[statusFilter,setStatusFilter]=useState('active'),[creating,setCreating]=useState(false),[tab,setTab]=useState<'profile'|'price'>('profile');
 const {data,error}=useConfigurationSource(async()=>{const [offerings,assignments]=await Promise.all([api.offerings(session),api.assignments(session)]);const entries=await Promise.all(assignments.map(async a=>[a.offering.id,await api.prices(session,a.offering.id)] as const));return {offerings,assignments,prices:Object.fromEntries(entries)};},[session.token,session.clinic,session.branch,revision]);
 if(error)return <p role="alert">{error}</p>;if(!data)return <p role="status">Đang tải danh mục và bảng giá…</p>;
 const locked=disabled||!!drafts?.active,current=data.offerings.find(o=>o.id===selected),assigned=data.assignments.find(a=>a.offering.id===selected),rows=data.offerings.filter(o=>(statusFilter==='all'||o.active===(statusFilter==='active'))&&matchesQuery(query,o.code,o.name,o.specialtyCode));
 if(creating)return <ManagementDetail title="Thêm dịch vụ" onBack={()=>setCreating(false)} disabled={locked}><ConfigurationForm fields={[{key:'code',label:'Mã dịch vụ',required:true,pattern:'[A-Z0-9._-]{1,60}'},...fields]} initial={{code:'',name:'',description:'',specialtyCode:'',active:true}} disabled={disabled} label="Thêm dịch vụ" onCancel={()=>setCreating(false)} submit={v=>act(async()=>{const added=await api.saveOffering(session,{code:v.code,name:v.name,description:v.description,specialtyCode:String(v.specialtyCode??'')||null,active:v.active===true});setCreating(false);setSelected(added.id);setTab('profile');})}/></ManagementDetail>;
 if(current)return <ManagementDetail title={current.name} onBack={()=>setSelected('')} disabled={locked}><p className="muted-copy">{current.code} · {current.active?'Đang hoạt động':'Ngừng hoạt động'}</p><div className="management-tabs" role="group" aria-label="Quản lý dịch vụ"><button type="button" aria-pressed={tab==='profile'} disabled={locked} onClick={()=>setTab('profile')}>Thông tin dịch vụ</button><button type="button" aria-pressed={tab==='price'} disabled={locked} onClick={()=>setTab('price')}>Bảng giá</button></div>{tab==='profile'?<><ConfigurationForm key={`offering-${current.id}-${current.version}`} fields={fields} initial={{name:current.name,description:current.description??'',specialtyCode:current.specialtyCode??'',active:current.active}} disabled={disabled} label="Lưu dịch vụ" submit={v=>act(()=>api.saveOffering(session,{expectedVersion:current.version,name:v.name,description:v.description,specialtyCode:String(v.specialtyCode??'')||null,active:v.active===true},current.id))}/><h3>Thời lượng và hiển thị</h3><ConfigurationForm key={`assignment-${assigned?.id??current.id}-${assigned?.version??revision}`} fields={assignmentFields} initial={{durationMinutes:String(assigned?.durationMinutes??30),active:assigned?.active??true,publicVisible:assigned?.publicVisible??false}} disabled={disabled} label={assigned?'Lưu thời lượng và hiển thị':'Thiết lập cung cấp dịch vụ'} submit={v=>act(()=>api.saveAssignment(session,{...(assigned?{expectedVersion:assigned.version}:{offeringId:current.id}),durationMinutes:Number(v.durationMinutes),active:v.active===true,publicVisible:v.publicVisible===true},assigned?.id))}/></>:assigned?<PriceConfiguration key={current.id} offering={current} {...props}/>:<div className="task-empty"><p>Thiết lập thời lượng và cung cấp dịch vụ trong Thông tin dịch vụ trước khi thêm giá.</p><button type="button" onClick={()=>setTab('profile')}>Thiết lập dịch vụ</button></div>}</ManagementDetail>;
 return <section className="management-section"><p className="management-intro">Tra cứu dịch vụ, thời lượng và giá đang áp dụng. Chọn Bảng giá để xem lịch sử hoặc đặt giá mới.</p><ManagementToolbar label="Tìm mã hoặc tên dịch vụ" query={query} onQuery={setQuery} count={rows.length} onAdd={()=>setCreating(true)} addLabel="Thêm dịch vụ" disabled={locked}><select className="management-filter" aria-label="Trạng thái dịch vụ" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="active">Đang hoạt động</option><option value="inactive">Ngừng hoạt động</option><option value="all">Tất cả trạng thái</option></select></ManagementToolbar><ManagementTable caption="Danh mục và bảng giá" headers={['Dịch vụ','Thời lượng','Giá hiện tại','Trạng thái','Thao tác']} empty={!rows.length}>{rows.map(o=>{const a=data.assignments.find(a=>a.offering.id===o.id),price=currentPrice(data.prices[o.id]??[]);return <tr key={o.id}><td><strong>{o.name}</strong><small>{o.code}{o.specialtyCode?' · '+o.specialtyCode:''}</small></td><td>{a?a.durationMinutes+' phút':'Chưa thiết lập'}</td><td className="management-money">{price?money(price.amountVnd):'Chưa có giá'}</td><td><span className="task-status" data-state={o.active&&a?.active?'ACTIVE':'INACTIVE'}>{!o.active?'Ngừng hoạt động':a?.active?'Đang cung cấp':'Chưa cung cấp'}</span></td><td><div className="management-actions"><button type="button" aria-label={'Bảng giá '+o.name} disabled={locked} onClick={()=>{setSelected(o.id);setTab('price');}}><Tags size={15} aria-hidden="true"/>Bảng giá</button><button type="button" aria-label={'Sửa dịch vụ '+o.name} disabled={locked} onClick={()=>{setSelected(o.id);setTab('profile');}}><Pencil size={15} aria-hidden="true"/>Sửa</button></div></td></tr>;})}</ManagementTable></section>;
}
function PriceConfiguration({offering,session,disabled,revision,act}:ConfigurationProps&{offering:api.Offering}){
 const drafts=useDraftGuard(),[creating,setCreating]=useState(false);
 const {data,error}=useConfigurationSource(()=>api.prices(session,offering.id),[session.token,session.clinic,session.branch,offering.id,revision]);
 if(error)return <p role="alert">{error}</p>;if(!data)return <p role="status">Đang tải bảng giá…</p>;
 const current=currentPrice(data);
 return <section><div className="management-subheading"><div><h3>Giá và lịch sử áp dụng</h3><p className="muted-copy">Giá đã chốt của lịch khám và dịch vụ đã thực hiện được giữ nguyên.</p></div><button type="button" className="booking-primary" disabled={disabled||!!drafts?.active} onClick={()=>setCreating(true)}>Thêm giá mới</button></div>{creating&&<section className="management-editor"><h3>Thêm giá mới</h3><ConfigurationForm key={`price-create-${revision}`} fields={[{key:'amountVnd',label:'Giá mới (VND)',type:'vnd',min:0,max:9000000000000,required:true},{key:'effectiveFrom',label:'Áp dụng từ (giờ Việt Nam)',type:'datetime-local',required:true}]} initial={{amountVnd:'',effectiveFrom:''}} disabled={disabled} label="Lưu giá mới" onCancel={()=>setCreating(false)} submit={v=>act(async()=>{await api.addPrice(session,{offeringId:offering.id,amountVnd:parseVnd(String(v.amountVnd),true),effectiveFrom:new Date(String(v.effectiveFrom)+'+07:00').toISOString()});setCreating(false);})}/></section>}<ManagementTable caption={'Bảng giá '+offering.name} headers={['Mức giá','Áp dụng từ (giờ Việt Nam)','Trạng thái']} empty={!data.length}>{[...data].sort((a,b)=>new Date(b.effectiveFrom).getTime()-new Date(a.effectiveFrom).getTime()).map(p=><tr key={p.id}><td className="management-money"><strong>{money(p.amountVnd)}</strong></td><td>{new Date(p.effectiveFrom).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'})}</td><td><span className="task-status" data-state={current?.id===p.id?'ACTIVE':undefined}>{current?.id===p.id?'Đang áp dụng':new Date(p.effectiveFrom).getTime()>Date.now()?'Sắp áp dụng':'Giá trước đây'}</span></td></tr>)}</ManagementTable></section>;
}
