import {useDraftGuard} from './DraftBoundary';
import { useState } from 'react';
import {CalendarDays,Pencil} from 'lucide-react';
import {ManagementTable,ManagementToolbar,ManagementDetail,matchesQuery} from './ManagementTable';
import * as api from '../api/configuration';
import { ConfigurationForm,type Field,type FormValues } from './ConfigurationForm';
import { useConfigurationSource,type ConfigurationProps } from './ConfigurationPanel';
const date=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Ho_Chi_Minh'});
const affiliationFields:Field[]=[{key:'specialtyCode',label:'Mã chuyên khoa',required:true,pattern:'[A-Za-z0-9._-]{1,60}'},{key:'specialtyName',label:'Tên chuyên khoa',required:true,maxLength:160},{key:'professionalTitle',label:'Chức danh chuyên môn',maxLength:120},{key:'effectiveFrom',label:'Liên kết có hiệu lực từ',type:'date',required:true},{key:'effectiveUntil',label:'Liên kết có hiệu lực đến (không gồm ngày này)',type:'date'},{key:'publicVisible',label:'Hiển thị bác sĩ trên hồ sơ công khai',type:'checkbox'}];
const scheduleFields:Field[]=[{key:'dayOfWeek',label:'Ngày trong tuần',options:['Thứ hai','Thứ ba','Thứ tư','Thứ năm','Thứ sáu','Thứ bảy','Chủ nhật'].map((label,i)=>({value:String(i+1),label})),required:true},{key:'startTime',label:'Giờ bắt đầu',type:'time',required:true},{key:'endTime',label:'Giờ kết thúc',type:'time',required:true},{key:'effectiveFrom',label:'Lịch có hiệu lực từ',type:'date',required:true},{key:'effectiveUntil',label:'Lịch có hiệu lực đến (không gồm ngày này)',type:'date'},{key:'active',label:'Lịch đang hoạt động',type:'checkbox'}];
const affiliationBody=(v:FormValues)=>({specialtyCode:String(v.specialtyCode),specialtyName:String(v.specialtyName),professionalTitle:String(v.professionalTitle??'')||null,effectiveFrom:String(v.effectiveFrom),effectiveUntil:String(v.effectiveUntil??'')||null,publicVisible:v.publicVisible===true});
const scheduleBody=(v:FormValues)=>({dayOfWeek:Number(v.dayOfWeek),startTime:String(v.startTime),endTime:String(v.endTime),effectiveFrom:String(v.effectiveFrom),effectiveUntil:String(v.effectiveUntil??'')||null,timezone:'Asia/Ho_Chi_Minh',active:v.active===true});
const days=['','Thứ hai','Thứ ba','Thứ tư','Thứ năm','Thứ sáu','Thứ bảy','Chủ nhật'];
const validateDates=(v:FormValues)=>v.effectiveUntil&&String(v.effectiveUntil)<=String(v.effectiveFrom)?'Ngày kết thúc hiệu lực phải sau ngày bắt đầu.':null;
export function DoctorConfiguration(props:ConfigurationProps){
 const drafts=useDraftGuard();const {session,disabled,revision,act}=props;
 const [selected,setSelected]=useState(''),[tab,setTab]=useState<'schedule'|'profile'>('schedule'),[query,setQuery]=useState(''),[statusFilter,setStatusFilter]=useState('active'),[creating,setCreating]=useState(false),[userId,setUserId]=useState('');
 const {data,error}=useConfigurationSource(async()=>{const [list,members]=await Promise.all([api.affiliations(session),api.staff(session)]);return {list,members};},[session.token,session.clinic,session.branch,revision]);
 if(error)return <p role="alert">{error}</p>;if(!data)return <p role="status">Đang tải bác sĩ…</p>;
 const navigationDisabled=disabled||!!drafts?.active;
 const doctors=data.members.filter(r=>r.account&&r.membership.status==='ACTIVE'&&r.membership.role==='DOCTOR'&&(r.membership.allBranches||r.membership.branchIds.includes(session.branch))&&!data.list.some(a=>a.userId===r.membership.userId));
 const chosen=doctors.find(r=>r.membership.userId===userId)??doctors[0];
 const current=data.list.find(a=>a.id===selected),rows=data.list.filter(a=>(statusFilter==='all'||a.active===(statusFilter==='active'))&&matchesQuery(query,a.displayName,a.specialtyName,a.professionalTitle));
 if(creating)return <ManagementDetail title="Thêm bác sĩ" disabled={navigationDisabled} onBack={()=>setCreating(false)}>{chosen?<><label>Nhân sự bác sĩ<select aria-label="Nhân sự bác sĩ" disabled={navigationDisabled} value={chosen.membership.userId} onChange={e=>setUserId(e.target.value)}>{doctors.map(r=><option key={r.membership.id} value={r.membership.userId}>{r.account!.fullName} · {r.account!.email}</option>)}</select></label><ConfigurationForm key={chosen.membership.userId} fields={[{key:'registrationCode',label:'Mã đăng ký hành nghề',maxLength:100},...affiliationFields]} initial={{registrationCode:'',specialtyCode:'',specialtyName:'',professionalTitle:'Bác sĩ',effectiveFrom:date(),publicVisible:false}} disabled={disabled} label="Thêm bác sĩ" onCancel={()=>setCreating(false)} validate={validateDates} submit={v=>act(async()=>{const added=await api.saveAffiliation(session,{...affiliationBody(v),userId:chosen.membership.userId,displayName:chosen.account!.fullName,registrationCode:String(v.registrationCode??'')||null});setCreating(false);setSelected(added.id);setTab('schedule');})}/></>:<div className="task-empty"><p>Chưa có nhân sự bác sĩ mới để thêm. Vào Nhân sự, thêm tài khoản với vai trò Bác sĩ rồi quay lại đây.</p></div>}</ManagementDetail>;
 if(current)return <ManagementDetail title={current.displayName} disabled={navigationDisabled} onBack={()=>setSelected('')}><p className="muted-copy">{current.professionalTitle||'Bác sĩ'} · {current.specialtyName}</p><div className="management-tabs" role="group" aria-label="Quản lý bác sĩ"><button type="button" aria-pressed={tab==='schedule'} disabled={navigationDisabled} onClick={()=>setTab('schedule')}>Lịch làm việc</button><button type="button" aria-pressed={tab==='profile'} disabled={navigationDisabled} onClick={()=>setTab('profile')}>Thông tin bác sĩ</button></div>{tab==='profile'?<ConfigurationForm key={`affiliation-${current.id}-${current.version}`} fields={[...affiliationFields,{key:'active',label:'Bác sĩ đang hoạt động',type:'checkbox'}]} initial={{specialtyCode:current.specialtyCode,specialtyName:current.specialtyName,professionalTitle:current.professionalTitle??'',effectiveFrom:current.effectiveFrom,effectiveUntil:current.effectiveUntil??'',publicVisible:current.publicVisible,active:current.active}} disabled={disabled} label="Lưu thông tin bác sĩ" validate={validateDates} submit={v=>act(()=>api.saveAffiliation(session,{...affiliationBody(v),active:v.active===true,expectedVersion:current.version},current.id))}/>:<ScheduleConfiguration key={current.id} affiliation={current} {...props}/>}</ManagementDetail>;
 return <section className="management-section"><p className="management-intro">Chọn bác sĩ để quản lý thông tin chuyên môn và lịch làm việc.</p><ManagementToolbar label="Tìm bác sĩ hoặc chuyên khoa" query={query} onQuery={setQuery} count={rows.length} onAdd={()=>setCreating(true)} addLabel="Thêm bác sĩ" disabled={navigationDisabled}><select className="management-filter" aria-label="Trạng thái bác sĩ" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="active">Đang hoạt động</option><option value="inactive">Ngừng hoạt động</option><option value="all">Tất cả trạng thái</option></select></ManagementToolbar><ManagementTable caption="Danh sách bác sĩ" headers={['Bác sĩ','Chuyên khoa','Hiển thị công khai','Trạng thái','Thao tác']} empty={!rows.length}>{rows.map(a=><tr key={a.id}><td><strong>{a.displayName}</strong><small>{a.professionalTitle||'Bác sĩ'}</small></td><td>{a.specialtyName}</td><td>{a.publicVisible?'Có':'Chưa hiển thị'}</td><td><span className="task-status" data-state={a.active?'ACTIVE':'INACTIVE'}>{a.active?'Đang hoạt động':'Ngừng hoạt động'}</span></td><td><div className="management-actions"><button type="button" aria-label={'Lịch làm việc của '+a.displayName} disabled={navigationDisabled} onClick={()=>{setSelected(a.id);setTab('schedule');}}><CalendarDays size={15} aria-hidden="true"/>Lịch làm việc</button><button type="button" aria-label={'Sửa bác sĩ '+a.displayName} disabled={navigationDisabled} onClick={()=>{setSelected(a.id);setTab('profile');}}><Pencil size={15} aria-hidden="true"/>Sửa</button></div></td></tr>)}</ManagementTable></section>;
}
function ScheduleConfiguration({affiliation,session,disabled,revision,act}:ConfigurationProps&{affiliation:api.Affiliation}){
 const drafts=useDraftGuard(),[editing,setEditing]=useState<string|null>(null);
 const {data,error}=useConfigurationSource(()=>api.schedules(session,affiliation.id),[session.token,session.clinic,session.branch,affiliation.id,revision]);
 if(error)return <p role="alert">{error}</p>;if(!data)return <p role="status">Đang tải lịch bác sĩ…</p>;
 const current=data.schedules.find(s=>s.id===editing),today=date();
 const status=(s:api.Schedule)=>!s.active?'Ngừng hoạt động':s.effectiveFrom>today?'Chưa đến hiệu lực':s.effectiveUntil&&s.effectiveUntil<=today?'Đã hết hiệu lực':'Đang áp dụng';
 return <section className="management-schedules"><div className="management-subheading"><div><h3>Lịch làm việc</h3><p className="muted-copy">Giờ Việt Nam. Thay đổi áp dụng cho việc đặt lịch mới.</p></div><button type="button" className="booking-primary" disabled={disabled||!!drafts?.active} onClick={()=>setEditing('new')}>Thêm khung lịch</button></div>{editing!==null&&<section className="management-editor"><h3>{current?'Sửa khung lịch':'Thêm khung lịch'}</h3><ConfigurationForm key={current?`${current.id}-${current.version}`:'new-schedule'} fields={scheduleFields} initial={current?{dayOfWeek:String(current.dayOfWeek),startTime:current.startTime.slice(0,5),endTime:current.endTime.slice(0,5),effectiveFrom:current.effectiveFrom,effectiveUntil:current.effectiveUntil??'',active:current.active}:{dayOfWeek:'1',startTime:'08:00',endTime:'17:00',effectiveFrom:today,active:true}} disabled={disabled} label="Lưu khung lịch" onCancel={()=>setEditing(null)} validate={v=>String(v.endTime)<=String(v.startTime)?'Giờ kết thúc phải sau giờ bắt đầu.':validateDates(v)} submit={v=>act(async()=>{await api.saveSchedule(session,affiliation.id,{...scheduleBody(v),...(current?{expectedVersion:current.version}:{})},current?.id);setEditing(null);})}/></section>}<ManagementTable caption={'Lịch làm việc của '+affiliation.displayName} headers={['Ngày','Khung giờ','Thời gian áp dụng','Trạng thái','Thao tác']} empty={!data.schedules.length}>{[...data.schedules].sort((a,b)=>a.dayOfWeek-b.dayOfWeek||a.startTime.localeCompare(b.startTime)).map(s=><tr key={s.id}><td><strong>{days[s.dayOfWeek]}</strong></td><td className="management-nowrap">{s.startTime.slice(0,5)} – {s.endTime.slice(0,5)}</td><td>{s.effectiveFrom.split('-').reverse().join('/')}<small>{s.effectiveUntil?'Đến trước '+s.effectiveUntil.split('-').reverse().join('/'):'Không giới hạn ngày kết thúc'}</small></td><td><span className="task-status">{status(s)}</span></td><td><button type="button" disabled={disabled||!!drafts?.active} aria-label={'Sửa lịch '+days[s.dayOfWeek]+' '+s.startTime.slice(0,5)} onClick={()=>setEditing(s.id)}>Sửa</button></td></tr>)}</ManagementTable></section>;
}
