import {useAuthoritativeSync} from './useAuthoritativeSync';
import {doctorSubscription} from '../api/realtime';
import {DatePreview} from './DatePreview';
import { useEffect,useRef,useState,type ReactNode } from 'react';
import * as api from '../api/medical';
import type { Scope } from '../api/reception';
import { RequestError } from '../api/booking';
import { stableOperationKey } from '../api/idempotency';
const blank:api.Note={reasonForVisit:'',medicalHistory:'',allergies:'',vitals:'',examination:'',preliminaryDiagnosis:'',conclusion:'',instructions:'',followUpDate:null};
const fields:[keyof Omit<api.Note,'followUpDate'>,string,number][]=[['reasonForVisit','Lý do khám',2000],['medicalHistory','Tiền sử',4000],['allergies','Dị ứng',2000],['vitals','Sinh hiệu',2000],['examination','Khám lâm sàng',4000],['preliminaryDiagnosis','Chẩn đoán sơ bộ',2000],['conclusion','Kết luận',4000],['instructions','Hướng dẫn',4000]];
export function MedicalPanel({scope,id,status='IN_PROGRESS',onValidated,onNavigationLock,onWorklistChanged,onComplete,completionBlockReason,actions}:{scope:Scope;id:string;status?:string;onValidated?:(version:number|null)=>void;onNavigationLock?:(reason:string|null)=>void;onWorklistChanged?:()=>void;onComplete?:(caseVersion:number)=>Promise<void>;completionBlockReason?:string;actions?:ReactNode}){
 const [draft,setDraft]=useState<api.Draft|null>(null),[note,setNote]=useState(blank),[orders,setOrders]=useState<api.Order[]>([]),[offerings,setOfferings]=useState<api.Offering[]>([]),[offering,setOffering]=useState('');
 const [reason,setReason]=useState(''),[dirty,setDirty]=useState(false),[autosave,setAutosave]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[uncertain,setUncertain]=useState(false),[comparison,setComparison]=useState<api.Draft|null>(null);
 const actionBar=useRef<HTMLDivElement>(null);
 useEffect(()=>{const element=actionBar.current,caseElement=element?.closest('.doctor-case');if(!element||!caseElement)return;const measure=()=>{const rect=caseElement.getBoundingClientRect();element.style.setProperty('--action-left',rect.left+'px');element.style.setProperty('--action-width',rect.width+'px');};measure();const observer=typeof ResizeObserver!=='undefined'?new ResizeObserver(measure):null;observer?.observe(caseElement);window.addEventListener('resize',measure);return()=>{observer?.disconnect();window.removeEventListener('resize',measure);};},[draft?.encounterId]);
 const running=useRef(false),revision=useRef(0),saveAttempt=useRef<{body:{expectedDocumentVersion:number;content:api.Note;reason:string};key:string;revision:number}|null>(null);
 const commandAttempt=useRef<(()=>Promise<void>)|null>(null);const scopeRef=useRef(scope);scopeRef.current=scope;
 const [caseStale,setCaseStale]=useState(false);
 const navigationReason=uncertain?'Thử lại hồ sơ đang chờ để xác minh kết quả trước khi đổi lượt.':busy?'Đợi thao tác hồ sơ xử lý xong trước khi đổi lượt.':dirty||comparison?'Lưu hoặc đối chiếu bản nháp trước khi đổi lượt, địa điểm hoặc rời màn hình.':null;
 useEffect(()=>{onNavigationLock?.(navigationReason);return()=>onNavigationLock?.(null);},[navigationReason,onNavigationLock]);
 const validatedCallback=useRef(onValidated);validatedCallback.current=onValidated;
 useEffect(()=>{validatedCallback.current?.(draft?.status==='VALIDATED'?draft.caseVersion:null);},[draft?.status,draft?.caseVersion]);
 useEffect(()=>{let active=true;Promise.all([api.draft(scope,id),api.orders(scope,id),api.offerings(scope)]).then(([d,o,f])=>{if(active){setDraft(d);setNote(d.content??blank);setOrders(o);setOfferings(f.filter(x=>x.active&&x.offering.active));}}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Không tải được hồ sơ khám');});return()=>{active=false;};},[scope.token,scope.clinic,scope.branch,id]);
 const editState=useRef({dirty,revision:revision.current});editState.current={dirty,revision:revision.current};
 useAuthoritativeSync({key:scope.token+scope.clinic+scope.branch+id,enabled:!!scope.token&&!!id,blocked:busy||uncertain,subscriptions:[doctorSubscription(scope,'medical')],refresh:async context=>{
  const localRevision=revision.current;
  try{const [d,o]=await Promise.all([api.draft(scope,id),api.orders(scope,id)]);if(!context.current()||running.current)return;
   setOrders(o);setCaseStale(false);
   if(editState.current.dirty||localRevision!==revision.current){if(d.documentVersion!==draft?.documentVersion){setComparison(d);setAutosave(false);setMessage('Hồ sơ tại máy chủ vừa thay đổi; nội dung đang nhập được giữ để đối chiếu.');}}
   else{setDraft(d);setNote(d.content??blank);}
  }catch(e){if(context.current()){setCaseStale(true);setError('Chưa cập nhật được hồ sơ máy chủ. Hệ thống sẽ thử lại.');}throw e;}
 },onDenied:()=>{setOrders([]);setCaseStale(true);setError('Quyền truy cập hồ sơ đã thay đổi.');}});
 async function run(action:()=>Promise<void>){if(running.current)return;running.current=true;setBusy(true);setError('');setMessage('');try{await action();}catch(e){setError(e instanceof Error?e.message:'Chưa xác định kết quả');}finally{running.current=false;setBusy(false);}}
 async function persistDraft(){
  if(!draft)return null;
  if(!saveAttempt.current){const body={expectedDocumentVersion:draft.documentVersion,content:{...note},reason:reason.trim()||'Lưu bản nháp của bác sĩ'};saveAttempt.current={body,key:await stableOperationKey('medical-draft',{clinic:scope.clinic,branch:scope.branch,id,...body}),revision:revision.current};}
  const original=saveAttempt.current;
  try{const d=await api.save(scopeRef.current,id,original.body,original.key);saveAttempt.current=null;setUncertain(false);setComparison(null);setCaseStale(false);setDraft(d);if(revision.current===original.revision)setDirty(false);setMessage('Đã lưu bản nháp phiên bản '+d.documentVersion+'.');return d;}
  catch(e){if(e instanceof RequestError&&e.status>=400&&e.status<500){saveAttempt.current=null;setAutosave(false);setUncertain(false);}else setUncertain(true);throw e;}
 }
 async function save(){await persistDraft();}
 useEffect(()=>{if(!autosave||!dirty||busy||uncertain||comparison||!draft||draft.status!=='DRAFT'||error)return;const timer=window.setTimeout(()=>void run(save),1000);return()=>window.clearTimeout(timer);},[autosave,dirty,note,busy,uncertain,comparison,draft,error]);
 async function reload(){const [d,o]=await Promise.all([api.draft(scope,id),api.orders(scope,id)]);setOrders(o);setCaseStale(false);if(dirty){setComparison(d);setAutosave(false);setMessage('Đã tải bản máy chủ để đối chiếu; nội dung đang sửa vẫn được giữ.');}else{setDraft(d);setNote(d.content??blank);}}
 async function syncCase(expectedDocumentVersion=draft?.documentVersion){try{const d=await api.draft(scope,id);if(d.documentVersion!==expectedDocumentVersion){setComparison(d);setAutosave(false);}else setDraft(d);}catch{setCaseStale(true);setError('Thao tác đã được ghi nhận, nhưng chưa tải được phiên bản hồ sơ mới. Tải phiên bản để đối chiếu trước khi tiếp tục.');}}
 async function execute(action:()=>Promise<void>){commandAttempt.current=action;try{await action();commandAttempt.current=null;setUncertain(false);}catch(e){if(e instanceof RequestError&&e.status>=400&&e.status<500){commandAttempt.current=null;setUncertain(false);}else setUncertain(true);throw e;}}
 async function addOrder(){if(!draft||!offering)return;const currentDraft=dirty?await persistDraft():draft;if(!currentDraft)return;const selectedOffering=offerings.find(item=>item.offering.id===offering)?.offering.name;const orderReason=reason.trim()||`Bác sĩ chỉ định ${selectedOffering||'dịch vụ trong quá trình khám'}`;const body={expectedCaseVersion:currentDraft.caseVersion,offeringId:offering,reason:orderReason};const key=await stableOperationKey('medical-order',{clinic:scope.clinic,branch:scope.branch,id,...body});await execute(async()=>{const o=await api.order(scope,id,body,key);setOrders(current=>[...current.filter(x=>x.id!==o.id),o]);setMessage('Đã tạo chỉ định từ danh mục và giá hiện hành.');await syncCase(currentDraft.documentVersion);});}
 async function review(o:api.Order){const currentDraft=dirty?await persistDraft():draft;if(!currentDraft)return;const originalReason=reason.trim()||`Bác sĩ xem và xác nhận kết quả ${o.name}`;const key=await stableOperationKey('medical-review',{clinic:scope.clinic,branch:scope.branch,id:o.id,version:o.version,resultVersion:o.resultVersion,reason:originalReason});await execute(async()=>{const updated=await api.review(scope,o,originalReason,key);setOrders(current=>current.map(x=>x.id===updated.id?updated:x));setMessage('Đã ghi nhận bác sĩ xem và duyệt kết quả.');await syncCase(currentDraft.documentVersion);onWorklistChanged?.();});}
 async function validate(){if(!draft)return null;const version=draft.caseVersion,originalReason=reason;const key=await stableOperationKey('medical-validate',{clinic:scope.clinic,branch:scope.branch,id,version,reason:originalReason});let validated:api.Draft|null=null;await execute(async()=>{const d=await api.validate(scope,id,version,originalReason,key);validated=d;setDraft(d);setMessage('Đã khóa nội dung chuyên môn để hoàn tất lượt khám.');});return validated;}
 const locked=busy||uncertain||caseStale||draft?.status==='VALIDATED'||status!=='IN_PROGRESS';
 const validationProblem=!draft?'Hồ sơ chưa sẵn sàng.':dirty?'Cần lưu các thay đổi trước khi hoàn tất.':!reason.trim()?'Cần nhập lý do lưu hoặc duyệt hồ sơ.':!note.reasonForVisit.trim()?'Cần hoàn thành “Lý do khám”.':!note.conclusion.trim()?'Cần hoàn thành “Kết luận”.':!note.instructions.trim()?'Cần hoàn thành “Hướng dẫn”.':orders.some(o=>!['REVIEWED','REJECTED','CANCELLED'].includes(o.state))?'Cần xử lý xong mọi chỉ định và kết quả trước khi hoàn tất chuyên môn.':completionBlockReason??null;
 async function completeProfessional(){if(!draft||!onComplete||status!=='IN_PROGRESS'||validationProblem)return;const validated=draft.status==='VALIDATED'?draft:await validate();if(!validated)return;await onComplete(validated.caseVersion);onWorklistChanged?.();}
 return <section className="medical-panel" aria-labelledby="medical-title">
  <div className="medical-panel-heading"><div><span className="eyebrow">Hồ sơ lâm sàng</span><h2 id="medical-title">Hồ sơ khám và chỉ định</h2></div><button type="button" disabled={busy} onClick={()=>void run(reload)}>Tải phiên bản mới</button></div>
  {error&&<p role="alert" className="booking-error">{error}</p>}{message&&<p role="status">{message}</p>}{!draft&&!error&&<p role="status">Đang tải hồ sơ khám…</p>}
  {uncertain&&<p role="status">Chưa nhận xác nhận; nội dung yêu cầu được giữ nguyên. <button type="button" disabled={busy} onClick={()=>void run(()=>saveAttempt.current?save():commandAttempt.current?execute(commandAttempt.current):Promise.resolve())}>Thử lại hồ sơ đang chờ</button></p>}
  {draft&&<>
   <div className="medical-document-status"><span>{draft.status==='VALIDATED'?'Đã khóa nội dung chuyên môn':'Bản nháp'} · Phiên bản {draft.documentVersion}</span><span>{dirty?'Có thay đổi chưa lưu':draft.savedAt?'Đã lưu lúc '+new Date(draft.savedAt).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'}):'Bản nháp đã lưu'}</span></div>
   <nav className="medical-section-nav" aria-label="Đi tới phần hồ sơ"><a href="#medical-intake">Tiếp nhận</a><a href="#medical-exam">Khám lâm sàng</a><a href="#medical-diagnosis">Chẩn đoán</a><a href="#medical-orders">Chỉ định</a><a href="#medical-results">Kết quả</a><a href="#medical-conclusion">Kết luận</a><a href="#medical-follow-up">Tái khám</a></nav>
   {comparison&&<div className="booking-confirm"><h3>Đối chiếu bản máy chủ</h3><p>Phiên bản {comparison.documentVersion} </p><dl className="draft-comparison">{fields.map(([field,label])=><div key={field}><dt>{label}</dt><dd><strong>Đang sửa:</strong> {note[field]||'Chưa ghi nhận'}</dd><dd><strong>Máy chủ:</strong> {comparison.content?.[field]||'Chưa ghi nhận'}</dd></div>)}</dl><button type="button" disabled={uncertain||busy} onClick={()=>{setDraft(comparison);setNote(comparison.content??blank);setDirty(false);setComparison(null);saveAttempt.current=null;setCaseStale(false);setError('');}}>Dùng bản từ máy chủ</button><button type="button" disabled={uncertain||busy} onClick={()=>{setDraft(comparison);setComparison(null);saveAttempt.current=null;setCaseStale(false);setError('');}}>Giữ nội dung đang sửa trên phiên bản mới</button></div>}
   <fieldset className="reception-actions medical-clinical-form" disabled={locked}>
    <section id="medical-intake" className="medical-form-section"><header><span>Thông tin ban đầu</span><h3>Tiếp nhận và tiền sử</h3></header><div className="medical-note-fields">{fields.slice(0,4).map(([field,label,max])=><label key={field}>{label}<textarea value={note[field]} maxLength={max} onChange={e=>{revision.current++;setNote(n=>({...n,[field]:e.target.value}));setDirty(true);}}/></label>)}</div></section>
    <section id="medical-exam" className="medical-form-section"><header><span>Ghi nhận của bác sĩ</span><h3>Khám lâm sàng</h3></header>{fields.slice(4,5).map(([field,label,max])=><label key={field}>{label}<textarea value={note[field]} maxLength={max} onChange={e=>{revision.current++;setNote(n=>({...n,[field]:e.target.value}));setDirty(true);}}/></label>)}</section>
    <section id="medical-diagnosis" className="medical-form-section"><header><span>Ghi nhận của bác sĩ</span><h3>Chẩn đoán</h3></header>{fields.slice(5,6).map(([field,label,max])=><label key={field}>{label}<textarea value={note[field]} maxLength={max} onChange={e=>{revision.current++;setNote(n=>({...n,[field]:e.target.value}));setDirty(true);}}/></label>)}</section>
    <section id="medical-orders" className="medical-form-section"><header><span>Chỉ định</span><h3>Dịch vụ chỉ định</h3></header><label>Dịch vụ chỉ định<select value={offering} onChange={e=>setOffering(e.target.value)}><option value="">Chọn dịch vụ từ danh mục</option>{offerings.map(o=><option key={o.offering.id} value={o.offering.id}>{o.offering.name}</option>)}</select></label>{dirty&&<p className="muted-copy" role="status">Các thay đổi trong hồ sơ sẽ được lưu trước khi tạo chỉ định.</p>}<button type="button" disabled={!offering||!!comparison} onClick={()=>void run(addOrder)}>Tạo chỉ định</button></section>
    <section id="medical-conclusion" className="medical-form-section"><header><span>Ghi nhận của bác sĩ</span><h3>Kết luận và hướng dẫn</h3></header><div className="medical-note-fields">{fields.slice(6).map(([field,label,max])=><label key={field}>{label}<textarea value={note[field]} maxLength={max} onChange={e=>{revision.current++;setNote(n=>({...n,[field]:e.target.value}));setDirty(true);}}/></label>)}</div></section>
    <section id="medical-follow-up" className="medical-form-section"><header><span>Theo dõi</span><h3>Tái khám</h3></header><label>Ngày hẹn tái khám đề xuất<input aria-label="Ngày hẹn tái khám đề xuất" type="date" value={note.followUpDate??''} onChange={e=>{revision.current++;setNote(n=>({...n,followUpDate:e.target.value||null}));setDirty(true);}}/><DatePreview value={note.followUpDate??''}/></label></section>
    <section className="medical-form-section medical-save-context"><label>Lý do lưu hoặc duyệt hồ sơ<textarea maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="medical-autosave"><input type="checkbox" checked={autosave} onChange={e=>setAutosave(e.target.checked)}/>Tự động lưu bản nháp sau khi ngừng nhập</label></section>
   </fieldset>
   <section id="medical-results" className="medical-form-section medical-results-section"><header><span>Kết quả</span><h3>Chỉ định và kết quả</h3></header><ul className="doctor-worklist medical-order-list" aria-label="Chỉ định của lượt khám">{orders.map(o=><li key={o.id} className="medical-order-item"><div className="medical-order-heading"><strong>{o.name}</strong><span className="task-status" data-state={o.state}>{o.state==='RESULTED'?'ĐÃ CÓ KẾT QUẢ':o.state==='REVIEWED'?'ĐÃ XEM KẾT QUẢ':({ORDERED:'Đã chỉ định',ACCEPTED:'Đã tiếp nhận',PROCESSING:'Đang thực hiện',REJECTED:'Đã từ chối',CANCELLED:'Đã hủy'} as Record<string,string>)[o.state]??o.state}</span></div>{o.orderedAt&&<small>Chỉ định: {new Date(o.orderedAt).toLocaleString('vi-VN')}</small>}{o.result&&<><details className="medical-result-detail"><summary>Xem kết quả</summary><p>{o.result.content}</p><small>Nguồn: {o.result.sourceRef} · Phiên bản {o.result.version}</small></details><small>Kết quả: {new Date(o.result.createdAt).toLocaleString('vi-VN')}</small></>}{o.state==='RESULTED'&&<><p className="medical-review-state">Chưa được bác sĩ xem xét</p><button type="button" disabled={locked||!!comparison} onClick={()=>void run(()=>review(o))}>Xem và xác nhận kết quả</button></>}{o.state==='REVIEWED'&&<p className="medical-review-state is-reviewed">✓ Bác sĩ đã xem kết quả{o.reviewedAt?' · '+new Date(o.reviewedAt).toLocaleString('vi-VN'):''}</p>}</li>)}</ul>{orders.length===0&&<p className="task-empty">Chưa có chỉ định trong lượt khám này.</p>}</section>
   {status==='AWAITING_RESULTS'&&<p role="status" className="medical-awaiting-note">Hồ sơ đang ở trạng thái chờ kết quả và chỉ đọc. Khi có kết quả mới, chọn “Tiếp tục xử lý” từ worklist để đưa lượt trở lại phiên khám trước khi bác sĩ duyệt kết quả hoặc sửa hồ sơ.</p>}
   <div ref={actionBar} className="medical-action-bar"><span role="status">{uncertain?'Cần xác minh kết quả lưu':dirty?'Có thay đổi chưa lưu':draft.savedAt?'Đã lưu lúc '+new Date(draft.savedAt).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'}):draft.status==='VALIDATED'?'Đã khóa nội dung':'Bản nháp đã lưu'}</span><button type="button" disabled={locked||!dirty||!!comparison} onClick={()=>void run(save)}>Lưu bản nháp</button>{onComplete?<button type="button" className="booking-primary" disabled={busy||uncertain||caseStale||status!=='IN_PROGRESS'||!!validationProblem} onClick={()=>void run(completeProfessional)}>Hoàn tất chuyên môn</button>:<button type="button" disabled={locked||!!validationProblem} onClick={()=>void run(async()=>{await validate();})}>Xác nhận nội dung chuyên môn</button>}{actions}</div>
   {status==='IN_PROGRESS'&&validationProblem&&<p className="medical-completion-hint" role="status">ⓘ {validationProblem}</p>}
  </>}
 </section>;
}
