import {useState,useRef} from 'react';
import {Pencil,ShieldOff} from 'lucide-react';
import * as api from '../api/configuration';
import {useSession} from '../auth/SessionProvider';
import {roleNames} from '../auth/access';
import {ConfigurationForm,type Field} from './ConfigurationForm';
import {useConfigurationSource,type ConfigurationProps} from './ConfigurationPanel';
import {useDraftGuard,useFormDraft} from './DraftBoundary';
import {ConfirmDialog} from './ConfirmDialog';
import {ManagementTable,ManagementToolbar,ManagementDetail,matchesQuery} from './ManagementTable';

const roles=['STAFF','DOCTOR'].map(value=>({value,label:roleNames[value]}));
const accountStatusNames:Record<string,string>={ACTIVE:'Đang hoạt động',LOCKED:'Đã khóa',INACTIVE:'Ngừng hoạt động'};
const roleScopeNames:Record<string,string>={ADMIN:'Quản trị cấu hình & giám sát',STAFF:'Tiếp nhận · Hàng đợi · Thu phí',DOCTOR:'Khám · Nghiệp vụ chuyên môn'};
const profileFields:Field[]=[{key:'fullName',label:'Họ và tên',required:true,maxLength:255},{key:'email',label:'Email đăng nhập',type:'email',required:true,maxLength:180},{key:'phone',label:'Số điện thoại',type:'tel',maxLength:50}];
export function MembershipConfiguration({session,disabled,revision,act}:ConfigurationProps){
 const shared=useSession(),drafts=useDraftGuard();
 const {data,error}=useConfigurationSource(()=>api.staff(session),[session.token,session.clinic,revision]);
 const [query,setQuery]=useState(''),[selected,setSelected]=useState(''),[creating,setCreating]=useState(false),[removing,setRemoving]=useState<api.StaffRow|null>(null),[statusChange,setStatusChange]=useState<api.StaffRow|null>(null);
 const navigationDisabled=disabled||!!drafts?.active;
 if(error)return <p role="alert">{error}</p>;if(!data)return <p role="status">Đang tải nhân sự…</p>;
 const current=data.find(r=>r.membership.id===selected),rows=data.filter(r=>matchesQuery(query,r.account?.fullName,r.account?.email,r.account?.phone,roleNames[r.membership.role]));
 const protectedRow=(r:api.StaffRow)=>r.membership.clinicOwner||r.membership.userId===shared?.workspaceSession?.actor.userId;
 if(creating)return <ManagementDetail title="Cấp tài khoản nhân sự" disabled={navigationDisabled} onBack={()=>setCreating(false)}><CreateStaffForm session={session} disabled={disabled} onCancel={()=>setCreating(false)} submit={body=>act(async()=>{await api.createStaff(session,body);setCreating(false);})}/></ManagementDetail>;
 if(current?.account){const manageable=['STAFF','DOCTOR'].includes(current.membership.role)&&!protectedRow(current);const locked=current.account.status==='LOCKED';return <ManagementDetail title={current.account.fullName} disabled={navigationDisabled} onBack={()=>setSelected('')}><p className="muted-copy">Quản lý thông tin đăng nhập, vai trò và trạng thái tài khoản của bác sĩ hoặc lễ tân.</p><h3>Thông tin tài khoản</h3><p><strong>Mã tài khoản:</strong> {current.account.accountCode??'Chưa có mã'} · <strong>Trạng thái:</strong> {accountStatusNames[current.account.status]??current.account.status}</p><ConfigurationForm key={`staff-${current.membership.id}-${revision}`} fields={profileFields} initial={{fullName:current.account.fullName,email:current.account.email,phone:current.account.phone??''}} disabled={disabled||!manageable} label="Lưu thông tin tài khoản" onCancel={()=>setSelected('')} submit={v=>act(()=>api.updateStaff(session,current.membership.id,{fullName:String(v.fullName),email:String(v.email),phone:String(v.phone)}))}/><h3>Vai trò tại phòng khám</h3><ConfigurationForm key={`role-${current.membership.id}-${current.membership.version}`} fields={[{key:'role',label:'Vai trò',required:true,options:roles}]} initial={{role:current.membership.role}} disabled={disabled||!manageable} label="Lưu vai trò" submit={v=>act(()=>api.updateStaffRole(session,current.membership,String(v.role)))}/>{manageable&&<><h3>Quyền đăng nhập</h3><p className="muted-copy">Khóa tài khoản khi nhân sự tạm nghỉ hoặc cần dừng truy cập. Mở lại khi nhân sự quay lại làm việc.</p><button type="button" className={locked?'button-secondary':'management-danger'} disabled={navigationDisabled} onClick={()=>setStatusChange(current)}>{locked?'Mở khóa tài khoản':'Khóa tài khoản'}</button><h3>Đặt lại mật khẩu</h3><ResetPasswordForm disabled={disabled} submit={password=>act(()=>api.resetStaffPassword(session,current.membership.id,password))}/></>}{statusChange&&<ConfirmDialog title={locked?'Mở khóa tài khoản?':'Khóa tài khoản?'} confirmLabel={locked?'Mở khóa':'Khóa tài khoản'} busy={disabled} onCancel={()=>setStatusChange(null)} onConfirm={()=>void act(async()=>{await api.setStaffStatus(session,statusChange.membership.id,locked?'ACTIVE':'LOCKED');setStatusChange(null);})}><p><strong>{current.account.fullName}</strong><br/>{current.account.email}</p><p>{locked?'Nhân sự sẽ có thể đăng nhập lại bằng tài khoản này.':'Nhân sự sẽ không thể đăng nhập mới; các phiên làm mới hiện có sẽ bị thu hồi.'}</p></ConfirmDialog>}</ManagementDetail>;}
 return <section className="management-section"><p className="management-intro">Cấp và quản lý tài khoản theo vai trò phòng khám. Vai trò quyết định phạm vi nghiệp vụ; Quản trị phòng khám không mặc định kế thừa quyền Lễ tân, Thu ngân hoặc Bác sĩ.</p><ManagementToolbar label="Tìm tên, email hoặc số điện thoại" query={query} onQuery={setQuery} count={rows.length} onAdd={()=>setCreating(true)} addLabel="Cấp tài khoản" disabled={navigationDisabled}/><ManagementTable caption="Nhân sự phòng khám" headers={['Nhân sự','Liên hệ','Vai trò','Tài khoản','Thao tác']} empty={!rows.length}>{rows.map(row=>{const manageable=['STAFF','DOCTOR'].includes(row.membership.role)&&!protectedRow(row);return <tr key={row.membership.id}><td><strong>{row.account?.fullName??'Chưa có thông tin tài khoản'}</strong><small>{row.account?.accountCode??''}{row.membership.clinicOwner?' · Chủ phòng khám':''}</small></td><td><span>{row.account?.email??'—'}</span><small>{row.account?.phone||'Chưa có số điện thoại'}</small></td><td><strong>{roleNames[row.membership.role]??row.membership.role}</strong><small>{roleScopeNames[row.membership.role]??'Theo phân công hiện tại'}</small></td><td><span className="task-status" data-state={row.account?.status??row.membership.status}>{row.account?accountStatusNames[row.account.status]??row.account.status:(row.membership.status==='ACTIVE'?'Đang làm việc':'Chờ cấp quyền')}</span></td><td><div className="management-actions"><button type="button" disabled={navigationDisabled||!manageable||!row.account} aria-label={'Quản lý tài khoản '+row.account?.fullName} onClick={()=>setSelected(row.membership.id)}><Pencil size={15} aria-hidden="true"/>Quản lý</button><button type="button" className="management-danger" disabled={navigationDisabled||!manageable} aria-label={'Thu hồi quyền '+row.account?.fullName} onClick={()=>setRemoving(row)}><ShieldOff size={15} aria-hidden="true"/>Thu hồi quyền</button></div></td></tr>;})}</ManagementTable>{removing&&<ConfirmDialog title="Thu hồi quyền tại phòng khám?" confirmLabel="Thu hồi quyền" busy={disabled} onCancel={()=>setRemoving(null)} onConfirm={()=>void act(async()=>{await api.revoke(session,removing.membership,'Quản trị thu hồi quyền nhân sự khỏi phòng khám');setRemoving(null);})}><p><strong>{removing.account?.fullName}</strong><br/>{removing.account?.email}</p><p>Membership sẽ bị thu hồi, không xóa tài khoản hay lịch sử. Các tham chiếu khám, vận hành và thu phí đã ghi vẫn được giữ để truy vết.</p></ConfirmDialog>}</section>;
}
function CreateStaffForm({session,disabled,submit,onCancel}:{session:api.Session;disabled:boolean;submit:(body:Parameters<typeof api.createStaff>[1])=>Promise<void>;onCancel:()=>void}){
 const [email,setEmail]=useState(''),[name,setName]=useState(''),[phone,setPhone]=useState(''),[password,setPassword]=useState(''),[role,setRole]=useState('STAFF');
 const [found,setFound]=useState<api.StaffAccount|null>(null),[checked,setChecked]=useState(''),[useExisting,setUseExisting]=useState(false),[checking,setChecking]=useState(false),[error,setError]=useState('');
 const epoch=useRef(0);
 const dirty=!!(email||name||phone||password||role!=='STAFF');
 const otherDraft=useFormDraft(dirty,'Cấp tài khoản nhân sự',()=>{epoch.current++;setEmail('');setName('');setPhone('');setPassword('');setRole('STAFF');setFound(null);setChecked('');setUseExisting(false);setChecking(false);});
 async function lookup(){const normalized=email.trim().toLowerCase();if(!normalized||!email.includes('@'))return;const request=++epoch.current;setChecking(true);setError('');try{const result=await api.lookupStaff(session,normalized);if(request!==epoch.current)return;setFound(result.account);setChecked(normalized);setUseExisting(false);return result.account;}catch(e){if(request===epoch.current)setError(e instanceof Error?e.message:'Không thể kiểm tra email.');}finally{if(request===epoch.current)setChecking(false);}}
 async function save(){let account=found;if(checked!==email.trim().toLowerCase()){const result=await lookup();if(result===undefined)return;account=result;if(account){setError('Email đã có tài khoản. Kiểm tra thông tin và chọn dùng tài khoản này.');return;}}if(account&&!useExisting){setError('Chọn dùng tài khoản hiện có hoặc nhập email khác.');return;}await submit({email:email.trim(),fullName:account?.fullName??name,phone:account?.phone??phone,password:account?null:password,role,useExistingAccount:!!account&&useExisting});}
 return <form onSubmit={e=>{e.preventDefault();void save();}}>{error&&<p role="alert" className="booking-error">{error}</p>}<fieldset disabled={disabled||checking||otherDraft} className="configuration-fields"><label>Email đăng nhập<input type="email" required autoComplete="off" value={email} onChange={e=>{epoch.current++;setEmail(e.target.value);setChecked('');setFound(null);setUseExisting(false);}}/></label><div className="management-lookup"><button type="button" disabled={!email.trim()} onClick={()=>void lookup()}>Kiểm tra email</button></div>{found?<div className="configuration-wide management-existing"><strong>{found.fullName}</strong><p>{found.email} · Tài khoản đã đăng ký · {accountStatusNames[found.status]??found.status}</p><label className="configuration-check"><input type="checkbox" checked={useExisting} onChange={e=>setUseExisting(e.target.checked)}/>Dùng tài khoản này cho nhân sự mới</label><small>Tài khoản tiếp tục dùng mật khẩu hiện có.</small></div>:<><label>Họ và tên<input required maxLength={255} value={name} onChange={e=>setName(e.target.value)}/></label><label>Số điện thoại<input type="tel" maxLength={50} value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Mật khẩu ban đầu<input type="password" autoComplete="new-password" required minLength={8} maxLength={100} value={password} onChange={e=>setPassword(e.target.value)}/><small>Tối thiểu 8 ký tự. Đây là mật khẩu tạm để nhân sự đăng nhập lần đầu.</small></label></>}<label>Vai trò<select value={role} onChange={e=>setRole(e.target.value)}>{roles.map(r=><option key={r.value} value={r.value}>{r.label}</option>)}</select></label><div className="configuration-form-actions"><button className="booking-primary">Cấp tài khoản</button><button type="button" onClick={onCancel}>Hủy</button></div></fieldset>{checking&&<p role="status">Đang kiểm tra email…</p>}{checked&&!found&&<p role="status" className="muted-copy">Email chưa đăng ký. Tài khoản mới sẽ được tạo khi bạn cấp tài khoản.</p>}</form>;
}

function ResetPasswordForm({disabled,submit}:{disabled:boolean;submit:(password:string)=>Promise<void>}){
 const [password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[error,setError]=useState('');
 const otherDraft=useFormDraft(!!(password||confirmation),'Đặt lại mật khẩu nhân sự',()=>{setPassword('');setConfirmation('');setError('');});
 async function save(){if(password.length<8){setError('Mật khẩu mới cần ít nhất 8 ký tự.');return;}if(password!==confirmation){setError('Mật khẩu xác nhận chưa khớp.');return;}setError('');await submit(password);setPassword('');setConfirmation('');}
 return <form onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={disabled||otherDraft} className="configuration-fields"><label>Mật khẩu tạm mới<input aria-label="Mật khẩu tạm mới" type="password" autoComplete="new-password" minLength={8} maxLength={100} required value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Xác nhận mật khẩu<input type="password" autoComplete="new-password" minLength={8} maxLength={100} required value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><div className="configuration-form-actions"><button className="button-secondary" disabled={!password||!confirmation}>Đặt lại mật khẩu</button></div></fieldset>{error&&<p role="alert" className="booking-error">{error}</p>}<p className="muted-copy">Đặt lại mật khẩu sẽ thu hồi refresh token hiện có của tài khoản.</p></form>;
}
