import {DatePreview} from './DatePreview';
import {UsersRound,Stethoscope,Wallet,ClipboardCheck} from 'lucide-react';
import {usePanelSession} from '../auth/SessionProvider';
import {SourceSessionState} from '../auth/SourceSessionState';
import { useEffect,useRef,useState } from 'react';
import { signIn } from '../api/booking';
import { contexts,directory,type Directory,type Scope } from '../api/reception';
import * as api from '../api/operations';
type Row={id:string;name:string;encounter:api.EncounterSummary|null;billing:api.BillingSummary|null};
function CareFlowChart({summary}:{summary:api.EncounterSummary}){const stages=[['Chờ khám',summary.waitingTickets],['Đang khám',summary.servingTickets],['Chờ kết quả',summary.awaitingResults]] as const;const max=Math.max(1,...stages.map(([,value])=>value));return <div className="care-flow-chart" role="group" aria-label="Lượt khám theo trạng thái trong ngày">{stages.map(([label,value])=><div className="care-flow-row" key={label}><div><span>{label}</span><strong>{value}</strong></div><div className="care-flow-track" aria-hidden="true"><span style={{width:`${value/max*100}%`}}/></div></div>)}</div>;}
const money=(n:number)=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND'}).format(n);
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export function OperationsPanel({onClinic}:{onClinic?:(name:string)=>void}) {
 const shared=usePanelSession(login);
 const [token,setToken]=useState('');const [clinic,setClinic]=useState<Directory|null>(null);const branch='ALL';const [date,setDate]=useState(today);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [rows,setRows]=useState<Row[]|null>(null);const epoch=useRef(0);
 async function login(){if(busy)return;const current=++epoch.current;setBusy(true);setError('');setRows(null);try{const access=shared?.session?.token??(await signIn(email,password)).data.accessToken;setEmail(shared?.session?.email??email);setPassword('');const memberships=(await contexts(access)).filter(m=>['ADMIN'].includes(m.role));const ids=[...new Set(memberships.map(m=>m.clinicId))];const requested=new URLSearchParams(location.search).get('clinicId');const id=requested?(ids.includes(requested)?requested:null):ids.length===1?ids[0]:null;if(!id)throw new Error('Phiên tổng quan cần quyền Chủ cơ sở hoặc Quản lý tại phòng khám trên đường dẫn Workspace.');const c=await directory(access,id);if(current!==epoch.current)return;setToken(access);setClinic(c);onClinic?.(c.name);}catch(e){if(current===epoch.current){setToken('');setClinic(null);setError(e instanceof Error?e.message:'Không thể đăng nhập tổng quan.');}}finally{if(current===epoch.current)setBusy(false);}}
 async function reload(){if(busy||!clinic)return;const current=++epoch.current;setBusy(true);setRows(null);setError('');try{const source=await directory(token,clinic.id);if(current!==epoch.current)return;setClinic(source);const chosen=source.branches.filter(b=>branch==='ALL'||b.id===branch);if(chosen.length===0)throw new Error('Địa điểm vận hành không còn trong phạm vi được cấp quyền.');const list=await Promise.all(chosen.map(async b=>{const scope:Scope={token,clinic:source.id,branch:b.id};const [e,f]=await Promise.allSettled([api.encounters(scope,date),api.billing(scope,date)]);return {id:b.id,name:b.name,encounter:e.status==='fulfilled'?e.value:null,billing:f.status==='fulfilled'?f.value:null};}));if(current===epoch.current)setRows(list);}catch(e){if(current===epoch.current)setError(e instanceof Error?e.message:'Không thể tải tổng quan.');}finally{if(current===epoch.current)setBusy(false);}}
 function logout(){epoch.current++;setToken('');setClinic(null);setRows(null);setPassword('');setError('');setBusy(false);onClinic?.('Phòng khám theo phiên đăng nhập');}
 useEffect(()=>{let active=true;if(shared&&token&&clinic)queueMicrotask(()=>{if(active)void reload();});return()=>{active=false;};},[!!shared,token,clinic?.id,branch,date]);
 const complete=rows&&rows.length>0&&rows.every(r=>r.encounter&&r.billing);const sum=(field:keyof api.EncounterSummary)=>rows?.reduce((v,r)=>v+(typeof r.encounter?.[field]==='number'?r.encounter[field] as number:0),0)??0;
 return <section className="booking-panel reception-panel doctor-panel operations-panel"><header className="task-panel-header"><div><span className="eyebrow">Vận hành phòng khám</span><h1>Tổng quan vận hành</h1><p>Theo dõi tiếp nhận, lượt khám và thu phí theo ngày từ dữ liệu của phòng khám.</p></div></header>{busy&&<p role="status">Đang tải dữ liệu nguồn…</p>}{error&&<p role="alert" className="booking-error">{error}</p>}
 {!token&&shared?<SourceSessionState error={error} retry={()=>void login()}/>:!token?<form className="booking-form" onSubmit={e=>{e.preventDefault();void login();}}><label>Email tổng quan<input type="email" required autoComplete="username" disabled={busy} value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Mật khẩu tổng quan<input type="password" required autoComplete="current-password" disabled={busy} value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="booking-primary" disabled={busy}>Đăng nhập tổng quan</button><p>Chủ cơ sở hoặc Quản lý xem tổng quan theo quyền hiện tại.</p></form>:<>{!shared&&<button onClick={logout}>Đăng xuất tổng quan</button>}<div className="dashboard-toolbar"><label>Ngày vận hành<input type="date" aria-label="Ngày vận hành" value={date} disabled={busy} onChange={e=>{epoch.current++;setRows(null);setDate(e.target.value);}}/><DatePreview value={date}/></label><button disabled={busy||!date} onClick={()=>void reload()}>Cập nhật tổng quan</button></div>
 {rows&&!complete&&<p role="alert">Chưa tải đủ dữ liệu nguồn. Tổng hợp toàn phạm vi đang chờ kiểm tra lại.</p>}
 {complete&&<><div className="dashboard-metrics" aria-label="Tổng quan trong ngày">{[
 ['Đã tiếp nhận',sum('checkedIn'),'bệnh nhân trong ngày',UsersRound],
 ['Hoàn tất khám',sum('completed'),'lượt trong ngày',ClipboardCheck],
 ['Đang chờ khám',sum('waitingTickets'),'người trong hàng đợi',Stethoscope],
 ['Tiền đã nhận',money(rows.reduce((v,r)=>v+r.billing!.collectedCashVnd+r.billing!.collectedBankVnd+r.billing!.collectedPosVnd+(r.billing!.collectedOnlineVnd??0),0)),'trong ngày đã chọn',Wallet]
 ].map(([label,value,hint,Icon])=>{const Symbol=Icon as typeof Wallet;return <article className="dashboard-metric" key={String(label)}><Symbol size={22} aria-hidden="true"/><span>{String(label)}</span><strong>{String(value)}</strong><small>{String(hint)}</small></article>;})}</div></>}
 <div className="dashboard-columns">{rows?.map(r=><div className="dashboard-source" key={r.id}><article className="dashboard-card"><h2>Hoạt động khám</h2>{r.encounter?<><CareFlowChart summary={r.encounter}/><dl className="dashboard-facts"><div><dt>Lượt khám chưa đóng</dt><dd>{r.encounter.openVisits}</dd></div><div><dt>Lượt giữ qua ngày</dt><dd>{r.encounter.overnight}</dd></div><div><dt>Tiếp nhận chờ xác nhận</dt><dd>{r.encounter.arrivalPending}</dd></div></dl><small>Cập nhật {new Date(r.encounter.measuredAt).toLocaleTimeString('vi-VN')}</small></>:<p role="status">Nguồn lượt khám chưa tải được.</p>}</article><article className="dashboard-card"><h2>Thu phí trong ngày</h2>{r.billing?<><dl className="dashboard-facts">{[['Tiền mặt',r.billing.collectedCashVnd],['Chuyển khoản tại quầy',r.billing.collectedBankVnd],['Thẻ tại quầy',r.billing.collectedPosVnd],['Thanh toán online',r.billing.collectedOnlineVnd??0],['Khoản còn phải thu hiện tại',r.billing.outstandingVnd]].map(([label,n])=><div key={String(label)}><dt>{label}</dt><dd>{money(Number(n))}</dd></div>)}</dl><div className="dashboard-attention"><strong>Cần theo dõi</strong><p>{r.billing.submittedShifts} ca chờ duyệt · {r.billing.paymentReviews??0} giao dịch cần đối chiếu</p><span>{r.billing.openShifts} ca đang thu</span></div>{!!r.billing.collectedSandboxVnd&&<small>Thanh toán thử nghiệm: {money(r.billing.collectedSandboxVnd)}. Không cộng vào thực thu.</small>}</>:<p role="status">Nguồn thu phí chưa tải được.</p>}</article></div>)}</div>
 </>}
 </section>;
}

