import {RealtimeIndicator,useReceptionRealtime} from './useReceptionRealtime';
import type {SyncContext} from './useAuthoritativeSync';
import {ReceptionAppointmentChange} from './ReceptionAppointmentChange';
import {ReceptionExceptionCenter} from './ReceptionExceptionCenter';
import {WorklistTools} from './WorklistTools';
import {stateName,dateLabel} from '../utils/display';
import {PatientIdentity} from './PatientIdentity';
import {formatVnd} from '../utils/vnd';
import {specialtyDisplay} from '../utils/specialty';
import {usePanelSession,useSessionBranch} from '../auth/SessionProvider';
import {SourceSessionState} from '../auth/SourceSessionState';
import { useEffect, useRef, useState } from 'react';
import * as api from '../api/reception';
import { signIn, RequestError } from '../api/booking';
import { stableOperationKey, forgetOperationKey } from '../api/idempotency';
import { AbsenceLifecyclePanel } from './AbsenceLifecyclePanel';
import { SupervisorArrivalPanel } from './SupervisorArrivalPanel';
import { OvernightQueuePanel } from './OvernightQueuePanel';
import type { IamContextView } from '../types/contracts';
import { useNavigationLock } from './useNavigationLock';
const queueStates:Record<string,string>={WAITING:'Chờ gọi',CALLED:'Đã gọi',SERVING:'Đang khám',DONE:'Đã phục vụ',SKIPPED:'Tạm bỏ qua',ABSENT:'Vắng',TRANSFERRED:'Đã chuyển phòng'};
const matches=(query:string,...values:(string|null|undefined)[])=>values.join(' ').toLocaleLowerCase('vi-VN').includes(query.trim().toLocaleLowerCase('vi-VN'));
const clockTime=(value:string)=>new Intl.DateTimeFormat('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',timeStyle:'short'}).format(new Date(value));
const visitStatus:Record<string,string>={ARRIVAL_PENDING:'Đang chờ xác nhận',WAITING:'Chờ khám',IN_PROGRESS:'Đang khám',AWAITING_RESULTS:'Chờ kết quả',CLINICALLY_COMPLETED:'Hoàn tất chuyên môn',CLOSED:'Đã đóng',CANCELLED:'Đã hủy',INTERRUPTED:'Gián đoạn'};
const localDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export function ReceptionPanel({onClinic,onNavigationLock}:{onClinic?:(name:string)=>void;onNavigationLock?:(reason:string|null)=>void}){
 const [arrivalMode,setArrivalMode]=useState('appointment');
 const [specialty,setSpecialty]=useState(''),[queuePoint,setQueuePoint]=useState(''),[sourceExceptions,setSourceExceptions]=useState<api.Exception[]>([]),[requestRows,setRequestRows]=useState<api.ReceptionRequest[]>([]),[exceptionDraft,setExceptionDraft]=useState<api.RequestInput|null>(null),[precheckPending,setPrecheckPending]=useState(false),[exceptionPending,setExceptionPending]=useState(false),[appointmentVerified,setAppointmentVerified]=useState(false),[now,setNow]=useState(Date.now());
 useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),30000);return()=>window.clearInterval(timer);},[]);
 const [deskTab,setDeskTab]=useState('intake'),[recoveryQuery,setRecoveryQuery]=useState(''),[recoveryFilter,setRecoveryFilter]=useState('');
 const shared=usePanelSession(()=>run(login));
 const [token,setToken]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState('');
 const [directory,setDirectory]=useState<api.Directory|null>(null),[branch,setBranch]=useState('');
 const [doctors,setDoctors]=useState<api.Doctor[]>([]),[doctor,setDoctor]=useState('');
 const [offerings,setOfferings]=useState<api.ReceptionOffering[]>([]),[offering,setOffering]=useState(''),[offeringPrice,setOfferingPrice]=useState<number|null>(null);
 const [points,setPoints]=useState<api.Point[]>([]),[point,setPoint]=useState(''),[destination,setDestination]=useState('');
 const [patients,setPatients]=useState<api.Patient[]>([]),[patient,setPatient]=useState<api.Patient|null>(null);
 const [name,setName]=useState(''),[dob,setDob]=useState(''),[createName,setCreateName]=useState(''),[createDob,setCreateDob]=useState(''),[createPhone,setCreatePhone]=useState(''),[createPatientOpen,setCreatePatientOpen]=useState(false),[patientSearchBusy,setPatientSearchBusy]=useState(false),[patientSearchDone,setPatientSearchDone]=useState(false),[patientSearchError,setPatientSearchError]=useState(''),[reason,setReason]=useState(''),[evidence,setEvidence]=useState('');
 const [date,setDate]=useState(localDate),[appointments,setAppointments]=useState<api.Appointment[]>([]),[appointment,setAppointment]=useState<api.Appointment|null>(null);
 const [,setNextQueue]=useState<number|null>(null);
 const detailHeading=useRef<HTMLHeadingElement>(null);
 const [listQuery,setListQuery]=useState(''),[queueFilter,setQueueFilter]=useState(''),[queueDoctor,setQueueDoctor]=useState(''),[syncError,setSyncError]=useState(''),[lastSync,setLastSync]=useState('');
 const [checkRecovery,setCheckRecovery]=useState(false);
 const checkAttempt=useRef<{scope:api.Scope;appointment:api.Appointment;point:string;reason:string;key:string}|null>(null);
 const [tickets,setTickets]=useState<api.Ticket[]|null>(null),[visit,setVisit]=useState<api.Visit|null>(null);
 const [recoveries,setRecoveries]=useState<api.ArrivalRecovery[]>([]);const newIntent=useRef('');
 const [exceptions,setExceptions]=useState<api.Exception[]>([]),[exceptionType,setExceptionType]=useState('LATE');
 const [absences,setAbsences]=useState<api.Absence[]>([]),[absenceStart,setAbsenceStart]=useState(''),[absenceEnd,setAbsenceEnd]=useState('');
 const [absenceRecovery,setAbsenceRecovery]=useState(false);const absenceAttempt=useRef<{scope:api.Scope;doctor:string;body:{startsAt:string;endsAt:string;reason:string};key:string}|null>(null);
 const [queuePending,setQueuePending]=useState(false),[queueActionRecovery,setQueueActionRecovery]=useState(false);
 const queueAttempt=useRef<{scope:api.Scope;ticket:api.Ticket;action:'call'|'skip'|'transfer'|'recall'|'absent'|'requeue';reason:string;destination?:string}|null>(null);
 const [supervisorPending,setSupervisorPending]=useState(false);
 const [lifecyclePending,setLifecyclePending]=useState(false),[memberships,setMemberships]=useState<IamContextView[]>([]);
 const [pointCode,setPointCode]=useState(''),[pointName,setPointName]=useState('');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');const running=useRef(false);
 const [walkRecovery,setWalkRecovery]=useState(false);
 const navigationPending=checkRecovery||walkRecovery||absenceRecovery||lifecyclePending||supervisorPending||queuePending||queueActionRecovery||precheckPending||exceptionPending;
 useNavigationLock(navigationPending?'Xác minh hoặc thử lại thao tác tiếp nhận đang chờ trước khi rời màn hình.':busy?'Đợi thao tác tiếp nhận xử lý xong trước khi rời màn hình.':null,onNavigationLock);
 const walkAttempt=useRef<{scope:api.Scope;payload:{clinic:string;branch:string;actorEmail:string;patientId:string;doctorId:string;offeringId:string;servicePointId:string;reason:string;intent:string};key:string}|null>(null);
 const scope:api.Scope={token,clinic:directory?.id??'',branch};
 async function run(action:()=>Promise<void>){if(running.current)return;running.current=true;setBusy(true);setError('');setMessage('');try{await action();}catch(e){setError(e instanceof Error?e.message:'Chưa xác định được kết quả. Thử lại cùng yêu cầu.');if(e instanceof RequestError&&e.status===409){try{await loadDay(date);}catch{/* Preserve the operation error. */}}}finally{running.current=false;setBusy(false);}}
 async function login(){const auth=shared?.session?.token??(await signIn(email,password)).data.accessToken;setEmail(shared?.session?.email??email);setPassword('');const memberships=await api.contexts(auth);setMemberships(memberships);const clinicIds=[...new Set(memberships.filter(m=>['ADMIN','STAFF'].includes(m.role)).map(m=>m.clinicId))];const requested=new URLSearchParams(location.search).get('clinicId');const id=requested?(clinicIds.includes(requested)?requested:null):clinicIds.length===1?clinicIds[0]:null;if(!id)throw new Error('Phiên này chưa xác định một phòng khám cho Workspace. Mở đường dẫn Workspace được cấp cho phòng khám của bạn.');const d=await api.directory(auth,id);setToken(auth);setDirectory(d);onClinic?.(d.name);setBranch('');setPatient(null);setPatients([]);setAppointments([]);setAppointment(null);setExceptions([]);setVisit(null);setTickets(null);setNextQueue(null);}
 useSessionBranch(shared,token,directory,branch,id=>run(()=>chooseBranch(id)));
 async function readAllQueue(s:api.Scope,_selectedPoint:string,selectedDate:string){
  const allPoints=await api.points(s);const pages=await Promise.all(allPoints.filter(p=>p.active).map(async p=>{const items:api.Ticket[]=[];let after=0;do{const page=await api.queuePage(s,p.id,selectedDate,after);items.push(...page.items);after=page.nextAfterNumber??0;}while(after>0);return items;}));
  return pages.flat().sort((a,b)=>(a.issuedAt??a.checkedInAt??'').localeCompare(b.issuedAt??b.checkedInAt??'')||a.number-b.number||a.code.localeCompare(b.code));
 }
 async function chooseBranch(id:string){walkAttempt.current=null;setRecoveries([]);setBranch(id);setAbsences([]);setPatient(null);setPatients([]);setVisit(null);setAppointments([]);setAppointment(null);setExceptions([]);setTickets(null);setNextQueue(null);setPoint('');setDoctor('');setDoctors([]);setPoints([]);setOfferings([]);setOffering('');setSpecialty('');setQueuePoint('');setRequestRows([]);setOfferingPrice(null);if(!id)return;const s={...scope,branch:id};const [d,p,a,o,bookings]=await Promise.all([api.doctors(s),api.points(s),api.workload(s,date),api.offerings(s).catch(e=>{setError(e instanceof Error?e.message:'Bảng giá chưa đồng bộ được.');return [] as api.ReceptionOffering[];}),api.appointments(s,date).catch(e=>{setError(e instanceof Error?e.message:'Lịch hẹn trong ngày chưa đồng bộ được.');return [] as api.Appointment[];})]);setOfferings(o.filter(x=>x.active&&x.offering.active));setRecoveries(a);setAppointments(bookings);setRequestRows(await api.requests(s));setSourceExceptions(await api.openExceptions(s));const today=localDate();setDoctors(d.filter(x=>x.active&&x.effectiveFrom<=today&&(!x.effectiveUntil||today<x.effectiveUntil)));setPoints(p);const firstPoint=p[0];if(firstPoint){setPoint(firstPoint.id);try{const items=await readAllQueue(s,firstPoint.id,date);setTickets(items);setNextQueue(null);}catch(e){setError(e instanceof Error?e.message:'Hàng đợi chưa đồng bộ được.');}}}
 async function reloadQueue(_afterNumber=0,selectedPoint=point){if(!selectedPoint)return;setTickets(null);setNextQueue(null);setTickets(await readAllQueue(scope,selectedPoint,date));}
 async function loadDay(nextDate:string){const [bookings,arrivals,queue]=await Promise.allSettled([api.appointments(scope,nextDate),api.workload(scope,nextDate),point?readAllQueue(scope,point,nextDate):Promise.resolve(null)]);if(bookings.status==='fulfilled')setAppointments(bookings.value);else setError('Lịch hẹn trong ngày đã chọn chưa đồng bộ được.');if(arrivals.status==='fulfilled')setRecoveries(arrivals.value);else setError('Lịch sử tiếp nhận trong ngày chưa đồng bộ được.');if(queue.status==='fulfilled'&&queue.value){setTickets(queue.value);setNextQueue(null);}else if(queue.status==='rejected'){setTickets(null);setError('Hàng đợi trong ngày đã chọn chưa đồng bộ được.');}}
 async function moveTicket(ticket:api.Ticket,action:'call'|'skip'|'transfer'|'recall'|'absent'|'requeue'){
  if(!queueAttempt.current)queueAttempt.current={scope:{...scope},ticket,action,reason:action==='call'||action==='recall'?(reason.trim()||'Gọi bệnh nhân vào phòng khám'):reason,destination:action==='transfer'?destination:undefined};
  const original=queueAttempt.current;setQueueActionRecovery(true);
  try{await api.move(original.scope,original.ticket,original.action,original.reason,original.destination);}
  catch(e){if(e instanceof RequestError&&e.status>=400&&e.status<500){queueAttempt.current=null;setQueueActionRecovery(false);}throw e;}
  queueAttempt.current=null;setQueueActionRecovery(false);setMessage(`Đã ghi nhận thao tác hàng đợi cho ${original.ticket.code}.`);
  setVisit(null);setVisit(await api.readVisit(original.scope,original.ticket.visitId));await reloadQueue();
 }
 async function reportDoctorAbsence(){
  if(!absenceAttempt.current){const body={startsAt:new Date(absenceStart+':00+07:00').toISOString(),endsAt:new Date(absenceEnd+':00+07:00').toISOString(),reason};absenceAttempt.current={scope:{...scope},doctor,body,key:await stableOperationKey('doctor-absence',{clinic:scope.clinic,branch,actorEmail:email,doctor,...body})};}
  const attempt=absenceAttempt.current;setAbsenceRecovery(true);
  try{const result=await api.reportAbsence(attempt.scope,attempt.doctor,attempt.body,attempt.key);setAbsenceRecovery(false);absenceAttempt.current=null;setAbsences(old=>[result,...old.filter(a=>a.id!==result.id)]);setMessage('Đã ghi khoảng vắng và chặn đặt mới. Tiếp tục ghi ngoại lệ cho các lịch bị ảnh hưởng.');}catch(e){if(e instanceof RequestError&&e.status>=400&&e.status<500){setAbsenceRecovery(false);absenceAttempt.current=null;}throw e;}
 }
 async function arriveWalkIn(){
  if(!walkAttempt.current){if(!patient)return;const payload={clinic:scope.clinic,branch,actorEmail:email,patientId:patient.patientId,doctorId:'',offeringId:offering,servicePointId:point,reason,intent:newIntent.current};walkAttempt.current={scope:{...scope},payload,key:await stableOperationKey('walk-in',payload)};}
  const attempt=walkAttempt.current;setWalkRecovery(true);
  let confirmed:api.Visit;
  try{const p=attempt.payload;confirmed=await api.walkIn(attempt.scope,p.patientId,p.doctorId,p.servicePointId,p.reason,attempt.key,p.offeringId);}
  catch(e){if(e instanceof RequestError&&e.status>=400&&e.status<500){setWalkRecovery(false);walkAttempt.current=null;}throw e;}
  setWalkRecovery(false);setVisit(confirmed);setMessage('Đã tiếp nhận khách đến trực tiếp · '+confirmed.ticket?.code);const items=await readAllQueue(attempt.scope,attempt.payload.servicePointId,date);setTickets(items);setNextQueue(null);
 }
 async function newWalkIn(){if(!visit||walkRecovery)return;if(walkAttempt.current)await forgetOperationKey('walk-in',walkAttempt.current.payload);walkAttempt.current=null;newIntent.current=crypto.randomUUID();setVisit(null);setPatient(null);setPatients([]);setName('');setDob('');setCreateName('');setCreateDob('');setCreatePhone('');setCreatePatientOpen(false);setReason('');setEvidence('');setMessage('Đối chiếu hồ sơ cho lượt tiếp nhận mới.');}

 function choosePatient(p:api.Patient){setPatient(p);setAppointment(null);setVisit(null);setEvidence('');setReason('Tiếp nhận khách đến trực tiếp tại quầy');walkAttempt.current=null;newIntent.current=crypto.randomUUID();}
 async function checkArrival(){
  if(!checkAttempt.current){if(!appointment?.patient||!point)return;checkAttempt.current={scope:{...scope},appointment,point,reason,key:await stableOperationKey('check-in',{clinic:scope.clinic,branch,actorEmail:email,appointmentId:appointment.id,patientId:appointment.patientId,servicePointId:point,reason})};}
  const attempt=checkAttempt.current;setCheckRecovery(true);
  let confirmed:api.Visit;
  try{confirmed=await api.checkIn(attempt.scope,attempt.appointment,attempt.appointment.patientId,attempt.point,attempt.reason,attempt.key);}catch(e){if(e instanceof RequestError&&e.status>=400&&e.status<500){setCheckRecovery(false);checkAttempt.current=null;}throw e;}
  setCheckRecovery(false);setVisit(confirmed);setMessage('Đã ghi nhận tiếp nhận lịch · '+(confirmed.ticket?.code??'Đang chờ xác nhận'));
  await loadDay(date);
  setRecoveries(current=>[{operation:'check-in',createdAt:new Date().toISOString(),visit:confirmed},...current.filter(x=>x.visit.id!==confirmed.id)]);
 }
 useEffect(()=>{detailHeading.current?.focus();},[patient?.patientId,appointment?.id]);
 const canManage=memberships.some(m=>m.clinicId===scope.clinic&&m.role==='ADMIN'&&(m.allBranches||m.branchIds.includes(branch)));
 const validScope=!!token&&!!directory&&!!branch;
 const appointmentAlreadyReceived=(a:api.Appointment)=>a.status==='CHECKED_IN'||recoveries.some(x=>x.visit.appointmentId===a.id);
 const pointQueue=(tickets??[]).filter(t=>!queuePoint||t.servicePointId===queuePoint);
 const visibleQueue=pointQueue.filter(t=>['WAITING','CALLED','SERVING','SKIPPED','ABSENT'].includes(t.state)&&(!queueFilter||t.state===queueFilter)&&(!queueDoctor||t.doctorId===queueDoctor)&&matches(listQuery,t.code,t.patient?.fullName,t.patient?.patientCode));
 const exceptionCount=sourceExceptions.length+requestRows.length+recoveries.filter(a=>a.visit.status==='ARRIVAL_PENDING').length+(tickets??[]).filter(t=>['SKIPPED','ABSENT'].includes(t.state)).length;
 const specialties=[...new Map(doctors.filter(d=>d.specialtyCode).map(d=>[d.specialtyCode!,specialtyDisplay(d.specialtyCode,d.specialtyName)])).entries()];
 const activeQueueTickets=pointQueue.filter(t=>['CALLED','SERVING'].includes(t.state));
 const activeForDoctor=(t:api.Ticket)=>activeQueueTickets.find(x=>x.doctorId===t.doctorId);
 const firstWaitingForDoctor=(t:api.Ticket)=>pointQueue.filter(x=>x.doctorId===t.doctorId&&x.state==='WAITING').sort((a,b)=>a.number-b.number)[0];
 const canCallTicket=(t:api.Ticket)=>!busy&&!navigationPending&&t.state==='WAITING'&&!activeForDoctor(t)&&firstWaitingForDoctor(t)?.id===t.id;
 const callTicketHint=(t:api.Ticket)=>{const active=activeForDoctor(t),first=firstWaitingForDoctor(t);return t.state==='CALLED'?'Lượt này đã được gọi và đang chờ vào phòng.':t.state==='SKIPPED'?'Lượt này đã được bỏ qua.':active?`${active.code} của cùng bác sĩ đang ${active.state==='SERVING'?'được khám':'chờ vào phòng'}; chưa thể gọi lượt tiếp theo của bác sĩ này.`:first&&first.id!==t.id?`Phải xử lý ${first.code} trước trong hàng đợi của bác sĩ này.`:'Gọi lượt chờ tiếp theo của bác sĩ này.';};
 useEffect(()=>{const query=name.trim();const digits=query.replace(/\D/g,'');const phoneQuery=digits.length>=6&&/^[+\d\s().-]+$/.test(query);const canSearch=!!query&&(phoneQuery||!!dob);if(!validScope||deskTab!=='intake')return;let active=true;setPatientSearchError('');if(!query&&!dob){setPatientSearchBusy(true);setPatientSearchDone(false);void api.recentPatients(scope).then(rows=>{if(active)setPatients(rows);}).catch(e=>{if(active)setPatientSearchError(e instanceof Error?e.message:'Chưa tải được hồ sơ bệnh nhân gần đây.');}).finally(()=>{if(active)setPatientSearchBusy(false);});return()=>{active=false;};}if(!canSearch){setPatients([]);setPatientSearchBusy(false);setPatientSearchDone(false);return()=>{active=false;};}const timer=window.setTimeout(()=>{setPatientSearchBusy(true);setPatientSearchError('');void api.suggestions(scope,phoneQuery?'':query,phoneQuery?'':dob,phoneQuery?query:'').then(rows=>{if(active){setPatients(rows);setPatientSearchDone(true);}}).catch(e=>{if(active){setPatients([]);setPatientSearchError(e instanceof Error?e.message:'Chưa tìm được hồ sơ bệnh nhân.');}}).finally(()=>{if(active)setPatientSearchBusy(false);});},300);return()=>{active=false;window.clearTimeout(timer);};},[validScope,deskTab,name,dob,scope.token,scope.clinic,scope.branch]);
 useEffect(()=>{if(!appointment||!validScope)return;let active=true;void api.exceptions(scope,appointment).then(rows=>{if(active)setExceptions(rows);}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Chưa đồng bộ được ngoại lệ lịch hẹn.');});return()=>{active=false;};},[appointment?.id,scope.token,scope.clinic,scope.branch,validScope]);
 useEffect(()=>{if(deskTab!=='operations'||!doctor||!validScope)return;let active=true;void api.doctorAbsences(scope,doctor).then(rows=>{if(active)setAbsences(rows);}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Chưa đồng bộ được khoảng vắng của bác sĩ.');});return()=>{active=false;};},[deskTab,doctor,scope.token,scope.clinic,scope.branch,validScope]);

 const refreshGeneration=useRef(0),refreshScope=useRef('');refreshScope.current=[token,directory?.id,branch,date,point].join(':');
 async function refreshReception(context?:SyncContext){
  const original=refreshScope.current,generation=refreshGeneration.current;
  try{const [bookings,arrivals,queue,requests,sourceExceptions]=await Promise.all([api.appointments(scope,date),api.workload(scope,date),readAllQueue(scope,point,date),api.requests(scope),api.openExceptions(scope)]);
   if(original===refreshScope.current&&generation===refreshGeneration.current&&!running.current&&(!context||context.current())){setAppointments(bookings);setRecoveries(arrivals);setTickets(queue);setRequestRows(requests);setSourceExceptions(sourceExceptions);setSyncError('');setLastSync(clockTime(new Date().toISOString()));}
  }catch(e){if(original!==refreshScope.current)return;if(e instanceof RequestError&&[401,403].includes(e.status)){setAppointments([]);setRecoveries([]);setTickets(null);setRequestRows([]);setAppointment(null);setPatient(null);}setSyncError(e instanceof Error?e.message:'Chưa đồng bộ được. Dữ liệu có thể đã cũ.');throw e;}
 }
 const realtime=useReceptionRealtime(scope,refreshReception,busy||navigationPending,['encounter','appointment'],()=>{refreshGeneration.current++;setAppointments([]);setRecoveries([]);setTickets(null);setRequestRows([]);setSourceExceptions([]);setAppointment(null);setPatient(null);setSyncError('Quyền truy cập đã thay đổi. Xác minh lại phiên đăng nhập.');});
 useEffect(()=>{if(validScope&&!busy&&!navigationPending)void refreshReception().catch(()=>{});},[date]);
 function requestException(ticket:api.Ticket){setExceptionDraft({visitId:ticket.visitId,type:'DOCTOR_CHANGE',reason:'Bệnh nhân yêu cầu đổi bác sĩ sau khi đã vào hàng đợi'});setDeskTab('operations');}
 return <section className="booking-panel reception-panel front-desk"><header className="task-panel-header"><div><span className="eyebrow">Tiếp nhận tại phòng khám</span><h1>Quầy tiếp nhận</h1><p>Tiếp nhận chung cho toàn phòng khám. Cấp số trước khám; thu tiền sau khi hoàn tất chuyên môn.</p></div></header>
 {!token&&shared?<SourceSessionState error={error} retry={()=>void run(login)}/>:!token?<form className="booking-form" onSubmit={e=>{e.preventDefault();void run(login);}}><label>Email nhân viên<input type="email" required autoComplete="username" disabled={busy} value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Mật khẩu nhân viên<input type="password" required autoComplete="current-password" disabled={busy} value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="booking-primary" disabled={busy}>Đăng nhập tiếp nhận</button></form>:<><div hidden={!!shared&&directory?.branches.length===1}><p>Phòng khám: <strong>{directory?.name}</strong></p><label>Địa điểm tiếp nhận<select aria-label="Địa điểm tiếp nhận" disabled={busy||navigationPending} value={branch} onChange={e=>void run(()=>chooseBranch(e.target.value))}><option value="">Chọn địa điểm</option>{directory?.branches.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></label></div>{!shared&&<button className="button-secondary" disabled={busy||navigationPending} onClick={()=>{setToken('');setMemberships([]);setLifecyclePending(false);setSupervisorPending(false);setQueuePending(false);setDirectory(null);setRecoveries([]);setWalkRecovery(false);setAbsenceRecovery(false);absenceAttempt.current=null;setAbsences([]);setPatient(null);setPatients([]);setTickets(null);setNextQueue(null);setAppointments([]);setAppointment(null);setExceptions([]);setVisit(null);walkAttempt.current=null;onClinic?.('Phòng khám theo phiên đăng nhập');}}>Đăng xuất tiếp nhận</button>}</>}
 {visit&&<p role="status">Lượt tiếp nhận: {visitStatus[visit.status]??visit.status} · {visit.ticket?.code??'Đang chờ xác nhận lượt đến'}</p>}
 <div aria-live="polite">{busy&&<p role="status">Đang xử lý…</p>}{error&&<p role="alert" className="booking-error">{error}</p>}{message&&<p role="status">{message}</p>}</div>
 {walkRecovery&&<div className="booking-confirm"><p>Chưa xác định được kết quả tiếp nhận. Giữ nguyên bệnh nhân, bác sĩ, điểm phục vụ và lý do cho đến khi xác nhận lượt này.</p><button className="booking-primary" disabled={busy} onClick={()=>void run(arriveWalkIn)}>Thử lại lượt tiếp nhận đang chờ</button></div>}
 {queueActionRecovery&&queueAttempt.current&&<div className="booking-confirm" role="status"><p>Chưa xác định kết quả thao tác hàng đợi. Giữ nguyên lượt và lý do; thử lại cùng yêu cầu để tránh tác động hai lần.</p><button className="booking-primary" disabled={busy} onClick={()=>void run(()=>moveTicket(queueAttempt.current!.ticket,queueAttempt.current!.action))}>Thử lại thao tác hàng đợi đang chờ</button></div>}
 {absenceRecovery&&<div className="booking-confirm"><p>Chưa xác định được kết quả báo vắng. Thử lại cùng bác sĩ, khoảng thời gian và lý do đã gửi.</p><button className="booking-primary" disabled={busy} onClick={()=>void run(reportDoctorAbsence)}>Thử lại báo vắng đang chờ</button></div>}

 {checkRecovery&&<div className="booking-confirm" role="status"><p>Chưa xác định kết quả tiếp nhận lịch. Thử lại cùng yêu cầu để tránh cấp số trùng.</p><button className="booking-primary" disabled={busy} onClick={()=>void run(checkArrival)}>Thử lại tiếp nhận lịch đang chờ</button></div>}
 {validScope&&<>
 <div className="desk-overview" aria-label="Công việc đang chờ"><button type="button" disabled={busy||navigationPending} onClick={()=>setDeskTab('intake')}><span>Chờ tiếp nhận</span><strong>{appointments.filter(a=>a.status==='CONFIRMED'&&!appointmentAlreadyReceived(a)).length}</strong></button><button type="button" disabled={busy||navigationPending} onClick={()=>{setDeskTab('queue');setQueueFilter('WAITING');}}><span>Đang chờ khám</span><strong>{tickets?.filter(t=>t.state==='WAITING').length??'—'}</strong></button><button type="button" disabled={busy||navigationPending} onClick={()=>{setDeskTab('queue');setQueueFilter('CALLED');}}><span>Đã gọi / chưa vào</span><strong>{tickets?.filter(t=>t.state==='CALLED').length??'—'}</strong></button><button type="button" disabled={busy||navigationPending} onClick={()=>setDeskTab('operations')}><span>Cần xử lý</span><strong>{exceptionCount}</strong></button></div>
 <nav className="task-tabs" aria-label="Công việc tiếp nhận">{[['intake','Tiếp nhận'],['queue','Hàng đợi'],['operations','Ngoại lệ'],['recovery','Lịch sử']].map(([id,label])=><button type="button" key={id} className={id==='recovery'?'reception-history-link':''} disabled={busy||navigationPending} aria-pressed={deskTab===id} onClick={()=>{setDeskTab(id);setListQuery('');setQueueFilter('');setExceptionDraft(null);}}>{label}</button>)}</nav>
 <div className="desk-daybar"><label>Ngày làm việc<input type="date" required disabled={busy||navigationPending} value={date} onChange={e=>{const next=e.target.value;if(!next)return;setDate(next);setTickets(null);setRecoveries([]);setAppointment(null);setPatient(null);setVisit(null);setExceptions([]);setAppointments([]);void run(()=>loadDay(next));}}/></label><div className="desk-sync"><RealtimeIndicator state={realtime}/>{syncError&&<p role="alert">{syncError} <button type="button" className="button-secondary" disabled={busy||navigationPending} onClick={()=>void run(refreshReception)}>Đồng bộ lại</button></p>}{lastSync&&<small>Đã cập nhật {lastSync}</small>}</div></div>
 {deskTab==='intake'&&<fieldset className="desk-workspace" disabled={busy||navigationPending&&!precheckPending}>
 <section className="desk-list">
 <div className="desk-list-heading"><div><h2>{arrivalMode==='appointment'?'Lịch hẹn trong ngày':'Hồ sơ bệnh nhân'}</h2><p>{arrivalMode==='appointment'?'Chọn lịch hẹn để đối chiếu và cấp số tại quầy.':'20 hồ sơ gần đây. Tra cứu chính xác hoặc tạo hồ sơ cho khách mới.'}</p></div></div>
 <div className="desk-mode" aria-label="Hình thức tiếp nhận">{[['appointment','Đã đặt lịch'],['walk-in','Khách đến trực tiếp']].map(([id,label])=><button key={id} type="button" aria-pressed={arrivalMode===id} onClick={()=>{setArrivalMode(id);setPatient(null);setAppointment(null);setVisit(null);setCreatePatientOpen(false);setListQuery('');walkAttempt.current=null;newIntent.current=crypto.randomUUID();}}>{label}</button>)}</div>
 {arrivalMode==='appointment'?<>
 <label className="desk-search">Tìm lịch hẹn<input type="search" placeholder="Tên, mã bệnh nhân, mã lịch hoặc ngày sinh…" value={listQuery} onChange={e=>setListQuery(e.target.value)}/></label>
 <div className="desk-table-scroll"><table className="desk-table"><caption className="sr-only">Lịch hẹn trong ngày</caption><thead><tr><th>Giờ khám</th><th>Bệnh nhân</th><th>Trạng thái</th><th>Tiếp nhận</th></tr></thead><tbody>{appointments.filter(a=>matches(listQuery,a.patient?.fullName,a.patient?.patientCode,a.appointmentCode,dateLabel(a.patient?.dateOfBirth),a.patient?.dateOfBirth)).map(a=><tr key={a.id} data-selected={appointment?.id===a.id}><td>{clockTime(a.startsAt)}</td><td><strong>{a.patient?.fullName??'Chưa có thông tin nhận diện'}</strong><small>{a.appointmentCode} · {dateLabel(a.patient?.dateOfBirth)}</small></td><td><span className="task-status" data-state={a.status}>{stateName(a.status)}</span></td><td><button type="button" className="button-secondary" disabled={appointmentAlreadyReceived(a)||a.status!=='CONFIRMED'||!a.patient} onClick={()=>{setAppointmentVerified(false);setAppointment(a);setPatient(null);setVisit(null);setExceptions([]);setReason('Tiếp nhận lịch hẹn tại quầy');checkAttempt.current=null;}}>{appointmentAlreadyReceived(a)?'Đã tiếp nhận':'Chọn lịch'}</button></td></tr>)}{!appointments.filter(a=>matches(listQuery,a.patient?.fullName,a.patient?.patientCode,a.appointmentCode,dateLabel(a.patient?.dateOfBirth),a.patient?.dateOfBirth)).length&&<tr><td colSpan={4} className="desk-empty">Không có lịch hẹn phù hợp trong ngày này.</td></tr>}</tbody></table></div>
 </>:<>
 <div className="desk-patient-search"><label>Tên hoặc số điện thoại<input type="search" aria-label="Tên hoặc số điện thoại bệnh nhân" placeholder="Tên chính xác hoặc số điện thoại" value={name} onChange={e=>setName(e.target.value)}/></label><label>Ngày sinh (khi tra theo tên)<input aria-label="Ngày sinh tra cứu" type="date" value={dob} onChange={e=>setDob(e.target.value)}/></label><button type="button" className="button-secondary" onClick={()=>{setCreatePatientOpen(v=>!v);setReason('Tạo hồ sơ khách đến trực tiếp tại quầy');}}>{createPatientOpen?'Đóng biểu mẫu':'Tạo hồ sơ mới'}</button></div>
 {patientSearchError&&<p role="alert" className="booking-error">{patientSearchError}</p>}
 {name.trim()&&!dob&&!/^[+\d\s().-]{6,}$/.test(name.trim())&&<p role="status">Nhập thêm ngày sinh để tra cứu chính xác theo tên.</p>}
 {createPatientOpen&&<form className="desk-create" onSubmit={e=>{e.preventDefault();void run(async()=>{const input={fullName:createName.trim(),dateOfBirth:createDob||null,phone:createPhone.trim()||null,reason:'Tạo hồ sơ khách đến trực tiếp tại quầy'};const key=await stableOperationKey('provisional',{clinic:scope.clinic,branch,actorEmail:email,...input});const p=await api.provisional(scope,input,key);choosePatient(p);setPatients(current=>[p,...current.filter(x=>x.patientId!==p.patientId)]);setCreatePatientOpen(false);setCreateName('');setCreateDob('');setCreatePhone('');setMessage('Đã tạo hồ sơ. Đối chiếu thông tin trước khi tiếp nhận.');});}}><h3>Hồ sơ mới tại quầy</h3><label>Họ tên bệnh nhân<input required maxLength={180} value={createName} onChange={e=>setCreateName(e.target.value)}/></label><label>Ngày sinh<input type="date" max={localDate()} value={createDob} onChange={e=>setCreateDob(e.target.value)}/></label><label>Số điện thoại<input type="tel" maxLength={30} value={createPhone} onChange={e=>setCreatePhone(e.target.value)}/></label><button className="booking-primary" disabled={!createName.trim()}>Tạo và chọn hồ sơ</button></form>}
 <div className="desk-table-scroll"><table className="desk-table" aria-busy={patientSearchBusy}><caption className="sr-only">Hồ sơ bệnh nhân</caption><thead><tr><th>Bệnh nhân</th><th>Điện thoại</th><th>Hồ sơ</th><th>Thao tác</th></tr></thead><tbody>{patients.map(p=><tr key={p.patientId} data-selected={patient?.patientId===p.patientId}><td><strong>{p.fullName}</strong><small>{dateLabel(p.dateOfBirth)}</small><small className="desk-code">{p.patientCode}</small></td><td>{p.phoneLast4?'•••• '+p.phoneLast4:'Chưa ghi nhận'}</td><td><span className="task-status" data-state={p.status}>{stateName(p.status)}</span></td><td><button className="button-secondary" type="button" onClick={()=>choosePatient(p)}>Chọn hồ sơ</button></td></tr>)}{!patients.length&&<tr><td colSpan={4} className="desk-empty">{patientSearchBusy?'Đang tìm hồ sơ…':patientSearchError?'Chưa đọc được danh sách hồ sơ.':patientSearchDone?'Không tìm thấy hồ sơ phù hợp.':'Chưa có hồ sơ để hiển thị.'}</td></tr>}</tbody></table></div>
 </>}
 </section>
 {(patient||appointment)&&<aside className="desk-detail" aria-label="Xác nhận tiếp nhận"><div className="desk-detail-heading"><h2 ref={detailHeading} tabIndex={-1}>Xác nhận tiếp nhận</h2><button type="button" className="button-secondary" disabled={navigationPending} onClick={()=>{setPatient(null);setAppointment(null);setVisit(null);}}>Đóng</button></div><PatientIdentity patient={arrivalMode==='appointment'?appointment?.patient:patient}/>{appointment&&<p>Lịch {clockTime(appointment.startsAt)} · {appointment.appointmentCode}</p>}
 {visit?<div className="desk-issued" role="status"><span>{visit.ticket?'Đã cấp số':'Đang chờ xác nhận lượt đến'}</span><strong>{visit.ticket?.code??'Chờ xác nhận'}</strong><p>{visitStatus[visit.status]??visit.status}</p><button type="button" className="booking-primary" onClick={()=>setDeskTab('queue')}>Xem hàng đợi</button><button type="button" className="button-secondary" onClick={()=>void run(async()=>{if(!visit.appointmentId)await newWalkIn();setPatient(null);setAppointment(null);setVisit(null);checkAttempt.current=null;})}>Tiếp nhận khách tiếp theo</button></div>:<>
 {appointment&&<ReceptionAppointmentChange key={appointment.id} scope={scope} appointment={appointment} doctors={doctors} offerings={offerings} disabled={busy||checkRecovery} onPending={setPrecheckPending} onReady={setAppointmentVerified} onChanged={async a=>{setAppointment({...a,patient:appointment.patient});setMessage('Đã đổi lựa chọn trước tiếp nhận. Đối chiếu lại trước khi cấp số.');await loadDay(date);}}/>}
 {arrivalMode==='walk-in'&&<><label>Chuyên khoa<select aria-label="Chuyên khoa tiếp nhận" value={specialty} onChange={e=>{setSpecialty(e.target.value);setOffering('');setOfferingPrice(null);}}><option value="">Chọn chuyên khoa</option>{specialties.map(([code,label])=><option key={code} value={code}>{label}</option>)}</select></label><label>Dịch vụ bệnh nhân sử dụng<select aria-label="Dịch vụ bệnh nhân sử dụng" value={offering} onChange={e=>{const id=e.target.value;setOffering(id);setOfferingPrice(null);if(id)void run(async()=>setOfferingPrice((await api.offeringPrice(scope,id)).amountVnd));}}><option value="">Chọn dịch vụ</option>{offerings.filter(o=>o.offering.specialtyCode===specialty&&specialty).map(o=><option key={o.offering.id} value={o.offering.id}>{o.offering.name}</option>)}</select></label><p className="reception-route-note">Bác sĩ được hệ thống điều phối theo chuyên khoa, dịch vụ, lịch làm việc và hàng đợi đang nhận khám.</p>{offeringPrice!==null&&<p className="desk-price">Giá dịch vụ tham khảo <strong>{formatVnd(offeringPrice)}</strong></p>}<button type="button" className="button-secondary" onClick={()=>{setExceptionDraft({patientId:patient?.patientId,type:'NO_ELIGIBLE_DOCTOR',reason:'Đối chiếu lựa chọn dịch vụ và bác sĩ đang nhận khám'});setDeskTab('operations');}}>Tạo yêu cầu khi không thể điều phối</button></>}
 <label>Phòng / khu vực tiếp nhận<select disabled={precheckPending} aria-label="Phòng hoặc khu vực tiếp nhận" value={point} onChange={e=>{const next=e.target.value;setPoint(next);setTickets(null);if(next)void run(()=>reloadQueue(0,next));}}><option value="">Chọn phòng / khu vực</option>{points.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
 <label>Lý do đến khám<textarea disabled={precheckPending} aria-label="Lý do đến khám" maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label>
 {patient?.status==='PROVISIONAL'&&<details><summary>Đối chiếu hồ sơ tạm</summary><label>Tham chiếu bằng chứng đối chiếu<input maxLength={180} value={evidence} onChange={e=>setEvidence(e.target.value)}/></label><button type="button" className="button-secondary" disabled={!evidence.trim()||!reason.trim()} onClick={()=>void run(async()=>{const p=await api.review(scope,patient,evidence,reason);setPatient(p);setPatients(rows=>rows.map(x=>x.patientId===p.patientId?p:x));})}>Ghi nhận đã xác minh</button></details>}
 <p className="muted-copy">Đối chiếu họ tên và ngày sinh trước khi cấp số. Dịch vụ cho biết bệnh nhân đến để sử dụng gì; phòng / khu vực cho biết nơi bệnh nhân chờ và được gọi. Thu tiền sau khi bác sĩ hoàn tất chuyên môn tại mục Thu phí & ca thu.</p>
 {date!==localDate()&&<p role="status">Ngày đã chọn dùng để tra cứu. Chọn ngày hôm nay để tiếp nhận và cấp số.</p>}
 <button type="button" className="booking-primary" disabled={date!==localDate()||precheckPending||!point||!reason.trim()||(arrivalMode==='walk-in'?(!patient||!specialty||!offering||offeringPrice===null):(!appointment?.patient||!appointmentVerified||appointmentAlreadyReceived(appointment)))} onClick={()=>void run(arrivalMode==='walk-in'?arriveWalkIn:checkArrival)}>{arrivalMode==='appointment'&&appointment&&appointmentAlreadyReceived(appointment)?'Đã tiếp nhận & cấp số':'Tiếp nhận & cấp số'}</button>
 </>}
 {appointment&&<details className="task-disclosure"><summary>Xử lý đến muộn, không đến hoặc bác sĩ vắng</summary><p>Ngoại lệ được giữ để theo dõi. Bác sĩ vắng cần quyền quản lý; chưa có thao tác hoàn tiền tự động.</p><label>Loại ngoại lệ<select disabled={busy} value={exceptionType} onChange={e=>setExceptionType(e.target.value)}><option value="LATE">Đến muộn</option><option value="NO_SHOW">Không đến</option>{canManage&&<option value="DOCTOR_ABSENT">Bác sĩ vắng</option>}</select></label><button className="button-secondary" disabled={busy||!reason.trim()||appointment.status!=='CONFIRMED'} onClick={()=>void run(async()=>{const key=await stableOperationKey('appointment-exception',{clinic:scope.clinic,branch,actorEmail:email,appointmentId:appointment.id,type:exceptionType,reason});const result=await api.recordException(scope,appointment,exceptionType,reason,key);setMessage('Đã ghi nhận ngoại lệ '+result.type+'. Cần theo dõi xử lý.');setExceptions(await api.exceptions(scope,appointment));setAppointments(await api.appointments(scope,date));})}>Ghi nhận ngoại lệ có lý do</button>{exceptions.map(x=><p key={x.id}>{stateName(x.type)} · {stateName(x.state)} · {x.notificationMode==='MANUAL_CONTACT_REQUIRED'?'Cần liên hệ bệnh nhân tại quầy':'Thông báo trong ứng dụng đang được giao'}</p>)}</details>}
 </aside>}
 </fieldset>}
 {deskTab==='queue'&&<section className="desk-list"><div className="desk-list-heading"><div><h2>Hàng đợi toàn phòng khám</h2><p>Theo dõi các phòng và bác sĩ. Trạng thái chuyên môn do bác sĩ cập nhật.</p></div></div>
 <fieldset className="desk-queue-controls" disabled={busy||navigationPending}><label>Điểm phục vụ<select aria-label="Điểm phục vụ" value={queuePoint} onChange={e=>setQueuePoint(e.target.value)}><option value="">Toàn phòng khám</option>{points.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Bác sĩ trong hàng đợi<select value={queueDoctor} onChange={e=>setQueueDoctor(e.target.value)}><option value="">Tất cả bác sĩ</option>{doctors.map(d=><option key={d.practitionerId} value={d.practitionerId}>{d.displayName}</option>)}</select></label><label>Tìm trong hàng đợi<input type="search" value={listQuery} onChange={e=>setListQuery(e.target.value)} placeholder="Tên, mã bệnh nhân, số thứ tự…"/></label><label>Trạng thái<select value={queueFilter} onChange={e=>setQueueFilter(e.target.value)}><option value="">Các lượt hiện tại</option>{Object.entries(queueStates).filter(([id])=>['WAITING','CALLED','SERVING','SKIPPED','ABSENT'].includes(id)).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label></fieldset>
 {activeQueueTickets.map(active=><p className="desk-queue-note" role="status" key={active.id}><strong>{active.code}</strong> · {doctors.find(d=>d.practitionerId===active.doctorId)?.displayName??'Bác sĩ phụ trách'} · {active.state==='SERVING'?'đang khám.':'đã gọi, đang chờ vào khám.'} Hàng đợi của bác sĩ khác vẫn hoạt động độc lập.</p>)}
 <label className="reception-queue-reason">Lý do thao tác hàng đợi<textarea disabled={busy||navigationPending} value={reason} maxLength={500} onChange={e=>setReason(e.target.value)} placeholder="Ghi lý do bỏ qua, đánh dấu vắng hoặc đưa lại cuối hàng…"/></label>
 <div className="desk-table-scroll"><table className="desk-table"><caption className="sr-only">Danh sách hàng đợi</caption><thead><tr><th>Số thứ tự</th><th>Bệnh nhân</th><th>Thời gian</th><th>Chuyên khoa / bác sĩ</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{visibleQueue.map(t=>{const received=recoveries.find(a=>a.visit.id===t.visitId)?.visit;const d=doctors.find(d=>d.practitionerId===t.doctorId);const elapsed=t.checkedInAt?Math.max(0,Math.floor((now-new Date(t.checkedInAt).getTime())/60000)):null;return <tr key={t.id}><td><strong className="desk-token">{t.code}</strong><small>{points.find(p=>p.id===t.servicePointId)?.name}</small></td><td><PatientIdentity patient={t.patient}/><small>{received?(received.appointmentId?'Đã đặt lịch':'Khám trực tiếp'):'Nguồn tiếp nhận đang đối chiếu'}</small></td><td>{t.checkedInAt?<><span>Đến {clockTime(t.checkedInAt)}</span>{['WAITING','CALLED','SKIPPED','ABSENT'].includes(t.state)&&<small>Đã chờ {elapsed} phút</small>}</>:'Chưa ghi nhận giờ đến'}</td><td>{d?.specialtyName??'Chuyên khoa theo phân công'}<small>{d?.displayName??'Bác sĩ phụ trách'}</small></td><td><span className="task-status" data-state={t.state}>{received&&['IN_PROGRESS','AWAITING_RESULTS'].includes(received.status)?visitStatus[received.status]:queueStates[t.state]??t.state}</span></td><td><div className="desk-row-actions">
 {['WAITING','CALLED','SKIPPED','ABSENT'].includes(t.state)&&<>
 {t.state==='WAITING'&&<button type="button" className="button-secondary" title={callTicketHint(t)} disabled={!canCallTicket(t)} onClick={()=>void run(()=>moveTicket(t,'call'))}>Gọi {t.code}</button>}
 {t.state==='CALLED'&&<button type="button" className="button-secondary" disabled={busy||navigationPending} onClick={()=>void run(()=>moveTicket(t,'recall'))}>Gọi lại</button>}
 {['WAITING','CALLED'].includes(t.state)&&<button type="button" className="button-secondary" disabled={busy||navigationPending||!reason.trim()} onClick={()=>void run(()=>moveTicket(t,'skip'))}>Bỏ qua tạm thời</button>}
 {t.state!=='ABSENT'&&<button type="button" className="button-secondary" disabled={busy||navigationPending||!reason.trim()} onClick={()=>void run(()=>moveTicket(t,'absent'))}>Đánh dấu vắng</button>}
 {['SKIPPED','ABSENT'].includes(t.state)&&<button type="button" className="button-secondary" disabled={busy||navigationPending||!reason.trim()} onClick={()=>void run(()=>moveTicket(t,'requeue'))}>Đưa lại cuối hàng</button>}
 </>}
 <details className="reception-row-exception"><summary>Yêu cầu đổi bác sĩ / chuyên khoa</summary><p>Lượt khám đã vào hàng đợi. Lễ tân không có quyền điều chuyển bác sĩ, chuyên khoa hoặc điểm phục vụ.</p><button type="button" className="button-secondary" disabled={busy||navigationPending} onClick={()=>requestException(t)}>Tạo yêu cầu xử lý</button></details>
 {t.state==='SERVING'&&<small>Trạng thái chuyên môn chỉ đọc</small>}
 </div></td></tr>;})}{!visibleQueue.length&&<tr><td colSpan={6} className="desk-empty">{tickets===null?'Đang đồng bộ hàng đợi…':'Hiện không có bệnh nhân đang chờ phù hợp tại điểm phục vụ này.'}</td></tr>}</tbody></table></div>
 <div className="reception-clinical-readonly"><h3>Theo dõi chuyên môn · chỉ đọc</h3>{recoveries.filter(a=>['IN_PROGRESS','AWAITING_RESULTS','CLINICALLY_COMPLETED'].includes(a.visit.status)&&matches(listQuery,a.visit.patient?.fullName,a.visit.patient?.patientCode)).map(a=><article key={a.visit.id}><PatientIdentity patient={a.visit.patient}/><span className="task-status" data-state={a.visit.status}>{visitStatus[a.visit.status]}</span>{a.visit.status==='CLINICALLY_COMPLETED'&&<small>Đối chiếu khoản phải thu tại Thu phí &amp; ca thu.</small>}</article>)}{!recoveries.some(a=>['IN_PROGRESS','AWAITING_RESULTS','CLINICALLY_COMPLETED'].includes(a.visit.status))&&<p className="muted-copy">Chưa có lượt đang khám, chờ kết quả hoặc vừa hoàn tất trong ngày đã chọn.</p>}</div></section>}
 {deskTab==='recovery'&&<label>Lý do tiếp nhận hoặc điều phối<textarea disabled={busy||navigationPending} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label>}
 </>}
 {validScope&&<section hidden={deskTab!=='recovery'} className="public-section reception-recovery-tab"><h2 id="reception-recovery" tabIndex={-1}>Lịch sử tiếp nhận</h2><p>Các lượt tiếp nhận chung của phòng khám trong ngày đã chọn. Tra cứu tại đây trước khi tạo lại một lượt đang chờ xác nhận.</p><WorklistTools query={recoveryQuery} onQuery={setRecoveryQuery} state={recoveryFilter} onState={setRecoveryFilter} states={visitStatus} disabled={busy} count={recoveries.filter(a=>(!recoveryFilter||a.visit.status===recoveryFilter)&&(!recoveryQuery||`${a.visit.patient?.fullName} ${a.visit.patient?.patientCode} ${dateLabel(a.visit.patient?.dateOfBirth)} ${a.visit.ticket?.code}`.toLocaleLowerCase('vi-VN').includes(recoveryQuery.toLocaleLowerCase('vi-VN')))).length} total={recoveries.length}/>{!recoveries.length&&<p className="desk-empty">Chưa có lượt tiếp nhận trong ngày đã chọn.</p>}<div className="arrival-recoveries">{recoveries.filter(a=>(!recoveryFilter||a.visit.status===recoveryFilter)&&(!recoveryQuery||`${a.visit.patient?.fullName} ${a.visit.patient?.patientCode} ${dateLabel(a.visit.patient?.dateOfBirth)} ${a.visit.ticket?.code}`.toLocaleLowerCase('vi-VN').includes(recoveryQuery.toLocaleLowerCase('vi-VN')))).map(a=><article className="booking-appointment" key={a.visit.id}><h3>{a.visit.ticket?.code??(a.visit.status==='ARRIVAL_PENDING'?'Tiếp nhận lịch đang chờ xác nhận':'Lượt '+(visitStatus[a.visit.status]??a.visit.status).toLowerCase())}</h3><PatientIdentity patient={a.visit.patient}/><p>{a.operation==='walk-in'?'Khách đến trực tiếp':'Lịch đã đặt'} · {visitStatus[a.visit.status]??a.visit.status} · {new Intl.DateTimeFormat('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',timeStyle:'short'}).format(new Date(a.createdAt))}</p><button className="button-secondary" disabled={busy||a.visit.status==='ARRIVAL_PENDING'} onClick={()=>void run(async()=>{const v=await api.readVisit(scope,a.visit.id);setVisit(v);setWalkRecovery(false);walkAttempt.current=null;setMessage('Đã xác nhận lượt tiếp nhận đã ghi · '+(v.ticket?.code??v.status));if(v.ticket){setPoint(v.ticket.servicePointId);const items=await readAllQueue(scope,v.ticket.servicePointId,date);setTickets(items);setNextQueue(null);}setRecoveries(await api.workload(scope,date));})}>{a.visit.status==='ARRIVAL_PENDING'?'Cần đối chiếu tại Ngoại lệ':'Xem trạng thái từ máy chủ'}</button></article>)}</div></section>}
 {validScope&&deskTab==='operations'&&<ReceptionExceptionCenter key={exceptionDraft?.visitId??exceptionDraft?.patientId??'general'} scope={scope} requests={requestRows} sourceExceptions={sourceExceptions} appointments={appointments} arrivals={recoveries} tickets={tickets??[]} draft={exceptionDraft} disabled={busy} canManage={canManage} onPending={setExceptionPending} onUpdated={refreshReception}/>}
 <div hidden={deskTab!=='operations'}>{canManage&&<section className="task-card">  <details><summary>Báo bác sĩ vắng theo khoảng lịch</summary><p>Quản trị báo vắng theo giờ Việt Nam. Khoảng vắng chặn đặt mới tại nguồn. Ghi ngoại lệ cho lịch đã đặt theo từng nhóm tối đa 10 lịch, thử lại phần chưa thành công; giữ lịch và giá đã chốt.</p><label>Bác sĩ báo vắng<select disabled={busy} value={doctor} onChange={e=>{setDoctor(e.target.value);setAbsences([]);}}><option value="">Chọn bác sĩ</option>{doctors.map(d=><option key={d.practitionerId} value={d.practitionerId}>{d.displayName}</option>)}</select></label><label>Bắt đầu vắng (giờ Việt Nam)<input type="datetime-local" disabled={busy} value={absenceStart} onChange={e=>setAbsenceStart(e.target.value)}/></label><label>Kết thúc vắng (giờ Việt Nam)<input type="datetime-local" disabled={busy} value={absenceEnd} onChange={e=>setAbsenceEnd(e.target.value)}/></label><button className="button-secondary" disabled={busy||!doctor||!absenceStart||!absenceEnd||!reason.trim()} onClick={()=>void run(reportDoctorAbsence)}>Ghi khoảng vắng có lý do</button>{absences.map(a=><article className="booking-appointment" key={a.id}><p>{new Date(a.startsAt).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'})} — {new Date(a.endsAt).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'})}</p><button className="button-secondary" disabled={busy} onClick={()=>void run(async()=>{const result=await api.applyAbsence(scope,a);setMessage(`Đã ghi ngoại lệ cho ${result.recorded} lịch. ${result.retryRequired.length} lịch cần kiểm tra và thử lại.${result.hasMore?' Còn lịch cần ghi ở nhóm tiếp theo.':' Đã hết nhóm lịch chưa ghi tại thời điểm tra cứu.'} Liên hệ bệnh nhân và theo dõi ngoại lệ đang mở.`);})}>Ghi ngoại lệ các lịch bị ảnh hưởng</button></article>)}</details>
 <details><summary>Cấu hình điểm phục vụ</summary><p>Quản trị được cấp quyền cấu hình điểm phục vụ.</p><form className="booking-form" onSubmit={e=>{e.preventDefault();void run(async()=>{await api.createPoint(scope,pointCode,pointName);setPoints(await api.points(scope));setMessage('Đã tạo điểm phục vụ.');});}}><label>Mã điểm phục vụ<input required pattern="[A-Z0-9]{1,8}" maxLength={8} disabled={busy} value={pointCode} onChange={e=>setPointCode(e.target.value.toUpperCase())}/></label><label>Tên điểm phục vụ<input required maxLength={100} disabled={busy} value={pointName} onChange={e=>setPointName(e.target.value)}/></label><button className="button-secondary" disabled={busy}>Tạo điểm phục vụ</button></form></details></section>}{validScope&&canManage&&<AbsenceLifecyclePanel scope={scope} doctor={doctor} disabled={busy||walkRecovery||absenceRecovery||supervisorPending||queuePending} appointment={appointment} exceptions={exceptions} onPending={setLifecyclePending} canManage={canManage} active={deskTab==='operations'}/>}
 {validScope&&canManage&&<SupervisorArrivalPanel scope={scope} disabled={busy||walkRecovery||absenceRecovery||lifecyclePending||queuePending} onPending={setSupervisorPending} canManage={canManage} active={deskTab==='operations'} onUpdated={async v=>{if(v.ticket){setPoint(v.ticket.servicePointId);const items=await readAllQueue(scope,v.ticket.servicePointId,date);setTickets(items);}}}/>}
 {validScope&&<OvernightQueuePanel scope={scope} tickets={tickets??[]} onPending={setQueuePending} disabled={busy||walkRecovery||absenceRecovery||lifecyclePending||supervisorPending} onMoved={async()=>{const today=localDate();setDate(today);await loadDay(today);}}/>}
 </div></section>;
}








