import {WorklistTools} from './WorklistTools';
import {stateName,dateLabel} from '../utils/display';
import {PatientIdentity} from './PatientIdentity';
import {formatVnd} from '../utils/vnd';
import {usePanelSession,useSessionBranch} from '../auth/SessionProvider';
import {SourceSessionState} from '../auth/SourceSessionState';
import { useEffect, useRef, useState } from 'react';
import * as api from '../api/reception';
import { signIn, RequestError } from '../api/booking';
import { stableOperationKey, forgetOperationKey } from '../api/idempotency';
import { AbsenceLifecyclePanel } from './AbsenceLifecyclePanel';
import { SupervisorArrivalPanel } from './SupervisorArrivalPanel';
import { OvernightQueuePanel } from './OvernightQueuePanel';
import type { IamContextView } from '../types/contracts';
import { useNavigationLock } from './useNavigationLock';
const queueStates:Record<string,string>={WAITING:'Chờ gọi',CALLED:'Đã gọi',SERVING:'Đang khám',DONE:'Đã phục vụ',SKIPPED:'Đã bỏ qua',TRANSFERRED:'Đã chuyển phòng'};
const matches=(query:string,...values:(string|null|undefined)[])=>values.join(' ').toLocaleLowerCase('vi-VN').includes(query.trim().toLocaleLowerCase('vi-VN'));
const clockTime=(value:string)=>new Intl.DateTimeFormat('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',timeStyle:'short'}).format(new Date(value));
const visitStatus:Record<string,string>={ARRIVAL_PENDING:'Đang chờ xác nhận',WAITING:'Chờ khám',IN_PROGRESS:'Đang khám',AWAITING_RESULTS:'Chờ kết quả',CLINICALLY_COMPLETED:'Hoàn tất chuyên môn',CLOSED:'Đã đóng',CANCELLED:'Đã hủy',INTERRUPTED:'Gián đoạn'};
const localDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export function ReceptionPanel({onClinic,onNavigationLock}:{onClinic?:(name:string)=>void;onNavigationLock?:(reason:string|null)=>void}){
 const [arrivalMode,setArrivalMode]=useState('appointment');
 const [deskTab,setDeskTab]=useState('intake'),[recoveryQuery,setRecoveryQuery]=useState(''),[recoveryFilter,setRecoveryFilter]=useState('');
 const shared=usePanelSession(()=>run(login));
 const [token,setToken]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState('');
 const [directory,setDirectory]=useState<api.Directory|null>(null),[branch,setBranch]=useState('');
 const [doctors,setDoctors]=useState<api.Doctor[]>([]),[doctor,setDoctor]=useState('');
 const [offerings,setOfferings]=useState<api.ReceptionOffering[]>([]),[offering,setOffering]=useState(''),[offeringPrice,setOfferingPrice]=useState<number|null>(null);
 const [points,setPoints]=useState<api.Point[]>([]),[point,setPoint]=useState(''),[destination,setDestination]=useState('');
 const [patients,setPatients]=useState<api.Patient[]>([]),[patient,setPatient]=useState<api.Patient|null>(null);
 const [name,setName]=useState(''),[dob,setDob]=useState(''),[createName,setCreateName]=useState(''),[createDob,setCreateDob]=useState(''),[createPhone,setCreatePhone]=useState(''),[createPatientOpen,setCreatePatientOpen]=useState(false),[patientSearchBusy,setPatientSearchBusy]=useState(false),[patientSearchDone,setPatientSearchDone]=useState(false),[patientSearchError,setPatientSearchError]=useState(''),[reason,setReason]=useState(''),[evidence,setEvidence]=useState('');
 const [date,setDate]=useState(localDate),[appointments,setAppointments]=useState<api.Appointment[]>([]),[appointment,setAppointment]=useState<api.Appointment|null>(null);
 const [,setNextQueue]=useState<number|null>(null);
 const detailHeading=useRef<HTMLHeadingElement>(null);
 const [listQuery,setListQuery]=useState(''),[queueFilter,setQueueFilter]=useState(''),[queueDoctor,setQueueDoctor]=useState(''),[syncError,setSyncError]=useState(''),[lastSync,setLastSync]=useState('');
 const [checkRecovery,setCheckRecovery]=useState(false);
 const checkAttempt=useRef<{scope:api.Scope;appointment:api.Appointment;point:string;reason:string;key:string}|null>(null);
 const [tickets,setTickets]=useState<api.Ticket[]|null>(null),[visit,setVisit]=useState<api.Visit|null>(null);
 const [recoveries,setRecoveries]=useState<api.ArrivalRecovery[]>([]);const newIntent=useRef('');
 const [exceptions,setExceptions]=useState<api.Exception[]>([]),[exceptionType,setExceptionType]=useState('LATE');
 const [absences,setAbsences]=useState<api.Absence[]>([]),[absenceStart,setAbsenceStart]=useState(''),[absenceEnd,setAbsenceEnd]=useState('');
 const [absenceRecovery,setAbsenceRecovery]=useState(false);const absenceAttempt=useRef<{scope:api.Scope;doctor:string;body:{startsAt:string;endsAt:string;reason:string};key:string}|null>(null);
 const [queuePending,setQueuePending]=useState(false);
 const [supervisorPending,setSupervisorPending]=useState(false);
 const [lifecyclePending,setLifecyclePending]=useState(false),[memberships,setMemberships]=useState<IamContextView[]>([]);
 const [pointCode,setPointCode]=useState(''),[pointName,setPointName]=useState('');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');const running=useRef(false);
 const [walkRecovery,setWalkRecovery]=useState(false);
 const navigationPending=checkRecovery||walkRecovery||absenceRecovery||lifecyclePending||supervisorPending||queuePending;
 useNavigationLock(navigationPending?'Xác minh hoặc thử lại thao tác tiếp nhận đang chờ trước khi rời màn hình.':busy?'Đợi thao tác tiếp nhận xử lý xong trước khi rời màn hình.':null,onNavigationLock);
 const walkAttempt=useRef<{scope:api.Scope;payload:{clinic:string;branch:string;actorEmail:string;patientId:string;doctorId:string;offeringId:string;servicePointId:string;reason:string;intent:string};key:string}|null>(null);
 const scope:api.Scope={token,clinic:directory?.id??'',branch};
 async function run(action:()=>Promise<void>){if(running.current)return;running.current=true;setBusy(true);setError('');setMessage('');try{await action();}catch(e){setError(e instanceof Error?e.message:'Chưa xác định được kết quả. Thử lại cùng yêu cầu.');}finally{running.current=false;setBusy(false);}}
 async function login(){const auth=shared?.session?.token??(await signIn(email,password)).data.accessToken;setEmail(shared?.session?.email??email);setPassword('');const memberships=await api.contexts(auth);setMemberships(memberships);const clinicIds=[...new Set(memberships.filter(m=>['ADMIN','STAFF'].includes(m.role)).map(m=>m.clinicId))];const requested=new URLSearchParams(location.search).get('clinicId');const id=requested?(clinicIds.includes(requested)?requested:null):clinicIds.length===1?clinicIds[0]:null;if(!id)throw new Error('Phiên này chưa xác định một phòng khám cho Workspace. Mở đường dẫn Workspace được cấp cho phòng khám của bạn.');const d=await api.directory(auth,id);setToken(auth);setDirectory(d);onClinic?.(d.name);setBranch('');setPatient(null);setPatients([]);setAppointments([]);setAppointment(null);setExceptions([]);setVisit(null);setTickets(null);setNextQueue(null);}
 useSessionBranch(shared,token,directory,branch,id=>run(()=>chooseBranch(id)));
 async function readAllQueue(s:api.Scope,selectedPoint:string,selectedDate:string){const items:api.Ticket[]=[];let after=0;let page:api.QueuePage;do{page=await api.queuePage(s,selectedPoint,selectedDate,after);items.push(...page.items);after=page.nextAfterNumber??0;}while(after>0);return items;}
 async function chooseBranch(id:string){walkAttempt.current=null;setRecoveries([]);setBranch(id);setAbsences([]);setPatient(null);setPatients([]);setVisit(null);setAppointments([]);setAppointment(null);setExceptions([]);setTickets(null);setNextQueue(null);setPoint('');setDoctor('');setDoctors([]);setPoints([]);setOfferings([]);setOffering('');setOfferingPrice(null);if(!id)return;const s={...scope,branch:id};const [d,p,a,o,bookings]=await Promise.all([api.doctors(s),api.points(s),api.arrivals(s,date),api.offerings(s).catch(e=>{setError(e instanceof Error?e.message:'Bảng giá chưa đồng bộ được.');return [] as api.ReceptionOffering[];}),api.appointments(s,date).catch(e=>{setError(e instanceof Error?e.message:'Lịch hẹn trong ngày chưa đồng bộ được.');return [] as api.Appointment[];})]);setOfferings(o.filter(x=>x.active&&x.offering.active));setRecoveries(a);setAppointments(bookings);const today=localDate();setDoctors(d.filter(x=>x.active&&x.effectiveFrom<=today&&(!x.effectiveUntil||today<x.effectiveUntil)));setPoints(p);const firstPoint=p[0];if(firstPoint){setPoint(firstPoint.id);try{const items=await readAllQueue(s,firstPoint.id,date);setTickets(items);setNextQueue(null);}catch(e){setError(e instanceof Error?e.message:'Hàng đợi chưa đồng bộ được.');}}}
 async function reloadQueue(_afterNumber=0,selectedPoint=point){if(!selectedPoint)return;setTickets(null);setNextQueue(null);setTickets(await readAllQueue(scope,selectedPoint,date));}
 async function loadDay(nextDate:string){const [bookings,arrivals,queue]=await Promise.allSettled([api.appointments(scope,nextDate),api.arrivals(scope,nextDate),point?readAllQueue(scope,point,nextDate):Promise.resolve(null)]);if(bookings.status==='fulfilled')setAppointments(bookings.value);else setError('Lịch hẹn trong ngày đã chọn chưa đồng bộ được.');if(arrivals.status==='fulfilled')setRecoveries(arrivals.value);else setError('Lịch sử tiếp nhận trong ngày chưa đồng bộ được.');if(queue.status==='fulfilled'&&queue.value){setTickets(queue.value);setNextQueue(null);}else if(queue.status==='rejected'){setTickets(null);setError('Hàng đợi trong ngày đã chọn chưa đồng bộ được.');}}
 async function moveTicket(ticket:api.Ticket,action:'call'|'skip'|'transfer'){
  await api.move(scope,ticket,action,action==='call'?(reason.trim()||'Gọi bệnh nhân vào phòng khám'):reason,action==='transfer'?destination:undefined);
  setMessage(action==='transfer'?`Đã chuyển từ ${points.find(p=>p.id===ticket.servicePointId)?.name??'phòng cũ'} sang ${points.find(p=>p.id===destination)?.name??'phòng mới'}.`:`Đã ${action==='call'?'gọi':'bỏ qua'} ${ticket.code}.`);
  setVisit(null);setVisit(await api.readVisit(scope,ticket.visitId));await reloadQueue();
 }
 async function reportDoctorAbsence(){
  if(!absenceAttempt.current){const body={startsAt:new Date(absenceStart+':00+07:00').toISOString(),endsAt:new Date(absenceEnd+':00+07:00').toISOString(),reason};absenceAttempt.current={scope:{...scope},doctor,body,key:await stableOperationKey('doctor-absence',{clinic:scope.clinic,branch,actorEmail:email,doctor,...body})};}
  const attempt=absenceAttempt.current;setAbsenceRecovery(true);
  try{const result=await api.reportAbsence(attempt.scope,attempt.doctor,attempt.body,attempt.key);setAbsenceRecovery(false);absenceAttempt.current=null;setAbsences(old=>[result,...old.filter(a=>a.id!==result.id)]);setMessage('Đã ghi khoảng vắng và chặn đặt mới. Tiếp tục ghi ngoại lệ cho các lịch bị ảnh hưởng.');}catch(e){if(e instanceof RequestError&&e.status>=400&&e.status<500){setAbsenceRecovery(false);absenceAttempt.current=null;}throw e;}
 }
 async function arriveWalkIn(){
  if(!walkAttempt.current){if(!patient)return;const payload={clinic:scope.clinic,branch,actorEmail:email,patientId:patient.patientId,doctorId:doctor,offeringId:offering,servicePointId:point,reason,intent:newIntent.current};walkAttempt.current={scope:{...scope},payload,key:await stableOperationKey('walk-in',payload)};}
  const attempt=walkAttempt.current;setWalkRecovery(true);
  let confirmed:api.Visit;
  try{const p=attempt.payload;confirmed=await api.walkIn(attempt.scope,p.patientId,p.doctorId,p.servicePointId,p.reason,attempt.key,p.offeringId);}
  catch(e){if(e instanceof RequestError&&e.status>=400&&e.status<500){setWalkRecovery(false);walkAttempt.current=null;}throw e;}
  setWalkRecovery(false);setVisit(confirmed);setMessage('Đã tiếp nhận khách đến trực tiếp · '+confirmed.ticket?.code);const items=await readAllQueue(attempt.scope,attempt.payload.servicePointId,date);setTickets(items);setNextQueue(null);
 }
 async function newWalkIn(){if(!visit||walkRecovery)return;if(walkAttempt.current)await forgetOperationKey('walk-in',walkAttempt.current.payload);walkAttempt.current=null;newIntent.current=crypto.randomUUID();setVisit(null);setPatient(null);setPatients([]);setName('');setDob('');setCreateName('');setCreateDob('');setCreatePhone('');setCreatePatientOpen(false);setReason('');setEvidence('');setMessage('Đối chiếu hồ sơ cho lượt tiếp nhận mới.');}

 function choosePatient(p:api.Patient){setPatient(p);setAppointment(null);setVisit(null);setEvidence('');setReason('Tiếp nhận khách đến trực tiếp tại quầy');walkAttempt.current=null;newIntent.current=crypto.randomUUID();}
 async function checkArrival(){
  if(!checkAttempt.current){if(!appointment?.patient||!point)return;checkAttempt.current={scope:{...scope},appointment,point,reason,key:await stableOperationKey('check-in',{clinic:scope.clinic,branch,actorEmail:email,appointmentId:appointment.id,patientId:appointment.patientId,servicePointId:point,reason})};}
  const attempt=checkAttempt.current;setCheckRecovery(true);
  let confirmed:api.Visit;
  try{confirmed=await api.checkIn(attempt.scope,attempt.appointment,attempt.appointment.patientId,attempt.point,attempt.reason,attempt.key);}catch(e){if(e instanceof RequestError&&e.status>=400&&e.status<500){setCheckRecovery(false);checkAttempt.current=null;}throw e;}
  setCheckRecovery(false);setVisit(confirmed);setMessage('Đã ghi nhận tiếp nhận lịch · '+(confirmed.ticket?.code??'Đang chờ xác nhận'));
  await loadDay(date);
  setRecoveries(current=>[{operation:'check-in',createdAt:new Date().toISOString(),visit:confirmed},...current.filter(x=>x.visit.id!==confirmed.id)]);
 }
 useEffect(()=>{detailHeading.current?.focus();},[patient?.patientId,appointment?.id]);
 const canManage=memberships.some(m=>m.clinicId===scope.clinic&&m.role==='ADMIN'&&(m.allBranches||m.branchIds.includes(branch)));
 const validScope=!!token&&!!directory&&!!branch;
 const appointmentAlreadyReceived=(a:api.Appointment)=>a.status==='CHECKED_IN'||recoveries.some(x=>x.visit.appointmentId===a.id);
 const pointQueue=(tickets??[]).filter(t=>!point||t.servicePointId===point);
 const activeQueueTickets=pointQueue.filter(t=>['CALLED','SERVING'].includes(t.state));
 const activeForDoctor=(t:api.Ticket)=>activeQueueTickets.find(x=>x.doctorId===t.doctorId);
 const firstWaitingForDoctor=(t:api.Ticket)=>pointQueue.filter(x=>x.doctorId===t.doctorId&&x.state==='WAITING').sort((a,b)=>a.number-b.number)[0];
 const canCallTicket=(t:api.Ticket)=>!busy&&!navigationPending&&t.state==='WAITING'&&!activeForDoctor(t)&&firstWaitingForDoctor(t)?.id===t.id;
 const callTicketHint=(t:api.Ticket)=>{const active=activeForDoctor(t),first=firstWaitingForDoctor(t);return t.state==='CALLED'?'Lượt này đã được gọi và đang chờ vào phòng.':t.state==='SKIPPED'?'Lượt này đã được bỏ qua.':active?`${active.code} của cùng bác sĩ đang ${active.state==='SERVING'?'được khám':'chờ vào phòng'}; chưa thể gọi lượt tiếp theo của bác sĩ này.`:first&&first.id!==t.id?`Phải xử lý ${first.code} trước trong hàng đợi của bác sĩ này.`:'Gọi lượt chờ tiếp theo của bác sĩ này.';};
 useEffect(()=>{const query=name.trim();const digits=query.replace(/\D/g,'');const phoneQuery=digits.length>=6&&/^[+\d\s().-]+$/.test(query);const canSearch=!!query&&(phoneQuery||!!dob);if(!validScope||deskTab!=='intake')return;let active=true;setPatientSearchError('');if(!query&&!dob){setPatientSearchBusy(true);setPatientSearchDone(false);void api.recentPatients(scope).then(rows=>{if(active)setPatients(rows);}).catch(e=>{if(active)setPatientSearchError(e instanceof Error?e.message:'Chưa tải được hồ sơ bệnh nhân gần đây.');}).finally(()=>{if(active)setPatientSearchBusy(false);});return()=>{active=false;};}if(!canSearch){setPatients([]);setPatientSearchBusy(false);setPatientSearchDone(false);return()=>{active=false;};}const timer=window.setTimeout(()=>{setPatientSearchBusy(true);setPatientSearchError('');void api.suggestions(scope,phoneQuery?'':query,phoneQuery?'':dob,phoneQuery?query:'').then(rows=>{if(active){setPatients(rows);setPatientSearchDone(true);}}).catch(e=>{if(active){setPatients([]);setPatientSearchError(e instanceof Error?e.message:'Chưa tìm được hồ sơ bệnh nhân.');}}).finally(()=>{if(active)setPatientSearchBusy(false);});},300);return()=>{active=false;window.clearTimeout(timer);};},[validScope,deskTab,name,dob,scope.token,scope.clinic,scope.branch]);
 useEffect(()=>{if(!appointment||!validScope)return;let active=true;void api.exceptions(scope,appointment).then(rows=>{if(active)setExceptions(rows);}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Chưa đồng bộ được ngoại lệ lịch hẹn.');});return()=>{active=false;};},[appointment?.id,scope.token,scope.clinic,scope.branch,validScope]);
 useEffect(()=>{if(deskTab!=='operations'||!doctor||!validScope)return;let active=true;void api.doctorAbsences(scope,doctor).then(rows=>{if(active)setAbsences(rows);}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Chưa đồng bộ được khoảng vắng của bác sĩ.');});return()=>{active=false;};},[deskTab,doctor,scope.token,scope.clinic,scope.branch,validScope]);

 useEffect(()=>{
  if(!validScope||busy||navigationPending)return;
  let active=true,inFlight=false;
  async function refresh(){
   if(!active||inFlight||running.current||document.visibilityState==='hidden')return;inFlight=true;
   try{const [bookings,arrivals,queue]=await Promise.all([api.appointments(scope,date),api.arrivals(scope,date),point?readAllQueue(scope,point,date):Promise.resolve(null)]);
    if(active&&!running.current){setAppointments(bookings);setRecoveries(arrivals);setTickets(queue);setSyncError('');setLastSync(clockTime(new Date().toISOString()));}
   }catch{if(active)setSyncError('Chưa đồng bộ được. Hệ thống sẽ tự thử lại; dữ liệu có thể đã cũ.');}finally{inFlight=false;}
  }
  const timer=window.setInterval(()=>void refresh(),15000);const resume=()=>void refresh();window.addEventListener('focus',resume);document.addEventListener('visibilitychange',resume);
  return()=>{active=false;window.clearInterval(timer);window.removeEventListener('focus',resume);document.removeEventListener('visibilitychange',resume);};
 },[validScope,scope.token,scope.clinic,scope.branch,date,point,busy,navigationPending]);
 return <section className="booking-panel reception-panel front-desk"><header className="task-panel-header"><div><span className="eyebrow">Tiếp nhận tại phòng khám</span><h1>Quầy tiếp nhận</h1><p>Lịch hẹn, khách đến khám và điều phối hàng đợi trong một luồng làm việc.</p></div></header>
 {!token&&shared?<SourceSessionState error={error} retry={()=>void run(login)}/>:!token?<form className="booking-form" onSubmit={e=>{e.preventDefault();void run(login);}}><label>Email nhân viên<input type="email" required autoComplete="username" disabled={busy} value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Mật khẩu nhân viên<input type="password" required autoComplete="current-password" disabled={busy} value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="booking-primary" disabled={busy}>Đăng nhập tiếp nhận</button></form>:<><div hidden={!!shared&&directory?.branches.length===1}><p>Phòng khám: <strong>{directory?.name}</strong></p><label>Địa điểm tiếp nhận<select aria-label="Địa điểm tiếp nhận" disabled={busy||navigationPending} value={branch} onChange={e=>void run(()=>chooseBranch(e.target.value))}><option value="">Chọn địa điểm</option>{directory?.branches.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></label></div>{!shared&&<button className="button-secondary" disabled={busy||navigationPending} onClick={()=>{setToken('');setMemberships([]);setLifecyclePending(false);setSupervisorPending(false);setQueuePending(false);setDirectory(null);setRecoveries([]);setWalkRecovery(false);setAbsenceRecovery(false);absenceAttempt.current=null;setAbsences([]);setPatient(null);setPatients([]);setTickets(null);setNextQueue(null);setAppointments([]);setAppointment(null);setExceptions([]);setVisit(null);walkAttempt.current=null;onClinic?.('Phòng khám theo phiên đăng nhập');}}>Đăng xuất tiếp nhận</button>}</>}
 {visit&&<p role="status">Lượt tiếp nhận: {visitStatus[visit.status]??visit.status} · {visit.ticket?.code??'Đang chờ xác nhận lượt đến'}</p>}
 <div aria-live="polite">{busy&&<p role="status">Đang xử lý…</p>}{error&&<p role="alert" className="booking-error">{error}</p>}{message&&<p role="status">{message}</p>}</div>
 {walkRecovery&&<div className="booking-confirm"><p>Chưa xác định được kết quả tiếp nhận. Giữ nguyên bệnh nhân, bác sĩ, điểm phục vụ và lý do cho đến khi xác nhận lượt này.</p><button className="booking-primary" disabled={busy} onClick={()=>void run(arriveWalkIn)}>Thử lại lượt tiếp nhận đang chờ</button></div>}
 {absenceRecovery&&<div className="booking-confirm"><p>Chưa xác định được kết quả báo vắng. Thử lại cùng bác sĩ, khoảng thời gian và lý do đã gửi.</p><button className="booking-primary" disabled={busy} onClick={()=>void run(reportDoctorAbsence)}>Thử lại báo vắng đang chờ</button></div>}

 {checkRecovery&&<div className="booking-confirm" role="status"><p>Chưa xác định kết quả tiếp nhận lịch. Thử lại cùng yêu cầu để tránh cấp số trùng.</p><button className="booking-primary" disabled={busy} onClick={()=>void run(checkArrival)}>Thử lại tiếp nhận lịch đang chờ</button></div>}
 {validScope&&<>
 <div className="desk-overview"><div><span>Lịch trong ngày</span><strong>{appointments.length}</strong></div><div><span>Chờ tiếp nhận</span><strong>{appointments.filter(a=>a.status==='CONFIRMED').length}</strong></div><div><span>Chờ gọi tại phòng</span><strong>{tickets?.filter(t=>['WAITING','CALLED'].includes(t.state)).length??'—'}</strong></div><div><span>Đang khám tại phòng</span><strong>{tickets?.filter(t=>t.state==='SERVING').length??'—'}</strong></div></div>
 <nav className="task-tabs" aria-label="Công việc tiếp nhận">{[['intake','Tiếp nhận bệnh nhân'],['queue','Hàng đợi'],['recovery','Lịch sử tiếp nhận'],['operations','Xử lý phát sinh']].map(([id,label])=><button type="button" key={id} disabled={busy||navigationPending} aria-pressed={deskTab===id} onClick={()=>{setDeskTab(id);setListQuery('');}}>{label}</button>)}</nav>
 <div className="desk-daybar"><label>Ngày làm việc<input type="date" required disabled={busy||navigationPending} value={date} onChange={e=>{const next=e.target.value;if(!next)return;setDate(next);setTickets(null);setRecoveries([]);setAppointment(null);setPatient(null);setVisit(null);setExceptions([]);setAppointments([]);void run(()=>loadDay(next));}}/></label><span className="muted-copy">{dateLabel(date)}</span><p className="desk-sync" role="status">{syncError|| (lastSync?'Đã cập nhật '+lastSync+' · Tự đồng bộ mỗi 15 giây':'Tự đồng bộ dữ liệu trong ngày')}</p></div>
 {deskTab==='intake'&&<fieldset className="desk-workspace" disabled={busy||navigationPending}>
 <section className="desk-list">
 <div className="desk-list-heading"><div><h2>{arrivalMode==='appointment'?'Lịch hẹn trong ngày':'Hồ sơ bệnh nhân'}</h2><p>{arrivalMode==='appointment'?'Chọn lịch hẹn để đối chiếu và cấp số tại quầy.':'20 hồ sơ gần đây. Tra cứu chính xác hoặc tạo hồ sơ cho khách mới.'}</p></div></div>
 <div className="desk-mode" aria-label="Hình thức tiếp nhận">{[['appointment','Đã đặt lịch'],['walk-in','Khách đến trực tiếp']].map(([id,label])=><button key={id} type="button" aria-pressed={arrivalMode===id} onClick={()=>{setArrivalMode(id);setPatient(null);setAppointment(null);setVisit(null);setCreatePatientOpen(false);setListQuery('');walkAttempt.current=null;newIntent.current=crypto.randomUUID();}}>{label}</button>)}</div>
 {arrivalMode==='appointment'?<>
 <label className="desk-search">Tìm lịch hẹn<input type="search" placeholder="Tên bệnh nhân hoặc mã lịch hẹn…" value={listQuery} onChange={e=>setListQuery(e.target.value)}/></label>
 <div className="desk-table-scroll"><table className="desk-table"><caption className="sr-only">Lịch hẹn trong ngày</caption><thead><tr><th>Giờ khám</th><th>Bệnh nhân</th><th>Trạng thái</th><th>Tiếp nhận</th></tr></thead><tbody>{appointments.filter(a=>matches(listQuery,a.patient?.fullName,a.appointmentCode)).map(a=><tr key={a.id} data-selected={appointment?.id===a.id}><td>{clockTime(a.startsAt)}</td><td><strong>{a.patient?.fullName??'Chưa có thông tin nhận diện'}</strong><small>{a.appointmentCode} · {dateLabel(a.patient?.dateOfBirth)}</small></td><td><span className="task-status" data-state={a.status}>{stateName(a.status)}</span></td><td><button type="button" className="button-secondary" disabled={appointmentAlreadyReceived(a)||a.status!=='CONFIRMED'||!a.patient} onClick={()=>{setAppointment(a);setPatient(null);setVisit(null);setExceptions([]);setReason('Tiếp nhận lịch hẹn tại quầy');checkAttempt.current=null;}}>{appointmentAlreadyReceived(a)?'Đã tiếp nhận':'Chọn lịch'}</button></td></tr>)}{!appointments.filter(a=>matches(listQuery,a.patient?.fullName,a.appointmentCode)).length&&<tr><td colSpan={4} className="desk-empty">Không có lịch hẹn phù hợp trong ngày này.</td></tr>}</tbody></table></div>
 </>:<>
 <div className="desk-patient-search"><label>Tên hoặc số điện thoại<input type="search" aria-label="Tên hoặc số điện thoại bệnh nhân" placeholder="Tên chính xác hoặc số điện thoại" value={name} onChange={e=>setName(e.target.value)}/></label><label>Ngày sinh (khi tra theo tên)<input aria-label="Ngày sinh tra cứu" type="date" value={dob} onChange={e=>setDob(e.target.value)}/></label><button type="button" className="button-secondary" onClick={()=>{setCreatePatientOpen(v=>!v);setReason('Tạo hồ sơ khách đến trực tiếp tại quầy');}}>{createPatientOpen?'Đóng biểu mẫu':'Tạo hồ sơ mới'}</button></div>
 {patientSearchError&&<p role="alert" className="booking-error">{patientSearchError}</p>}
 {name.trim()&&!dob&&!/^[+\d\s().-]{6,}$/.test(name.trim())&&<p role="status">Nhập thêm ngày sinh để tra cứu chính xác theo tên.</p>}
 {createPatientOpen&&<form className="desk-create" onSubmit={e=>{e.preventDefault();void run(async()=>{const input={fullName:createName.trim(),dateOfBirth:createDob||null,phone:createPhone.trim()||null,reason:'Tạo hồ sơ khách đến trực tiếp tại quầy'};const key=await stableOperationKey('provisional',{clinic:scope.clinic,branch,actorEmail:email,...input});const p=await api.provisional(scope,input,key);choosePatient(p);setPatients(current=>[p,...current.filter(x=>x.patientId!==p.patientId)]);setCreatePatientOpen(false);setCreateName('');setCreateDob('');setCreatePhone('');setMessage('Đã tạo hồ sơ. Đối chiếu thông tin trước khi tiếp nhận.');});}}><h3>Hồ sơ mới tại quầy</h3><label>Họ tên bệnh nhân<input required maxLength={180} value={createName} onChange={e=>setCreateName(e.target.value)}/></label><label>Ngày sinh<input type="date" max={localDate()} value={createDob} onChange={e=>setCreateDob(e.target.value)}/></label><label>Số điện thoại<input type="tel" maxLength={30} value={createPhone} onChange={e=>setCreatePhone(e.target.value)}/></label><button className="booking-primary" disabled={!createName.trim()}>Tạo và chọn hồ sơ</button></form>}
 <div className="desk-table-scroll"><table className="desk-table" aria-busy={patientSearchBusy}><caption className="sr-only">Hồ sơ bệnh nhân</caption><thead><tr><th>Bệnh nhân</th><th>Điện thoại</th><th>Hồ sơ</th><th>Thao tác</th></tr></thead><tbody>{patients.map(p=><tr key={p.patientId} data-selected={patient?.patientId===p.patientId}><td><strong>{p.fullName}</strong><small>{dateLabel(p.dateOfBirth)}</small><small className="desk-code">{p.patientCode}</small></td><td>{p.phoneLast4?'•••• '+p.phoneLast4:'Chưa ghi nhận'}</td><td><span className="task-status" data-state={p.status}>{stateName(p.status)}</span></td><td><button className="button-secondary" type="button" onClick={()=>choosePatient(p)}>Chọn hồ sơ</button></td></tr>)}{!patients.length&&<tr><td colSpan={4} className="desk-empty">{patientSearchBusy?'Đang tìm hồ sơ…':patientSearchError?'Chưa đọc được danh sách hồ sơ.':patientSearchDone?'Không tìm thấy hồ sơ phù hợp.':'Chưa có hồ sơ để hiển thị.'}</td></tr>}</tbody></table></div>
 </>}
 </section>
 {(patient||appointment)&&<aside className="desk-detail" aria-label="Xác nhận tiếp nhận"><div className="desk-detail-heading"><h2 ref={detailHeading} tabIndex={-1}>Xác nhận tiếp nhận</h2><button type="button" className="button-secondary" onClick={()=>{setPatient(null);setAppointment(null);setVisit(null);}}>Đóng</button></div><PatientIdentity patient={arrivalMode==='appointment'?appointment?.patient:patient}/>{appointment&&<p>Lịch {clockTime(appointment.startsAt)} · {appointment.appointmentCode}</p>}
 {visit?<div className="desk-issued" role="status"><span>{visit.ticket?'Đã cấp số':'Đang chờ xác nhận lượt đến'}</span><strong>{visit.ticket?.code??'Chờ xác nhận'}</strong><p>{visitStatus[visit.status]??visit.status}</p><button type="button" className="booking-primary" onClick={()=>setDeskTab('queue')}>Xem hàng đợi</button><button type="button" className="button-secondary" onClick={()=>void run(async()=>{if(!visit.appointmentId)await newWalkIn();setPatient(null);setAppointment(null);setVisit(null);checkAttempt.current=null;})}>Tiếp nhận khách tiếp theo</button></div>:<>
 {arrivalMode==='walk-in'&&<><label>Bác sĩ phụ trách<select aria-label="Bác sĩ phụ trách" value={doctor} onChange={e=>setDoctor(e.target.value)}><option value="">Chọn bác sĩ</option>{doctors.map(d=><option key={d.practitionerId} value={d.practitionerId}>{d.displayName}</option>)}</select></label><label>Dịch vụ bệnh nhân sử dụng<select aria-label="Dịch vụ bệnh nhân sử dụng" value={offering} onChange={e=>{const id=e.target.value;setOffering(id);setOfferingPrice(null);if(id)void run(async()=>setOfferingPrice((await api.offeringPrice(scope,id)).amountVnd));}}><option value="">Chọn dịch vụ</option>{offerings.map(o=><option key={o.offering.id} value={o.offering.id}>{o.offering.name}</option>)}</select></label>{offeringPrice!==null&&<p className="desk-price">Giá dịch vụ <strong>{formatVnd(offeringPrice)}</strong></p>}</>}
 <label>Phòng / khu vực tiếp nhận<select aria-label="Phòng hoặc khu vực tiếp nhận" value={point} onChange={e=>{const next=e.target.value;setPoint(next);setTickets(null);if(next)void run(()=>reloadQueue(0,next));}}><option value="">Chọn phòng / khu vực</option>{points.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
 <label>Lý do đến khám<textarea aria-label="Lý do đến khám" maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label>
 {patient?.status==='PROVISIONAL'&&<details><summary>Đối chiếu hồ sơ tạm</summary><label>Tham chiếu bằng chứng đối chiếu<input maxLength={180} value={evidence} onChange={e=>setEvidence(e.target.value)}/></label><button type="button" className="button-secondary" disabled={!evidence.trim()||!reason.trim()} onClick={()=>void run(async()=>{const p=await api.review(scope,patient,evidence,reason);setPatient(p);setPatients(rows=>rows.map(x=>x.patientId===p.patientId?p:x));})}>Ghi nhận đã xác minh</button></details>}
 <p className="muted-copy">Đối chiếu họ tên và ngày sinh trước khi cấp số. Dịch vụ cho biết bệnh nhân đến để sử dụng gì; phòng / khu vực cho biết nơi bệnh nhân chờ và được gọi. Thanh toán thực hiện tại mục Thu phí & ca thu.</p>
 <button type="button" className="booking-primary" disabled={!point||!reason.trim()||(arrivalMode==='walk-in'?(!patient||!doctor||!offering||offeringPrice===null):(!appointment?.patient||appointmentAlreadyReceived(appointment)))} onClick={()=>void run(arrivalMode==='walk-in'?arriveWalkIn:checkArrival)}>{arrivalMode==='appointment'&&appointment&&appointmentAlreadyReceived(appointment)?'Đã tiếp nhận & cấp số':'Tiếp nhận & cấp số'}</button>
 </>}
 {appointment&&<details className="task-disclosure"><summary>Xử lý đến muộn, không đến hoặc bác sĩ vắng</summary><p>Ngoại lệ được giữ để theo dõi. Bác sĩ vắng cần quyền quản lý; chưa có thao tác hoàn tiền tự động.</p><label>Loại ngoại lệ<select disabled={busy} value={exceptionType} onChange={e=>setExceptionType(e.target.value)}><option value="LATE">Đến muộn</option><option value="NO_SHOW">Không đến</option><option value="DOCTOR_ABSENT">Bác sĩ vắng</option></select></label><button className="button-secondary" disabled={busy||!reason.trim()||appointment.status!=='CONFIRMED'} onClick={()=>void run(async()=>{const key=await stableOperationKey('appointment-exception',{clinic:scope.clinic,branch,actorEmail:email,appointmentId:appointment.id,type:exceptionType,reason});const result=await api.recordException(scope,appointment,exceptionType,reason,key);setMessage('Đã ghi nhận ngoại lệ '+result.type+'. Cần theo dõi xử lý.');setExceptions(await api.exceptions(scope,appointment));setAppointments(await api.appointments(scope,date));})}>Ghi nhận ngoại lệ có lý do</button>{exceptions.map(x=><p key={x.id}>{stateName(x.type)} · {stateName(x.state)} · {x.notificationMode==='MANUAL_CONTACT_REQUIRED'?'Cần liên hệ bệnh nhân tại quầy':'Thông báo trong ứng dụng đang được giao'}</p>)}</details>}
 </aside>}
 </fieldset>}
 {deskTab==='queue'&&<section className="desk-list"><div className="desk-list-heading"><div><h2>Hàng đợi tại điểm phục vụ</h2><p>Gọi số và điều phối tại quầy. Trạng thái khám do bác sĩ cập nhật.</p></div></div><fieldset className="desk-queue-controls" disabled={busy||navigationPending}><label>Điểm phục vụ<select aria-label="Điểm phục vụ" value={point} onChange={e=>{const next=e.target.value;setPoint(next);setTickets(null);if(next)void run(()=>reloadQueue(0,next));}}><option value="">Chọn điểm phục vụ</option>{points.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Bác sĩ trong hàng đợi<select value={queueDoctor} onChange={e=>setQueueDoctor(e.target.value)}><option value="">Tất cả bác sĩ</option>{doctors.map(d=><option key={d.practitionerId} value={d.practitionerId}>{d.displayName}</option>)}</select></label><label>Tìm trong hàng đợi<input type="search" value={listQuery} onChange={e=>setListQuery(e.target.value)} placeholder="Tên bệnh nhân, số thứ tự…"/></label><label>Trạng thái<select value={queueFilter} onChange={e=>setQueueFilter(e.target.value)}><option value="">Tất cả trạng thái</option>{Object.entries(queueStates).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label></fieldset>
 {activeQueueTickets.map(active=><p className="desk-queue-note" role="status" key={active.id}><strong>{active.code}</strong> · {doctors.find(d=>d.practitionerId===active.doctorId)?.displayName??'Bác sĩ phụ trách'} · {active.state==='SERVING'?'đang khám.':'đã gọi, đang chờ vào khám.'} {active.state==='CALLED'?'Nếu bệnh nhân chưa có mặt, nhập lý do rồi dùng “Bỏ qua”; hàng đợi của bác sĩ khác vẫn hoạt động độc lập.':'Chỉ hàng đợi của chính bác sĩ này phải chờ lượt hiện tại kết thúc.'}</p>)}
 <details className="desk-routing"><summary>Lý do điều phối & chuyển phòng</summary><label>Lý do tiếp nhận hoặc điều phối<textarea disabled={busy||navigationPending} value={reason} maxLength={500} onChange={e=>setReason(e.target.value)}/></label><label>Chuyển đến điểm phục vụ<select disabled={busy||navigationPending} value={destination} onChange={e=>setDestination(e.target.value)}><option value="">Chọn đích chuyển</option>{points.filter(p=>p.active&&p.id!==point).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></details>
 <div className="desk-table-scroll"><table className="desk-table"><caption className="sr-only">Danh sách hàng đợi</caption><thead><tr><th>Số thứ tự</th><th>Bệnh nhân</th><th>Giờ đến / Bác sĩ</th><th>Trạng thái</th><th>Điều phối</th></tr></thead><tbody>{(tickets??[]).filter(t=>(!queueFilter||t.state===queueFilter)&&(!queueDoctor||t.doctorId===queueDoctor)&&matches(listQuery,t.code,t.patient?.fullName)).map(t=><tr key={t.id}><td><strong className="desk-token">{t.code}</strong></td><td><PatientIdentity patient={t.patient}/></td><td>{t.checkedInAt?clockTime(t.checkedInAt):'Chưa ghi nhận'}<small>{doctors.find(d=>d.practitionerId===t.doctorId)?.displayName??'Chưa có thông tin bác sĩ'}</small></td><td><span className="task-status" data-state={t.state}>{queueStates[t.state]??t.state}</span></td><td><div className="desk-row-actions">{['WAITING','CALLED','SKIPPED'].includes(t.state)&&<><button className="button-secondary" title={callTicketHint(t)} disabled={!canCallTicket(t)} onClick={()=>void run(()=>moveTicket(t,'call'))}>{t.state==='CALLED'?`Đã gọi ${t.code}`:t.state==='SKIPPED'?`Đã bỏ qua ${t.code}`:`Gọi ${t.code}`}</button><button className="button-secondary" disabled={busy||navigationPending||t.state==='SKIPPED'||!reason.trim()} onClick={()=>void run(()=>moveTicket(t,'skip'))}>Bỏ qua</button><button className="button-secondary" disabled={busy||navigationPending||!reason.trim()||!destination||destination===point} onClick={()=>void run(()=>moveTicket(t,'transfer'))}>Chuyển phòng</button></>}</div></td></tr>)}{!(tickets??[]).filter(t=>(!queueFilter||t.state===queueFilter)&&(!queueDoctor||t.doctorId===queueDoctor)&&matches(listQuery,t.code,t.patient?.fullName)).length&&<tr><td colSpan={5} className="desk-empty">{!point?'Chọn điểm phục vụ để xem hàng đợi.':tickets===null?'Đang đồng bộ hàng đợi…':'Không có bệnh nhân phù hợp trong hàng đợi.'}</td></tr>}</tbody></table></div></section>}
 {['recovery','operations'].includes(deskTab)&&<label>Lý do tiếp nhận hoặc điều phối<textarea disabled={busy||navigationPending} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label>}
 </>}
 {validScope&&<section hidden={deskTab!=='recovery'} className="public-section reception-recovery-tab"><h2 id="reception-recovery" tabIndex={-1}>Lịch sử tiếp nhận</h2><p>Các lượt bạn đã tiếp nhận trong ngày đã chọn. Tra cứu tại đây trước khi tạo lại một lượt đang chờ xác nhận.</p><WorklistTools query={recoveryQuery} onQuery={setRecoveryQuery} state={recoveryFilter} onState={setRecoveryFilter} states={visitStatus} disabled={busy} count={recoveries.filter(a=>(!recoveryFilter||a.visit.status===recoveryFilter)&&(!recoveryQuery||`${a.visit.patient?.fullName} ${a.visit.patient?.patientCode} ${dateLabel(a.visit.patient?.dateOfBirth)} ${a.visit.ticket?.code}`.toLocaleLowerCase('vi-VN').includes(recoveryQuery.toLocaleLowerCase('vi-VN')))).length} total={recoveries.length}/><div className="arrival-recoveries">{recoveries.filter(a=>(!recoveryFilter||a.visit.status===recoveryFilter)&&(!recoveryQuery||`${a.visit.patient?.fullName} ${a.visit.patient?.patientCode} ${dateLabel(a.visit.patient?.dateOfBirth)} ${a.visit.ticket?.code}`.toLocaleLowerCase('vi-VN').includes(recoveryQuery.toLocaleLowerCase('vi-VN')))).map(a=><article className="booking-appointment" key={a.visit.id}><h3>{a.visit.ticket?.code??(a.visit.status==='ARRIVAL_PENDING'?'Tiếp nhận lịch đang chờ xác nhận':'Lượt '+(visitStatus[a.visit.status]??a.visit.status).toLowerCase())}</h3><PatientIdentity patient={a.visit.patient}/><p>{a.operation==='walk-in'?'Khách đến trực tiếp':'Lịch đã đặt'} · {visitStatus[a.visit.status]??a.visit.status} · {new Intl.DateTimeFormat('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',timeStyle:'short'}).format(new Date(a.createdAt))}</p><button className="button-secondary" disabled={busy||!reason.trim()} onClick={()=>void run(async()=>{const v=await api.recoverArrival(scope,a.visit,reason);setVisit(v);setWalkRecovery(false);walkAttempt.current=null;setMessage('Đã xác nhận lượt tiếp nhận đã ghi · '+(v.ticket?.code??v.status));if(v.ticket){setPoint(v.ticket.servicePointId);const items=await readAllQueue(scope,v.ticket.servicePointId,date);setTickets(items);setNextQueue(null);}setRecoveries(await api.arrivals(scope,date));})}>{a.visit.status==='ARRIVAL_PENDING'?'Tiếp tục tiếp nhận lịch đang chờ':'Xác nhận kết quả lượt này'}</button></article>)}</div></section>}
 <div hidden={deskTab!=='operations'}>{canManage&&<section className="task-card">  <details><summary>Báo bác sĩ vắng theo khoảng lịch</summary><p>Quản trị báo vắng theo giờ Việt Nam. Khoảng vắng chặn đặt mới tại nguồn. Ghi ngoại lệ cho lịch đã đặt theo từng nhóm tối đa 10 lịch, thử lại phần chưa thành công; giữ lịch và giá đã chốt.</p><label>Bác sĩ báo vắng<select disabled={busy} value={doctor} onChange={e=>{setDoctor(e.target.value);setAbsences([]);}}><option value="">Chọn bác sĩ</option>{doctors.map(d=><option key={d.practitionerId} value={d.practitionerId}>{d.displayName}</option>)}</select></label><label>Bắt đầu vắng (giờ Việt Nam)<input type="datetime-local" disabled={busy} value={absenceStart} onChange={e=>setAbsenceStart(e.target.value)}/></label><label>Kết thúc vắng (giờ Việt Nam)<input type="datetime-local" disabled={busy} value={absenceEnd} onChange={e=>setAbsenceEnd(e.target.value)}/></label><button className="button-secondary" disabled={busy||!doctor||!absenceStart||!absenceEnd||!reason.trim()} onClick={()=>void run(reportDoctorAbsence)}>Ghi khoảng vắng có lý do</button>{absences.map(a=><article className="booking-appointment" key={a.id}><p>{new Date(a.startsAt).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'})} — {new Date(a.endsAt).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'})}</p><button className="button-secondary" disabled={busy} onClick={()=>void run(async()=>{const result=await api.applyAbsence(scope,a);setMessage(`Đã ghi ngoại lệ cho ${result.recorded} lịch. ${result.retryRequired.length} lịch cần kiểm tra và thử lại.${result.hasMore?' Còn lịch cần ghi ở nhóm tiếp theo.':' Đã hết nhóm lịch chưa ghi tại thời điểm tra cứu.'} Liên hệ bệnh nhân và theo dõi ngoại lệ đang mở.`);})}>Ghi ngoại lệ các lịch bị ảnh hưởng</button></article>)}</details>
 <details><summary>Cấu hình điểm phục vụ</summary><p>Quản trị được cấp quyền cấu hình điểm phục vụ.</p><form className="booking-form" onSubmit={e=>{e.preventDefault();void run(async()=>{await api.createPoint(scope,pointCode,pointName);setPoints(await api.points(scope));setMessage('Đã tạo điểm phục vụ.');});}}><label>Mã điểm phục vụ<input required pattern="[A-Z0-9]{1,8}" maxLength={8} disabled={busy} value={pointCode} onChange={e=>setPointCode(e.target.value.toUpperCase())}/></label><label>Tên điểm phục vụ<input required maxLength={100} disabled={busy} value={pointName} onChange={e=>setPointName(e.target.value)}/></label><button className="button-secondary" disabled={busy}>Tạo điểm phục vụ</button></form></details></section>}{validScope&&<AbsenceLifecyclePanel scope={scope} doctor={doctor} disabled={busy||walkRecovery||absenceRecovery||supervisorPending||queuePending} appointment={appointment} exceptions={exceptions} onPending={setLifecyclePending} canManage={canManage} active={deskTab==='operations'}/>}
 {validScope&&<SupervisorArrivalPanel scope={scope} disabled={busy||walkRecovery||absenceRecovery||lifecyclePending||queuePending} onPending={setSupervisorPending} canManage={canManage} active={deskTab==='operations'} onUpdated={async v=>{if(v.ticket){setPoint(v.ticket.servicePointId);const items=await readAllQueue(scope,v.ticket.servicePointId,date);setTickets(items);}}}/>}
 {validScope&&<OvernightQueuePanel scope={scope} tickets={tickets??[]} onPending={setQueuePending} disabled={busy||walkRecovery||absenceRecovery||lifecyclePending||supervisorPending} onMoved={async()=>{const today=localDate();setDate(today);await loadDay(today);}}/>}
 </div></section>;
}








