import {PatientIdentity} from './PatientIdentity';
import {useEffect,useRef,useState} from 'react';
import * as api from '../api/reception';
import {RequestError} from '../api/booking';
import {stableOperationKey} from '../api/idempotency';
type Attempt={scope:api.Scope;visit:api.Visit;body:{expectedVersion:number;reason:string};key:string};
export function SupervisorArrivalPanel({scope,canManage,onPending,disabled=false,active=false,onUpdated}:{scope:api.Scope;canManage:boolean;onPending:(v:boolean)=>void;disabled?:boolean;active?:boolean;onUpdated?:(visit:api.Visit)=>Promise<void>}){
 const [rows,setRows]=useState<api.Visit[]>([]),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[unknown,setUnknown]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');const running=useRef(false),epoch=useRef(0),attempt=useRef<Attempt|null>(null);
 useEffect(()=>{epoch.current++;setRows([]);setError('');setMessage('');setBusy(false);setUnknown(false);attempt.current=null;running.current=false;return()=>{epoch.current++;};},[scope.token,scope.clinic,scope.branch]);
 async function read(){if(running.current||unknown||disabled)return;const generation=epoch.current;running.current=true;setBusy(true);setError('');setRows([]);try{const all:api.Visit[]=[];let cursor:string|undefined;do{const result=await api.pendingArrivals(scope,cursor);if(generation!==epoch.current)return;all.push(...result.items);cursor=result.nextAfter??undefined;}while(cursor);if(generation===epoch.current)setRows(all);}catch(e){if(generation===epoch.current)setError(e instanceof Error?e.message:'Chưa đọc được lượt chờ.');}finally{if(generation===epoch.current){running.current=false;setBusy(false);}}}
 useEffect(()=>{if(active&&canManage)void read();},[active,canManage,scope.token,scope.clinic,scope.branch]);
 async function recover(visit?:api.Visit){if(running.current||disabled||!canManage)return;const generation=epoch.current;running.current=true;setBusy(true);setError('');onPending(true);
  try{if(!attempt.current){if(!visit)return;const captured={...scope},body={expectedVersion:visit.version,reason:reason.trim()};attempt.current={scope:captured,visit:{...visit},body,key:await stableOperationKey('supervisor-arrival',{clinic:scope.clinic,branch:scope.branch,id:visit.id,...body})};}if(generation!==epoch.current)return;setUnknown(true);const original=attempt.current!,result=await api.superviseArrival(original.scope,original.visit,original.body,original.key);if(generation!==epoch.current)return;attempt.current=null;setUnknown(false);onPending(false);setRows(old=>old.filter(v=>v.id!==result.id));setMessage('Đã đối chiếu và phục hồi cùng lượt. Hàng đợi đã được đồng bộ.');await onUpdated?.(result);}
  catch(e){if(generation!==epoch.current)return;if(e instanceof RequestError&&e.status>=400&&e.status<500){attempt.current=null;setUnknown(false);onPending(false);}else setUnknown(true);setError(e instanceof Error?e.message:'Chưa xác định được kết quả phục hồi.');}
  finally{if(generation===epoch.current){running.current=false;setBusy(false);if(!attempt.current)onPending(false);}}
 }
 if(!canManage)return null;
 return <section className="booking-appointment supervisor-arrival-panel" aria-label="Quản lý phục hồi tiếp nhận"><h3>Lượt tiếp nhận đang chờ xác nhận</h3><p>Quản lý đối chiếu nguồn và tiếp tục cùng lượt khi nhân viên đã rời ca. Nguồn sai hoặc bác sĩ còn vắng cần được xử lý trước.</p>{busy&&<p role="status">Đang đối chiếu tiếp nhận…</p>}{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 {unknown&&<><p>Kết quả chưa rõ. Giữ yêu cầu gốc và thử lại, không tạo lượt thay thế.</p><button className="button-secondary" type="button" disabled={busy||disabled} onClick={()=>void recover()}>Thử lại phục hồi đang chờ</button></>}
 <fieldset className="reception-actions configuration-fields" disabled={busy||unknown||disabled}><legend>Đối chiếu lượt</legend><label>Lý do quản lý phục hồi tiếp nhận<textarea maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label>{rows.map(visit=><article key={visit.id}><PatientIdentity patient={visit.patient}/><p>Đang chờ xác nhận lịch đến khám</p><button className="button-secondary" type="button" disabled={!reason.trim()} onClick={()=>void recover(visit)}>Phục hồi lượt {visit.id}</button></article>)}</fieldset></section>;
}
