import { requestJson } from './client';
import { unwrap } from './booking';
import type { Scope,Directory } from './reception';
const billing=import.meta.env.VITE_BILLING_V2_URL??'/s1/billing',clinic=import.meta.env.VITE_CLINIC_V2_URL??'/s1/clinic',encounter=import.meta.env.VITE_ENCOUNTER_V2_URL??'/s1/encounter',identity=import.meta.env.VITE_IDENTITY_V2_URL??'/s1/identity';
const path=(s:Scope)=>`/api/v2/clinics/${encodeURIComponent(s.clinic)}/branches/${encodeURIComponent(s.branch)}`;
const get=<T,>(url:string,token:string)=>unwrap(requestJson<T>(url,{headers:{Authorization:`Bearer ${token}`}}));
const post=<T,>(s:Scope,p:string,body:unknown,key:string)=>unwrap(requestJson<T>(billing+path(s)+p,{method:'POST',headers:{Authorization:`Bearer ${s.token}`,'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify(body)}));
export type Bill={id:string;encounterId:string;patientId:string;currency:string;subtotalVnd:number;adjustmentVnd:number;paidVnd:number;remainingVnd:number;status:string;version:number;lines:{chargeId:string;sourceType:string;sourceId:string;name:string;amountVnd:number}[]};
export type Receipt={id:string;billId:string;shiftId:string;collectorUserId:string;amountVnd:number;currency:string;method:string;externalRef:string|null;receiptCode:string;createdAt:string;label:string};
export type Shift={id:string;collectorUserId:string;state:string;version:number;expectedCashVnd:number|null;expectedBankVnd:number|null;expectedPosVnd:number|null;declaredCashVnd:number|null;declaredBankVnd:number|null;declaredPosVnd:number|null;varianceVnd:number|null;approvedBy:string|null};
export type Billable={id:string;patientId:string;appointmentId:string|null;status:string;medicalCaseVersion:number;visitCode?:string;checkedInAt?:string|null};
export const directory=(token:string,id:string)=>get<Directory>(clinic+`/api/v2/clinics/${id}/billing-directory`,token);
export const current=(token:string)=>get<{userId:string}>(identity+'/api/v2/me/current',token);
export const visits=(s:Scope)=>get<Billable[]>(encounter+path(s)+'/billable-visits',s.token);
export const bills=(s:Scope)=>get<Bill[]>(billing+path(s)+'/bills',s.token);
export const shifts=(s:Scope)=>get<Shift[]>(billing+path(s)+'/collection-shifts',s.token);
export const receipts=(s:Scope,id:string)=>get<Receipt[]>(billing+path(s)+`/bills/${id}/payments`,s.token);
export type NotificationState={pending:number;delivered:number;manualContact:number;failed:number};
export const notificationState=(s:Scope,id:string)=>get<NotificationState>(billing+path(s)+`/bills/${id}/notification-deliveries`,s.token);
export const retryNotifications=(s:Scope,id:string,reason:string,key:string)=>post<NotificationState>(s,`/bills/${id}/notification-deliveries/retry`,{reason},key);
export type ChargeEventState={eventId:string;status:string;attempts:number;lastError:string|null;kind?:string};
export type ChargeSyncState={events:ChargeEventState[];chargeCount?:number};
export const chargeState=(s:Scope,id:string)=>get<ChargeSyncState>(billing+path(s)+`/encounters/${id}/source-charges`,s.token);
export const deliveryState=(s:Scope,id:string,producer:'medical'|'encounter')=>get<ChargeSyncState>(`/s1/${producer}`+path(s)+`/encounters/${id}/billing-deliveries`,s.token);
export const retryCharge=(s:Scope,id:string,eventId:string,reason:string,key:string,source:'billing'|'medical'|'encounter')=>unwrap(requestJson<ChargeSyncState>(`/s1/${source}`+path(s)+`/encounters/${id}/${source==='billing'?'source-charges':'billing-deliveries'}/${eventId}/retry`,{method:'POST',headers:{Authorization:`Bearer ${s.token}`,'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify({reason})}));
export const issue=(s:Scope,encounterId:string,reason:string,key:string)=>post<Bill>(s,'/bills',{encounterId,reason},key);
export const open=(s:Scope,reason:string,key:string)=>post<Shift>(s,'/collection-shifts',{reason},key);
export const collect=(s:Scope,id:string,body:{expectedVersion:number;shiftId:string;amountVnd:number;method:string;externalRef:string|null;reason:string},key:string)=>post<Receipt>(s,`/bills/${id}/payments`,body,key);
export const adjust=(s:Scope,id:string,body:{expectedVersion:number;amountVnd:number;reason:string},key:string)=>post<Bill>(s,`/bills/${id}/adjustments`,body,key);
export const submit=(s:Scope,id:string,body:{expectedVersion:number;declaredCashVnd:number;declaredBankVnd:number;declaredPosVnd:number;reason:string},key:string)=>post<Shift>(s,`/collection-shifts/${id}/submit`,body,key);
export const approve=(s:Scope,id:string,version:number,reason:string,key:string)=>post<Shift>(s,`/collection-shifts/${id}/approve`,{expectedVersion:version,reason},key);
