import { requestJson } from './client';
import { unwrap,RequestError } from './booking';
import type { ClinicBranchView, ClinicOwnerView,CurrentActor } from '../types/contracts';
const bases={clinic:import.meta.env.VITE_CLINIC_V2_URL??'/s1/clinic',identity:import.meta.env.VITE_IDENTITY_V2_URL??'/s1/identity',doctor:import.meta.env.VITE_DOCTOR_V2_URL??'/s1/doctor',catalog:import.meta.env.VITE_CATALOG_V2_URL??'/s1/catalog'};
export type Session={token:string;clinic:string};
export type Scope=Session&{branch:string};
export type License={licenseNumber:string|null;issuingAuthority:string|null;scopeSummary:string|null;evidenceRef:string|null;validUntil:string|null};
export type Clinic=ClinicOwnerView&{contactName:string|null;contactEmail:string|null;contactPhone:string|null;license:License|null;version:number};
export type Draft={name:string;slug:string;publicDescription:string;contactName:string;contactEmail:string;contactPhone:string;license:License;expectedVersion?:number};
export type Membership={id:string;userId:string;clinicId:string;role:string;status:string;allBranches:boolean;version:number;branchIds:string[]};
export type Affiliation={id:string;practitionerId:string;userId:string;displayName:string;registrationCode:string|null;specialtyCode:string;specialtyName:string;professionalTitle:string|null;effectiveFrom:string;effectiveUntil:string|null;active:boolean;publicVisible:boolean;version:number};
export type Schedule={id:string;dayOfWeek:number;startTime:string;endTime:string;effectiveFrom:string;effectiveUntil:string|null;timezone:string;active:boolean;version:number};
export type Offering={id:string;code:string;name:string;description:string|null;specialtyCode:string|null;active:boolean;version:number};
export type Assignment={id:string;offering:Offering;durationMinutes:number;active:boolean;publicVisible:boolean;version:number};
export type Price={id:string;amountVnd:number;currency:string;effectiveFrom:string;taxPolicyCode:string|null;discountPolicyCode:string|null};
const clinicPath=(s:Session)=>`/api/v2/clinics/${encodeURIComponent(s.clinic)}`;
const branchPath=(s:Scope)=>clinicPath(s)+`/branches/${encodeURIComponent(s.branch)}`;
const get=<T,>(base:string,path:string,token:string)=>unwrap(requestJson<T>(base+path,{headers:{Authorization:`Bearer ${token}`}}));
const write=<T,>(base:string,path:string,token:string,body:unknown,method='POST')=>unwrap(requestJson<T>(base+path,{method,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)}));
export const mine=(token:string)=>get<Clinic[]>(bases.clinic,'/api/v2/clinics/mine',token);
export const current=(token:string)=>get<CurrentActor>(bases.identity,'/api/v2/me/current',token);
export const bootstrap=async(s:Session)=>{const result=await requestJson<void>(bases.clinic+clinicPath(s)+'/owner-membership',{method:'POST',headers:{Authorization:`Bearer ${s.token}`}});if(!result.ok)throw new RequestError(result.message??'Không thể liên kết quyền chủ cơ sở.',result.status);};
export const ownInvitations=(token:string)=>get<Membership[]>(bases.identity,'/api/v2/me/invitations',token);
export const acceptInvitation=(token:string,m:string)=>write<Membership>(bases.identity,`/api/v2/memberships/${encodeURIComponent(m)}/activate`,token,{});
export const revokeSession=(token:string)=>write<{version:number;invalidBefore:string}>(bases.identity,'/api/v2/sessions/revoke-current',token,{});
export const clinic=(s:Session)=>get<Clinic>(bases.clinic,clinicPath(s),s.token);
export const createClinic=(token:string,draft:Draft)=>write<Clinic>(bases.clinic,'/api/v2/clinics',token,draft);
export const saveClinic=(s:Session,draft:Draft)=>write<Clinic>(bases.clinic,clinicPath(s),s.token,draft,'PUT');
export const saveBranch=(s:Session,branch:Omit<ClinicBranchView,'id'>&{expectedVersion?:number},id?:string)=>write<Clinic>(bases.clinic,clinicPath(s)+'/branches'+(id?'/'+encodeURIComponent(id):''),s.token,branch,id?'PUT':'POST');
export const submitClinic=(s:Session)=>write<Clinic>(bases.clinic,clinicPath(s)+'/submit',s.token,{});
export const memberships=(s:Session)=>get<Membership[]>(bases.identity,clinicPath(s)+'/memberships',s.token);
export const invite=(s:Session,userId:string,role:string,allBranches:boolean,reason:string)=>write<Membership>(bases.identity,clinicPath(s)+'/memberships',s.token,{userId,role,allBranches,reason});
export const grant=(s:Session,m:Membership,branchId:string,reason:string)=>write<Membership>(bases.identity,clinicPath(s)+`/memberships/${m.id}/branches`,s.token,{branchId,reason});
export const revokeGrant=(s:Session,m:Membership,branch:string,reason:string)=>write<Membership>(bases.identity,clinicPath(s)+`/memberships/${m.id}/branches/${branch}/revoke`,s.token,{reason});
export const revoke=(s:Session,m:Membership,reason:string)=>write<Membership>(bases.identity,clinicPath(s)+`/memberships/${m.id}/revoke`,s.token,{reason});
export const affiliations=(s:Scope)=>get<Affiliation[]>(bases.doctor,branchPath(s)+'/doctor-affiliations',s.token);
export const saveAffiliation=(s:Scope,body:unknown,id?:string)=>write<Affiliation>(bases.doctor,branchPath(s)+'/doctor-affiliations'+(id?'/'+id:''),s.token,body,id?'PUT':'POST');
export const schedules=(s:Scope,a:string)=>get<{affiliation:Affiliation;schedules:Schedule[]}>(bases.doctor,branchPath(s)+`/doctor-affiliations/${a}/schedules`,s.token);
export const saveSchedule=(s:Scope,a:string,body:unknown,id?:string)=>write<Schedule>(bases.doctor,branchPath(s)+`/doctor-affiliations/${a}/schedules`+(id?'/'+id:''),s.token,body,id?'PUT':'POST');
export const offerings=(s:Session)=>get<Offering[]>(bases.catalog,clinicPath(s)+'/offerings',s.token);
export const saveOffering=(s:Session,body:unknown,id?:string)=>write<Offering>(bases.catalog,clinicPath(s)+'/offerings'+(id?'/'+id:''),s.token,body,id?'PUT':'POST');
export const assignments=(s:Scope)=>get<Assignment[]>(bases.catalog,branchPath(s)+'/offerings',s.token);
export const saveAssignment=(s:Scope,body:unknown,id?:string)=>write<Assignment>(bases.catalog,branchPath(s)+'/offerings'+(id?'/'+id:''),s.token,body,id?'PUT':'POST');
export const prices=(s:Scope,o:string)=>get<Price[]>(bases.catalog,branchPath(s)+`/offerings/${o}/price-versions`,s.token);
export const addPrice=(s:Scope,body:{offeringId:string;amountVnd:number;effectiveFrom:string})=>write<Price>(bases.catalog,branchPath(s)+'/price-versions',s.token,body);
