import { requestJson } from './client';
import { unwrap } from './booking';
import type { IamContextView } from '../types/contracts';
export type Directory={id:string;name:string;branches:{id:string;name:string;active:boolean}[]};
export type Patient={patientId:string;clinicPatientLinkId:string;patientCode:string;fullName:string;dateOfBirth:string|null;phoneLast4:string|null;status:string;version:number};
export type Point={id:string;code:string;name:string;active:boolean};
export type Ticket={id:string;visitId:string;servicePointId:string;date:string;number:number;code:string;state:string;version:number};
export type Visit={id:string;appointmentId:string|null;status:string;version:number;ticket:Ticket|null};
export type ArrivalRecovery={operation:string;createdAt:string;visit:Visit};
export type Absence={id:string;doctorId:string;startsAt:string;endsAt:string;state?:'ACTIVE'|'CANCELLED';version?:number};
export type AbsenceBatch={recorded:number;retryRequired:string[];hasMore:boolean};
export type Appointment={id:string;appointmentCode:string;patientId:string;startsAt:string;status:string;version?:number};
export type Exception={id:string;appointmentId:string;type:string;state:string;notificationMode:string};
export type Doctor={practitionerId:string;displayName:string;active:boolean;effectiveFrom:string;effectiveUntil:string|null};
const bases={identity:import.meta.env.VITE_IDENTITY_V2_URL??'/s1/identity',clinic:import.meta.env.VITE_CLINIC_V2_URL??'/s1/clinic',doctor:import.meta.env.VITE_DOCTOR_V2_URL??'/s1/doctor',patient:import.meta.env.VITE_PATIENT_V2_URL??'/s1/patient',encounter:import.meta.env.VITE_ENCOUNTER_V2_URL??'/s1/encounter'};
export type Scope={token:string;clinic:string;branch:string};
const path=(s:Scope)=>`/api/v2/clinics/${encodeURIComponent(s.clinic)}/branches/${encodeURIComponent(s.branch)}`;
const get=<T,>(base:string,p:string,token:string)=>unwrap(requestJson<T>(base+p,{headers:{Authorization:`Bearer ${token}`}}));
const post=<T,>(base:string,p:string,s:Scope,body:unknown,key?:string)=>unwrap(requestJson<T>(base+p,{method:'POST',headers:{Authorization:`Bearer ${s.token}`,'Content-Type':'application/json',...(key?{'Idempotency-Key':key}:{})},body:JSON.stringify(body)}));
export const contexts=(token:string)=>get<IamContextView[]>(bases.identity,'/api/v2/me/contexts',token);
export const directory=(token:string,clinic:string)=>get<Directory>(bases.clinic,`/api/v2/clinics/${encodeURIComponent(clinic)}/reception-directory`,token);
export const doctors=(s:Scope)=>get<Doctor[]>(bases.doctor,path(s)+'/doctor-affiliations',s.token);
export const points=(s:Scope)=>get<Point[]>(bases.encounter,path(s)+'/service-points',s.token);
export const createPoint=(s:Scope,code:string,name:string)=>post<Point>(bases.encounter,path(s)+'/service-points',s,{code,name});
export const suggestions=(s:Scope,name:string,dateOfBirth:string,phone:string)=>get<Patient[]>(bases.patient,path(s)+'/patients/match-suggestions?'+new URLSearchParams({name,...(dateOfBirth?{dateOfBirth}:{}),phone}),s.token);
export const provisional=(s:Scope,body:{fullName:string;dateOfBirth:string|null;phone:string|null;reason:string},key:string)=>post<Patient>(bases.patient,path(s)+'/patients/walk-in',s,body,key);
export const review=(s:Scope,p:Patient,evidence:string,reason:string)=>post<Patient>(bases.patient,path(s)+`/patients/${p.patientId}/review`,s,{expectedVersion:p.version,identityEvidenceRef:evidence,reason});
export const appointments=(s:Scope,date:string)=>get<Appointment[]>(bases.encounter,path(s)+'/reception/appointments?'+new URLSearchParams({date}),s.token);
export const arrivals=(s:Scope,date:string)=>get<ArrivalRecovery[]>(bases.encounter,path(s)+'/reception/arrivals?'+new URLSearchParams({date}),s.token);
export const recoverArrival=(s:Scope,v:Visit,reason:string)=>post<Visit>(bases.encounter,path(s)+`/reception/arrivals/${v.id}/recover`,s,{expectedVersion:v.version,reason});
export const walkIn=(s:Scope,patientId:string,doctorId:string,servicePointId:string,reason:string,key:string)=>post<Visit>(bases.encounter,path(s)+'/visits/walk-in',s,{patientId,doctorId,servicePointId,reason},key);
export const checkIn=(s:Scope,a:Appointment,patientId:string,servicePointId:string,reason:string,key:string)=>post<Visit>(bases.encounter,path(s)+`/appointments/${a.id}/check-in`,s,{patientId,servicePointId,reason},key);
export const queue=(s:Scope,point:string,date:string)=>get<Ticket[]>(bases.encounter,path(s)+'/queue?'+new URLSearchParams({servicePointId:point,date}),s.token);
export type QueuePage={items:Ticket[];nextAfterNumber:number|null};
export const queuePage=(s:Scope,point:string,date:string,afterNumber=0)=>get<QueuePage>(bases.encounter,path(s)+'/queue/page?'+new URLSearchParams({servicePointId:point,date,afterNumber:String(afterNumber),limit:'50'}),s.token);
export type PendingPage={items:Visit[];nextAfter:string|null};
export const pendingArrivals=(s:Scope,after?:string)=>get<PendingPage>(bases.encounter,path(s)+'/reception/pending-arrivals?'+new URLSearchParams({limit:'25',...(after?{after}:{})}),s.token);
export const superviseArrival=(s:Scope,visit:Visit,body:{expectedVersion:number;reason:string},key:string)=>post<Visit>(bases.encounter,path(s)+`/reception/pending-arrivals/${visit.id}/recover`,s,body,key);
export const rollForward=(s:Scope,ticket:Ticket,body:{expectedVersion:number;reason:string;destinationPointId?:string},key:string)=>post<Ticket>(bases.encounter,path(s)+`/queue/${ticket.id}/roll-forward`,s,body,key);
export const move=(s:Scope,t:Ticket,action:'call'|'skip'|'transfer',reason:string,destination?:string)=>post<Ticket>(bases.encounter,path(s)+`/queue/${t.id}/${action}`,s,{expectedVersion:t.version,reason,...(destination?{destinationPointId:destination}:{})});
export const exceptions=(s:Scope,a:Appointment)=>get<Exception[]>(bases.encounter,path(s)+`/appointments/${a.id}/exceptions`,s.token);
export const recordException=(s:Scope,a:Appointment,type:string,reason:string,key:string)=>post<Exception>(bases.encounter,path(s)+`/appointments/${a.id}/exceptions`,s,{type,reason},key);
export const doctorAbsences=(s:Scope,doctor:string)=>get<Absence[]>(bases.doctor,path(s)+`/doctors/${doctor}/absences`,s.token);
export const reportAbsence=(s:Scope,doctor:string,body:{startsAt:string;endsAt:string;reason:string},key:string)=>post<Absence>(bases.doctor,path(s)+`/doctors/${doctor}/absences`,s,body,key);
export const applyAbsence=(s:Scope,a:Absence)=>post<AbsenceBatch>(bases.encounter,path(s)+`/doctor-absences/${a.id}/apply`,s,{});
export type AbsenceChange={previous:Absence;replacement:Absence|null};
export const changeAbsence=(s:Scope,a:Absence,operation:'cancel'|'amend',body:{expectedVersion:number;reason:string;startsAt?:string;endsAt?:string},key:string)=>post<AbsenceChange>(bases.doctor,path(s)+`/doctors/${a.doctorId}/absences/${a.id}/${operation}`,s,body,key);
export const resolveException=(s:Scope,a:Appointment,e:Exception,body:{expectedVersion:number;reason:string},key:string)=>post<Exception>(bases.encounter,path(s)+`/appointments/${a.id}/exceptions/${e.id}/resolve`,s,body,key);
