import {usePanelSession} from '../auth/SessionProvider';
import {SourceSessionState} from '../auth/SourceSessionState';
import { useEffect,useRef,useState } from 'react';
import { signIn } from '../api/booking';
import { contexts } from '../api/reception';
import * as api from '../api/configuration';
import type { CurrentActor,IamContextView } from '../types/contracts';
type Account={actor:CurrentActor;contexts:IamContextView[];invitations:api.Membership[]};
export function AccountSettingsPanel(){
 const shared=usePanelSession(login);
 const [token,setToken]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[account,setAccount]=useState<Account|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const epoch=useRef(0),locked=useRef(false);
 useEffect(()=>()=>{epoch.current++;},[]);
 const read=async(access:string):Promise<Account>=>{const [actor,grants,invitations]=await Promise.all([api.current(access),contexts(access),api.ownInvitations(access)]);return {actor,contexts:grants,invitations};};
 function logout(){epoch.current++;locked.current=false;setToken('');setAccount(null);setPassword('');setBusy(false);setError('');setNotice('');}
 async function login(){if(locked.current)return;locked.current=true;setBusy(true);setError('');const current=++epoch.current;try{const access=shared?.session?.token??(await signIn(email,password)).data.accessToken;setEmail(shared?.session?.email??email);setPassword('');const data=await read(access);if(current===epoch.current){setToken(access);setAccount(data);}}catch(e){if(current===epoch.current){setToken('');setAccount(null);setError(e instanceof Error?e.message:'Không thể đọc tài khoản.');}}finally{if(current===epoch.current){locked.current=false;setBusy(false);}}}
 async function refresh(){if(locked.current)return;locked.current=true;setBusy(true);setAccount(null);setError('');const current=epoch.current;try{const data=await read(token);if(current===epoch.current)setAccount(data);}catch(e){if(current===epoch.current)setError(e instanceof Error?e.message:'Không thể đối chiếu tài khoản.');}finally{if(current===epoch.current){locked.current=false;setBusy(false);}}}
 async function accept(invitation:api.Membership){if(locked.current)return;locked.current=true;setBusy(true);setError('');setNotice('');const current=epoch.current;try{await api.acceptInvitation(token,invitation.id);const data=await read(token);if(current===epoch.current){setAccount(data);setNotice('Đã chấp nhận lời mời. Mở luồng vận hành phù hợp với quyền được cấp.');}}catch(e){if(current===epoch.current){setAccount(null);setError(e instanceof Error?e.message:'Chưa xác nhận được việc chấp nhận lời mời.');setNotice('Tải lại quyền và lời mời tại nguồn trước khi thao tác tiếp.');}}finally{if(current===epoch.current){locked.current=false;setBusy(false);}}}
 async function revoke(){if(locked.current)return;locked.current=true;setBusy(true);setError('');const current=epoch.current;try{await api.revokeSession(token);if(current===epoch.current){logout();shared?.signOut('Đã thu hồi các phiên hiện tại. Vui lòng đăng nhập lại.');setNotice('Đã thu hồi các phiên hiện tại. Vui lòng đăng nhập lại.');}}catch(e){if(current===epoch.current){logout();setError(e instanceof Error?e.message:'Chưa xác nhận được kết quả thu hồi phiên.');}}finally{if(current===epoch.current){locked.current=false;setBusy(false);}}}
 return <section className="booking-panel reception-panel doctor-panel configuration-panel"><h1>Cài đặt tài khoản</h1><p>Quyền phòng khám và lời mời được xác minh từ Identity.</p>{busy&&<p role="status">Đang đối chiếu tài khoản…</p>}{error&&<p role="alert" className="booking-error">{error}</p>}{notice&&<p role="status">{notice}</p>}{!token&&shared?<SourceSessionState error={error} retry={()=>void login()}/>:!token?<form className="booking-form" onSubmit={e=>{e.preventDefault();void login();}}><label>Email tài khoản<input type="email" required autoComplete="username" disabled={busy} value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Mật khẩu tài khoản<input type="password" required autoComplete="current-password" disabled={busy} value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="booking-primary" disabled={busy}>Đăng nhập tài khoản</button></form>:<>{!shared&&<button onClick={logout}>Đăng xuất tài khoản</button>}<button disabled={busy} onClick={()=>void refresh()}>Tải lại quyền và lời mời</button><button disabled={busy} onClick={()=>void revoke()}>Thu hồi phiên hiện tại</button>{account&&<><h2>Tài khoản của tôi</h2><p>Mã tài khoản dùng khi nhận lời mời: <code>{account.actor.userId}</code></p><h2>Lời mời của tôi</h2>{!account.invitations.length&&<p>Không có lời mời đang chờ.</p>}{account.invitations.map(m=><article className="booking-appointment" key={m.id}><p>Phòng khám: {m.clinicId} · Vai trò: {m.role}</p><p>{m.allBranches?'Tất cả địa điểm của phòng khám':`${m.branchIds.length} địa điểm đã cấp quyền`}</p><button disabled={busy} onClick={()=>void accept(m)}>Chấp nhận lời mời {m.role}</button></article>)}<h2>Quyền đang hoạt động</h2>{!account.contexts.length&&<p>Chưa có quyền vận hành phòng khám.</p>}<ul>{account.contexts.map(m=><li key={m.membershipId}>{m.role} · Phòng khám {m.clinicId} · {m.allBranches?'Tất cả địa điểm':`${m.branchIds.length} địa điểm`}</li>)}</ul><p>Ký/phát hành hồ sơ khám và thanh toán online đang chưa bật.</p></>}</>}</section>;
}
