import {usePanelSession,useSessionBranch} from '../auth/SessionProvider';
import {SourceSessionState} from '../auth/SourceSessionState';
import { useRef,useState } from 'react';
import * as api from '../api/billing';
import { contexts,type Directory,type Scope } from '../api/reception';
import { signIn,RequestError } from '../api/booking';
import { stableOperationKey } from '../api/idempotency';
import { CashierNotificationPanel } from './CashierNotificationPanel';
import { ChargeSyncPanel } from './ChargeSyncPanel';
import { useNavigationLock } from './useNavigationLock';
const money=(v:number)=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(v);
const methodName:Record<string,string>={CASH:'Tiền mặt',BANK_TRANSFER:'Chuyển khoản tại quầy',POS:'POS tại quầy'};
export function CashierPanel({onClinic,onNavigationLock}:{onClinic?:(name:string)=>void;onNavigationLock?:(reason:string|null)=>void}){
 const shared=usePanelSession(()=>run(login));
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[token,setToken]=useState(''),[actor,setActor]=useState(''),[role,setRole]=useState('');
 const [directory,setDirectory]=useState<Directory|null>(null),[branch,setBranch]=useState(''),[visits,setVisits]=useState<api.Billable[]>([]),[bills,setBills]=useState<api.Bill[]>([]),[shifts,setShifts]=useState<api.Shift[]>([]);
 const [visitId,setVisitId]=useState(''),[billId,setBillId]=useState(''),[shiftId,setShiftId]=useState(''),[receipts,setReceipts]=useState<api.Receipt[]>([]),[printed,setPrinted]=useState<api.Receipt|null>(null);
 const [reason,setReason]=useState(''),[amount,setAmount]=useState(''),[method,setMethod]=useState('CASH'),[reference,setReference]=useState(''),[cash,setCash]=useState('0'),[bank,setBank]=useState('0'),[pos,setPos]=useState('0');
 const [busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[stale,setStale]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 useNavigationLock(uncertain?'Thử lại thu phí đang chờ để xác minh kết quả trước khi rời màn hình.':busy?'Đợi thao tác thu phí xử lý xong trước khi rời màn hình.':null,onNavigationLock);
 const running=useRef(false),pending=useRef<(()=>Promise<void>)|null>(null);const scope:Scope={token,clinic:directory?.id??'',branch};const bill=bills.find(x=>x.id===billId),shift=shifts.find(x=>x.id===shiftId),manager=['CLINIC_OWNER','CLINIC_MANAGER'].includes(role);
 async function run(action:()=>Promise<void>){if(running.current)return;running.current=true;setBusy(true);setError('');setMessage('');try{await action();}catch(e){setError(e instanceof Error?e.message:'Chưa xác định kết quả thu phí');}finally{running.current=false;setBusy(false);}}
 async function login(){let auth:string;try{auth=shared?.session?.token??(await signIn(email,password)).data.accessToken;setEmail(shared?.session?.email??email);}finally{setPassword('');}const memberships=await contexts(auth);const ids=[...new Set(memberships.filter(m=>['CASHIER','CLINIC_MANAGER','CLINIC_OWNER'].includes(m.role)).map(m=>m.clinicId))];const requested=new URLSearchParams(location.search).get('clinicId');const id=requested?(ids.includes(requested)?requested:null):ids.length===1?ids[0]:null;if(!id)throw new Error('Cần quyền thu phí tại một phòng khám. Dùng đường dẫn Workspace được cấp nếu làm việc tại nhiều phòng khám.');const [d,me]=await Promise.all([api.directory(auth,id),api.current(auth)]);setToken(auth);setDirectory(d);setActor(me.userId);setRole(['CLINIC_OWNER','CLINIC_MANAGER','CASHIER'].find(r=>memberships.some(m=>m.clinicId===id&&m.role===r))!);onClinic?.(d.name);}
 async function load(s=scope){const [v,b,h]=await Promise.all([api.visits(s),api.bills(s),api.shifts(s)]);setVisits(v);setBills(b);setShifts(h);if(billId)setReceipts(await api.receipts(s,billId));setStale(false);}
 useSessionBranch(shared,token,directory,branch,id=>run(()=>chooseBranch(id)));
 async function chooseBranch(id:string){setBranch(id);setVisits([]);setBills([]);setShifts([]);setBillId('');setShiftId('');setVisitId('');setReceipts([]);setPrinted(null);setReason('');setAmount('');setReference('');setStale(false);if(id){const s={...scope,branch:id};const [v,b,h]=await Promise.all([api.visits(s),api.bills(s),api.shifts(s)]);setVisits(v);setBills(b);setShifts(h);}}
 async function sync(){try{await load();}catch{setStale(true);setError('Thao tác đã được ghi nhận. Tải lại thu phí để lấy số dư và phiên bản mới trước khi tiếp tục.');}}
 async function execute(action:()=>Promise<void>){pending.current=action;try{await action();pending.current=null;setUncertain(false);}catch(e){if(e instanceof RequestError&&e.status>=400&&e.status<500){pending.current=null;setUncertain(false);setStale(true);}else setUncertain(true);throw e;}}
 async function mutation<T>(operation:string,body:unknown,request:(key:string)=>Promise<T>,ack:(value:T)=>void){const key=await stableOperationKey('billing-'+operation,{clinic:scope.clinic,branch,actor,...(body as object)});await execute(async()=>{const result=await request(key);ack(result);setMessage('Đã ghi nhận thao tác thu phí.');await sync();});}
 function positive(){const v=Number(amount);if(!Number.isSafeInteger(v)||v<1||v>9000000000000)throw new Error('Nhập số tiền VND nguyên, lớn hơn 0 và trong giới hạn hỗ trợ.');return v;}
 async function issue(){const id=visitId,text=reason;await mutation('issue',{id,reason:text},key=>api.issue(scope,id,text,key),b=>{setBillId(b.id);setBills(current=>[b,...current.filter(x=>x.id!==b.id)]);});}
 async function open(){const text=reason;await mutation('shift-open',{reason:text},key=>api.open(scope,text,key),s=>{setShiftId(s.id);setShifts(current=>[s,...current.filter(x=>x.id!==s.id)]);});}
 async function collect(){if(!bill||!shift)return;const id=bill.id,body={expectedVersion:bill.version,shiftId:shift.id,amountVnd:positive(),method,externalRef:reference.trim()||null,reason};if(body.amountVnd>bill.remainingVnd)throw new Error('Số tiền vượt số dư còn lại.');if(method!=='CASH'&&!body.externalRef)throw new Error('Nhập mã giao dịch đã xác nhận tại quầy.');await mutation('collect',{id,...body},key=>api.collect(scope,id,body,key),r=>{setReceipts(current=>[r,...current.filter(x=>x.id!==r.id)]);setPrinted(r);setAmount('');setReference('');});}
 async function adjust(){if(!bill)return;const id=bill.id,body={expectedVersion:bill.version,amountVnd:positive(),reason};await mutation('adjust',{id,...body},key=>api.adjust(scope,id,body,key),b=>setBills(current=>current.map(x=>x.id===b.id?b:x)));}
 async function retryNotifications(){if(!bill)return;const id=bill.id,text=reason;await mutation('notification-retry',{id,reason:text},key=>api.retryNotifications(scope,id,text,key),()=>{});}
 async function retryCharge(source:'billing'|'medical'|'encounter',eventId:string){const id=visitId,text=reason;await mutation('charge-retry',{id,source,eventId,reason:text},key=>api.retryCharge(scope,id,eventId,text,key,source),()=>{});}
 async function submit(){if(!shift)return;const id=shift.id,body={expectedVersion:shift.version,declaredCashVnd:Number(cash),declaredBankVnd:Number(bank),declaredPosVnd:Number(pos),reason};if([body.declaredCashVnd,body.declaredBankVnd,body.declaredPosVnd].some(v=>!Number.isSafeInteger(v)||v<0||v>9000000000000))throw new Error('Nhập số tiền kiểm đếm VND nguyên, không âm.');await mutation('shift-submit',{id,...body},key=>api.submit(scope,id,body,key),s=>setShifts(current=>current.map(x=>x.id===s.id?s:x)));}
 async function approve(){if(!shift)return;const id=shift.id,version=shift.version,text=reason;await mutation('shift-approve',{id,version,reason:text},key=>api.approve(scope,id,version,text,key),s=>setShifts(current=>current.map(x=>x.id===s.id?s:x)));}
 function logout(){setToken('');setDirectory(null);setActor('');setRole('');setBranch('');setVisits([]);setBills([]);setShifts([]);setReceipts([]);setPrinted(null);setBillId('');setShiftId('');setReason('');setAmount('');setReference('');pending.current=null;setUncertain(false);setStale(false);setError('');setMessage('');onClinic?.('Phòng khám theo phiên đăng nhập');}
 return <section className="booking-panel reception-panel cashier-panel" aria-labelledby="cashier-title"><h1 id="cashier-title">Thu phí tại quầy</h1><p>Lập phiếu từ lượt khám đã hoàn tất. Khoản thu giữ giá tại thời điểm dịch vụ được ghi nhận.</p>
 {error&&<p role="alert" className="booking-error">{error}</p>}{message&&<p role="status">{message}</p>}{busy&&<p role="status">Đang xử lý thu phí…</p>}
 {!token&&shared?<SourceSessionState error={error} retry={()=>void run(login)}/>:!token?<form className="booking-form" onSubmit={e=>{e.preventDefault();void run(login);}}><label>Email thu ngân<input type="email" autoComplete="username" required value={email} disabled={busy} onChange={e=>setEmail(e.target.value)}/></label><label>Mật khẩu thu ngân<input type="password" autoComplete="current-password" required value={password} disabled={busy} onChange={e=>setPassword(e.target.value)}/></label><button className="booking-primary" disabled={busy}>Đăng nhập thu phí</button></form>:<>
 {!shared&&<button type="button" disabled={busy||uncertain} onClick={logout}>Đăng xuất thu phí</button>}<fieldset className="reception-actions" disabled={busy||uncertain}><label>Địa điểm thu phí<select value={branch} onChange={e=>void run(()=>chooseBranch(e.target.value))}><option value="">Chọn địa điểm được cấp quyền</option>{directory?.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label></fieldset>
 {branch&&<button type="button" disabled={busy} onClick={()=>void run(()=>load())}>Tải lại thu phí</button>}
 {uncertain&&<p role="status">Chưa nhận xác nhận. Số tiền, phiên bản và mã yêu cầu được giữ nguyên. <button type="button" disabled={busy} onClick={()=>void run(()=>pending.current?execute(pending.current):Promise.resolve())}>Thử lại thu phí đang chờ</button></p>}
 {branch&&<fieldset className="reception-actions" disabled={busy||uncertain||stale}>
 <label>Lý do lập phiếu hoặc xử lý<textarea maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label>
 <label>Lượt khám đã hoàn tất<select value={visitId} onChange={e=>setVisitId(e.target.value)}><option value="">Chọn lượt khám</option>{visits.map(v=><option key={v.id} value={v.id}>{v.appointmentId?'Lịch hẹn':'Vãng lai'} · {v.visitCode??v.id}</option>)}</select></label><button type="button" disabled={!visitId||!reason.trim()} onClick={()=>void run(issue)}>Lập phiếu thu từ dịch vụ thực</button>
 {visitId&&<ChargeSyncPanel scope={scope} encounterId={visitId} onRetry={manager?(source,eventId)=>void run(()=>retryCharge(source,eventId)):undefined} canRetry={!busy&&!uncertain&&!stale&&!!reason.trim()}/>}
 <label>Phiếu thu<select value={billId} onChange={e=>{const id=e.target.value;setBillId(id);setReceipts([]);setPrinted(null);if(id)void run(async()=>setReceipts(await api.receipts(scope,id)));}}><option value="">Chọn phiếu thu</option>{bills.map(b=><option key={b.id} value={b.id}>{visits.find(v=>v.id===b.encounterId)?.visitCode??b.id} · {money(b.remainingVnd)} còn lại</option>)}</select></label>
 {bill&&<article className="booking-confirm"><h2>Khoản phải thu</h2><ul>{bill.lines.map(l=><li key={l.chargeId}>{l.name} · {money(l.amountVnd)}</li>)}</ul><p>Tổng: {money(bill.subtotalVnd)} · Đã giảm: {money(bill.adjustmentVnd)}</p><p>Đã thu: {money(bill.paidVnd)} · Còn lại: <strong>{money(bill.remainingVnd)}</strong></p></article>}
 {bill&&<CashierNotificationPanel scope={scope} billId={bill.id} version={bill.version} onRetry={manager?()=>void run(retryNotifications):undefined} canRetry={!busy&&!uncertain&&!stale&&!!reason.trim()}/>}
 <label>Ca thu<select value={shiftId} onChange={e=>setShiftId(e.target.value)}><option value="">Chọn ca thu</option>{shifts.map(s=><option key={s.id} value={s.id}>{s.id} · {s.state}</option>)}</select></label><button type="button" disabled={!reason.trim()||shifts.some(s=>s.state==='OPEN'&&s.collectorUserId===actor)} onClick={()=>void run(open)}>Mở ca thu của tôi</button>
 {bill&&<><label>Số tiền VND<input inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Hình thức nhận tiền<select value={method} onChange={e=>setMethod(e.target.value)}>{Object.entries(methodName).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{method!=='CASH'&&<label>Mã giao dịch đã xác nhận tại quầy<input maxLength={200} value={reference} onChange={e=>setReference(e.target.value)}/></label>}<button type="button" className="booking-primary" disabled={!reason.trim()||!amount||!shift||shift.state!=='OPEN'||shift.collectorUserId!==actor||bill.remainingVnd<=0} onClick={()=>void run(collect)}>Ghi nhận tiền đã nhận</button>{manager&&<button type="button" disabled={!reason.trim()||!amount||bill.remainingVnd<=0} onClick={()=>void run(adjust)}>Duyệt giảm khoản phải thu</button>}</>}
 {shift&&<article className="booking-confirm"><h2>Chốt ca thu</h2>{shift.state==='OPEN'&&shift.collectorUserId===actor&&<><label>Tiền mặt kiểm đếm VND<input inputMode="numeric" value={cash} onChange={e=>setCash(e.target.value)}/></label><label>Chuyển khoản kiểm đếm VND<input inputMode="numeric" value={bank} onChange={e=>setBank(e.target.value)}/></label><label>POS kiểm đếm VND<input inputMode="numeric" value={pos} onChange={e=>setPos(e.target.value)}/></label><button type="button" disabled={!reason.trim()} onClick={()=>void run(submit)}>Gửi chốt ca</button></>}{shift.state!=='OPEN'&&<><p>Thực thu: {money((shift.expectedCashVnd??0)+(shift.expectedBankVnd??0)+(shift.expectedPosVnd??0))}</p><p>Chênh lệch kiểm đếm: {money(shift.varianceVnd??0)}</p>{manager&&shift.state==='SUBMITTED'&&shift.collectorUserId!==actor&&<button type="button" disabled={!reason.trim()} onClick={()=>void run(approve)}>Duyệt chốt ca và chênh lệch</button>}</>}</article>}
 </fieldset>}
 <ul aria-label="Biên nhận đã ghi nhận">{receipts.map(r=><li key={r.id}><button type="button" onClick={()=>setPrinted(r)}>{r.receiptCode} · {money(r.amountVnd)}</button></li>)}</ul>
 {printed&&<article className="cashier-receipt" aria-label="Biên nhận nội bộ"><h2>{printed.label}</h2><p>{directory?.name}</p><p>Mã: {printed.receiptCode}</p><p>Đã nhận: <strong>{money(printed.amountVnd)}</strong> · {methodName[printed.method]}</p>{printed.externalRef&&<p>Mã giao dịch: {printed.externalRef}</p>}<p>Người thu: {printed.collectorUserId}</p><p>Thời điểm: {new Date(printed.createdAt).toLocaleString('vi-VN')}</p><button type="button" onClick={()=>window.print()}>In biên nhận nội bộ</button></article>}
 </>}
 </section>;
}

