import { useState } from 'react';
import * as api from '../api/configuration';
import { ConfigurationForm,type Field } from './ConfigurationForm';
import { useConfigurationSource,type ConfigurationProps } from './ConfigurationPanel';
const fields:Field[]=[{key:'name',label:'Tên dịch vụ',required:true,maxLength:220},{key:'description',label:'Mô tả dịch vụ',type:'textarea',maxLength:1000},{key:'specialtyCode',label:'Chuyên khoa của dịch vụ',maxLength:60},{key:'active',label:'Dịch vụ đang hoạt động',type:'checkbox'}];
const assignmentFields:Field[]=[{key:'durationMinutes',label:'Thời lượng (phút)',type:'number',min:5,max:720,required:true},{key:'active',label:'Cung cấp tại địa điểm này',type:'checkbox'},{key:'publicVisible',label:'Hiển thị dịch vụ công khai',type:'checkbox'}];
const money=(amount:number)=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND'}).format(amount);
export function CatalogConfiguration(props:ConfigurationProps){
 const {session,disabled,revision,act}=props;const [selected,setSelected]=useState('');
 const {data,error}=useConfigurationSource(async()=>{const [offerings,assignments]=await Promise.all([api.offerings(session),api.assignments(session)]);return {offerings,assignments};},[session.token,session.clinic,session.branch,revision]);
 if(error)return <p role="alert">{error}</p>;if(!data)return <p role="status">Đang tải danh mục từ nguồn…</p>;
 const current=data.offerings.find(o=>o.id===selected),assigned=data.assignments.find(a=>a.offering.id===selected);
 return <><h2>Thêm dịch vụ</h2><ConfigurationForm key={`offering-create-${revision}`} fields={[{key:'code',label:'Mã dịch vụ',required:true,pattern:'[A-Z0-9._-]{1,60}'},...fields]} initial={{code:'',name:'',description:'',specialtyCode:'',active:true}} disabled={disabled} label="Thêm dịch vụ" submit={v=>act(()=>api.saveOffering(session,{code:v.code,name:v.name,description:v.description,specialtyCode:String(v.specialtyCode??'')||null,active:v.active===true}))}/><label>Dịch vụ cấu hình<select value={selected} disabled={disabled} onChange={e=>setSelected(e.target.value)}><option value="">Chọn dịch vụ trong phòng khám</option>{data.offerings.map(o=><option key={o.id} value={o.id}>{o.code} · {o.name}{o.active?'':' (ngừng hoạt động)'}</option>)}</select></label>{current&&<><h2>{current.name}</h2><ConfigurationForm key={`offering-${current.id}-${current.version}`} fields={fields} initial={{name:current.name,description:current.description??'',specialtyCode:current.specialtyCode??'',active:current.active}} disabled={disabled} label="Lưu dịch vụ" submit={v=>act(()=>api.saveOffering(session,{expectedVersion:current.version,name:v.name,description:v.description,specialtyCode:String(v.specialtyCode??'')||null,active:v.active===true},current.id))}/><h3>Cung cấp tại địa điểm đang cấu hình</h3><ConfigurationForm key={`assignment-${assigned?.id??current.id}-${assigned?.version??revision}`} fields={assignmentFields} initial={{durationMinutes:String(assigned?.durationMinutes??30),active:assigned?.active??true,publicVisible:assigned?.publicVisible??false}} disabled={disabled} label={assigned?'Lưu cung cấp tại địa điểm':'Cấp dịch vụ cho địa điểm'} submit={v=>act(()=>api.saveAssignment(session,{...(assigned?{expectedVersion:assigned.version}:{offeringId:current.id}),durationMinutes:Number(v.durationMinutes),active:v.active===true,publicVisible:v.publicVisible===true},assigned?.id))}/>{assigned&&<PriceConfiguration key={current.id} offering={current} {...props}/>}</>}</>;
}
function PriceConfiguration({offering,session,disabled,revision,act}:ConfigurationProps&{offering:api.Offering}){
 const {data,error}=useConfigurationSource(()=>api.prices(session,offering.id),[session.token,session.clinic,session.branch,offering.id,revision]);
 if(error)return <p role="alert">{error}</p>;if(!data)return <p role="status">Đang tải phiên bản giá…</p>;
 return <><h3>Phiên bản giá</h3><p>Giá mới dùng cho đặt lịch mới theo thời điểm hiệu lực. Giá đã chốt của lịch khám và dịch vụ đã thực hiện được giữ nguyên.</p><ul>{data.map(p=><li key={p.id}>{money(p.amountVnd)} · Hiệu lực từ {new Date(p.effectiveFrom).toLocaleString('vi-VN')}{p.taxPolicyCode?` · Thuế: ${p.taxPolicyCode}`:''}{p.discountPolicyCode?` · Giảm giá: ${p.discountPolicyCode}`:''}</li>)}</ul>{!data.length&&<p>Chưa có giá tại địa điểm này.</p>}<ConfigurationForm key={`price-create-${revision}`} fields={[{key:'amountVnd',label:'Giá mới (VND)',type:'number',min:0,max:9000000000000,required:true},{key:'effectiveFrom',label:'Giá có hiệu lực từ',type:'datetime-local',required:true}]} initial={{amountVnd:'',effectiveFrom:''}} disabled={disabled} label="Thêm phiên bản giá" submit={v=>act(()=>api.addPrice(session,{offeringId:offering.id,amountVnd:Number(v.amountVnd),effectiveFrom:new Date(String(v.effectiveFrom)).toISOString()}))}/><p>Thuế và chính sách giảm giá chỉ dùng mã chính sách đã được phê duyệt; việc thêm giá này không bật thanh toán online.</p></>;
}
