import { useState } from 'react';
import * as api from '../api/configuration';
import { ConfigurationForm,type Field,type FormValues } from './ConfigurationForm';
import { useConfigurationSource,type ConfigurationProps } from './ConfigurationPanel';
const date=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Ho_Chi_Minh'});
const affiliationFields:Field[]=[{key:'specialtyCode',label:'Mã chuyên khoa',required:true,pattern:'[A-Za-z0-9._-]{1,60}'},{key:'specialtyName',label:'Tên chuyên khoa',required:true,maxLength:160},{key:'professionalTitle',label:'Chức danh chuyên môn',maxLength:120},{key:'effectiveFrom',label:'Liên kết có hiệu lực từ',type:'date',required:true},{key:'effectiveUntil',label:'Liên kết có hiệu lực đến (không gồm ngày này)',type:'date'},{key:'publicVisible',label:'Hiển thị bác sĩ trên hồ sơ công khai',type:'checkbox'}];
const scheduleFields:Field[]=[{key:'dayOfWeek',label:'Ngày trong tuần',options:['Thứ hai','Thứ ba','Thứ tư','Thứ năm','Thứ sáu','Thứ bảy','Chủ nhật'].map((label,i)=>({value:String(i+1),label})),required:true},{key:'startTime',label:'Giờ bắt đầu',type:'time',required:true},{key:'endTime',label:'Giờ kết thúc',type:'time',required:true},{key:'effectiveFrom',label:'Lịch có hiệu lực từ',type:'date',required:true},{key:'effectiveUntil',label:'Lịch có hiệu lực đến (không gồm ngày này)',type:'date'},{key:'active',label:'Lịch đang hoạt động',type:'checkbox'}];
const affiliationBody=(v:FormValues)=>({specialtyCode:String(v.specialtyCode),specialtyName:String(v.specialtyName),professionalTitle:String(v.professionalTitle??'')||null,effectiveFrom:String(v.effectiveFrom),effectiveUntil:String(v.effectiveUntil??'')||null,publicVisible:v.publicVisible===true});
const scheduleBody=(v:FormValues)=>({dayOfWeek:Number(v.dayOfWeek),startTime:String(v.startTime),endTime:String(v.endTime),effectiveFrom:String(v.effectiveFrom),effectiveUntil:String(v.effectiveUntil??'')||null,timezone:'Asia/Ho_Chi_Minh',active:v.active===true});
export function DoctorConfiguration(props:ConfigurationProps){
 const {session,disabled,revision,act}=props;const [selected,setSelected]=useState('');
 const {data,error}=useConfigurationSource(async()=>{const [list,members]=await Promise.all([api.affiliations(session),api.memberships(session)]);return {list,members};},[session.token,session.clinic,session.branch,revision]);
 if(error)return <p role="alert">{error}</p>;if(!data)return <p role="status">Đang tải bác sĩ từ nguồn…</p>;
 const doctors=data.members.filter(m=>m.status==='ACTIVE'&&m.role==='DOCTOR'&&(m.allBranches||m.branchIds.includes(session.branch)));
 const current=data.list.find(a=>a.id===selected);
 return <><h2>Liên kết bác sĩ</h2>{doctors.length?<ConfigurationForm key={`affiliation-create-${revision}`} fields={[{key:'userId',label:'Tài khoản bác sĩ đã được cấp quyền',required:true,options:doctors.map(m=>({value:m.userId,label:m.userId}))},{key:'displayName',label:'Họ tên bác sĩ',required:true,maxLength:180},{key:'registrationCode',label:'Mã đăng ký hành nghề',maxLength:100},...affiliationFields]} initial={{userId:doctors[0].userId,displayName:'',registrationCode:'',specialtyCode:'',specialtyName:'',effectiveFrom:date(),publicVisible:false}} disabled={disabled} label="Liên kết bác sĩ với địa điểm" submit={v=>act(()=>api.saveAffiliation(session,{...affiliationBody(v),userId:v.userId,displayName:v.displayName,registrationCode:String(v.registrationCode??'')||null}))}/>:<p>Mời bác sĩ, chấp nhận lời mời và cấp quyền tại địa điểm này trước khi liên kết lịch.</p>}<label>Bác sĩ cấu hình<select value={selected} disabled={disabled} onChange={e=>setSelected(e.target.value)}><option value="">Chọn bác sĩ trong địa điểm</option>{data.list.map(a=><option key={a.id} value={a.id}>{a.displayName} · {a.specialtyName}{a.active?'':' (ngừng hoạt động)'}</option>)}</select></label>{current&&<><ConfigurationForm key={`affiliation-${current.id}-${current.version}`} fields={[...affiliationFields,{key:'active',label:'Liên kết đang hoạt động',type:'checkbox'}]} initial={{specialtyCode:current.specialtyCode,specialtyName:current.specialtyName,professionalTitle:current.professionalTitle??'',effectiveFrom:current.effectiveFrom,effectiveUntil:current.effectiveUntil??'',publicVisible:current.publicVisible,active:current.active}} disabled={disabled} label="Lưu liên kết bác sĩ" submit={v=>act(()=>api.saveAffiliation(session,{...affiliationBody(v),active:v.active===true,expectedVersion:current.version},current.id))}/><ScheduleConfiguration key={current.id} affiliation={current} {...props}/></>}</>;
}
function ScheduleConfiguration({affiliation,session,disabled,revision,act}:ConfigurationProps&{affiliation:api.Affiliation}){
 const {data,error}=useConfigurationSource(()=>api.schedules(session,affiliation.id),[session.token,session.clinic,session.branch,affiliation.id,revision]);
 if(error)return <p role="alert">{error}</p>;if(!data)return <p role="status">Đang tải lịch bác sĩ…</p>;
 return <><h2>Lịch của {affiliation.displayName}</h2><p>Giờ Việt Nam. Đổi lịch có thể ảnh hưởng khả năng đặt mới; lịch đã đặt cần được tiếp nhận xử lý riêng.</p>{data.schedules.map(s=><article className="booking-appointment" key={s.id}><ConfigurationForm key={`${s.id}-${s.version}`} fields={scheduleFields} initial={{dayOfWeek:String(s.dayOfWeek),startTime:s.startTime.slice(0,5),endTime:s.endTime.slice(0,5),effectiveFrom:s.effectiveFrom,effectiveUntil:s.effectiveUntil??'',active:s.active}} disabled={disabled} label="Lưu khung lịch" submit={v=>act(()=>api.saveSchedule(session,affiliation.id,{...scheduleBody(v),expectedVersion:s.version},s.id))}/></article>)}<h3>Thêm khung lịch</h3><ConfigurationForm key={`schedule-create-${revision}`} fields={scheduleFields} initial={{dayOfWeek:'1',startTime:'08:00',endTime:'17:00',effectiveFrom:date(),active:true}} disabled={disabled} label="Thêm khung lịch" submit={v=>act(()=>api.saveSchedule(session,affiliation.id,scheduleBody(v)))}/></>;
}
