import { useState } from 'react';
import * as api from '../api/configuration';
import { ConfigurationForm,type Field } from './ConfigurationForm';
import { useConfigurationSource,type ConfigurationProps } from './ConfigurationPanel';
const roleNames:Record<string,string>={CLINIC_OWNER:'Chủ cơ sở',CLINIC_MANAGER:'Quản lý',RECEPTIONIST:'Tiếp nhận',DOCTOR:'Bác sĩ',NURSE:'Điều dưỡng',LAB:'Lab',CASHIER:'Thu ngân'};
export function MembershipConfiguration({session,clinic,disabled,revision,act}:ConfigurationProps){
 const {data,error}=useConfigurationSource(()=>api.memberships(session),[session.token,session.clinic,revision]);
 const [reason,setReason]=useState(''),[branch,setBranch]=useState(clinic.branches[0]?.id??'');
 const fields:Field[]=[{key:'userId',label:'Mã tài khoản được mời',required:true,pattern:'[0-9a-fA-F-]{36}'},{key:'role',label:'Vai trò được mời',required:true,options:Object.entries(roleNames).filter(([key])=>key!=='CLINIC_OWNER').map(([value,label])=>({value,label}))},{key:'allBranches',label:'Quyền tại tất cả địa điểm của phòng khám',type:'checkbox'},{key:'reason',label:'Lý do mời',required:true,maxLength:500}];
 if(error)return <p role="alert">{error}</p>;if(!data)return <p role="status">Đang tải phân quyền hiện tại…</p>;
 return <><h2>Mời nhân sự</h2><p>Người được mời dùng mã tài khoản của mình và tự chấp nhận lời mời. Lời mời chưa cấp quyền vận hành ngay.</p><ConfigurationForm key={`invite-${revision}`} fields={fields} initial={{userId:'',role:'RECEPTIONIST',allBranches:false,reason:''}} disabled={disabled} label="Mời nhân sự" submit={v=>act(()=>api.invite(session,String(v.userId),String(v.role),v.allBranches===true,String(v.reason)))}/><h2>Phân quyền nhân sự</h2><label>Lý do thay đổi quyền<input required maxLength={500} disabled={disabled} value={reason} onChange={e=>setReason(e.target.value)}/></label><label>Địa điểm cấp quyền<select disabled={disabled} value={branch} onChange={e=>setBranch(e.target.value)}>{clinic.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>{!data.length&&<p>Chưa có nhân sự trong phạm vi này.</p>}{data.map(m=><article key={m.id} className="booking-appointment"><h3>{roleNames[m.role]??m.role} · {m.status==='INVITED'?'Chờ chấp nhận':m.status==='ACTIVE'?'Đang hoạt động':m.status}</h3><p>Mã tài khoản: {m.userId}</p><p>Phạm vi: {m.allBranches?'Tất cả địa điểm':m.branchIds.map(id=>clinic.branches.find(b=>b.id===id)?.name??'Địa điểm không còn khả dụng').join(', ')||'Chưa được cấp địa điểm'}</p>{m.role!=='CLINIC_OWNER'&&<><button disabled={disabled||!reason.trim()} onClick={()=>void act(()=>api.revoke(session,m,reason.trim()))}>Thu hồi vai trò {roleNames[m.role]??m.role}</button>{!m.allBranches&&<><button disabled={disabled||!reason.trim()||!branch||m.branchIds.includes(branch)} onClick={()=>void act(()=>api.grant(session,m,branch,reason.trim()))}>Cấp địa điểm cho {roleNames[m.role]??m.role}</button>{m.branchIds.map(id=><button key={id} disabled={disabled||!reason.trim()} onClick={()=>void act(()=>api.revokeGrant(session,m,id,reason.trim()))}>Thu hồi địa điểm {clinic.branches.find(b=>b.id===id)?.name??id}</button>)}</>}</>}</article>)}</>;
}
