import {usePanelSession} from '../auth/SessionProvider';
import {SourceSessionState} from '../auth/SourceSessionState';
import { useEffect,useRef,useState } from 'react';
import { signIn } from '../api/booking';
import { contexts,directory,type Directory,type Scope } from '../api/reception';
import * as api from '../api/operations';
type Row={id:string;name:string;encounter:api.EncounterSummary|null;billing:api.BillingSummary|null};
const money=(n:number)=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND'}).format(n);
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export function OperationsPanel({onClinic}:{onClinic?:(name:string)=>void}) {
 const shared=usePanelSession(login);
 const [token,setToken]=useState('');const [clinic,setClinic]=useState<Directory|null>(null);const [branch,setBranch]=useState('ALL');const [date,setDate]=useState(today);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [rows,setRows]=useState<Row[]|null>(null);const epoch=useRef(0);
 async function login(){if(busy)return;const current=++epoch.current;setBusy(true);setError('');setRows(null);try{const access=shared?.session?.token??(await signIn(email,password)).data.accessToken;setEmail(shared?.session?.email??email);setPassword('');const memberships=(await contexts(access)).filter(m=>['CLINIC_OWNER','CLINIC_MANAGER'].includes(m.role));const ids=[...new Set(memberships.map(m=>m.clinicId))];const requested=new URLSearchParams(location.search).get('clinicId');const id=requested?(ids.includes(requested)?requested:null):ids.length===1?ids[0]:null;if(!id)throw new Error('Phiên tổng quan cần quyền Chủ cơ sở hoặc Quản lý tại phòng khám trên đường dẫn Workspace.');const c=await directory(access,id);if(current!==epoch.current)return;setToken(access);setClinic(c);setBranch('ALL');onClinic?.(c.name);}catch(e){if(current===epoch.current){setToken('');setClinic(null);setError(e instanceof Error?e.message:'Không thể đăng nhập tổng quan.');}}finally{if(current===epoch.current)setBusy(false);}}
 async function reload(){if(busy||!clinic)return;const current=++epoch.current;setBusy(true);setRows(null);setError('');try{const source=await directory(token,clinic.id);if(current!==epoch.current)return;setClinic(source);const chosen=source.branches.filter(b=>branch==='ALL'||b.id===branch);if(chosen.length===0)throw new Error('Địa điểm vận hành không còn trong phạm vi được cấp quyền.');const list=await Promise.all(chosen.map(async b=>{const scope:Scope={token,clinic:source.id,branch:b.id};const [e,f]=await Promise.allSettled([api.encounters(scope,date),api.billing(scope,date)]);return {id:b.id,name:b.name,encounter:e.status==='fulfilled'?e.value:null,billing:f.status==='fulfilled'?f.value:null};}));if(current===epoch.current)setRows(list);}catch(e){if(current===epoch.current)setError(e instanceof Error?e.message:'Không thể tải tổng quan.');}finally{if(current===epoch.current)setBusy(false);}}
 function logout(){epoch.current++;setToken('');setClinic(null);setRows(null);setPassword('');setError('');setBusy(false);onClinic?.('Phòng khám theo phiên đăng nhập');}
 useEffect(()=>{let active=true;if(shared&&token&&clinic)queueMicrotask(()=>{if(active)void reload();});return()=>{active=false;};},[!!shared,token,clinic?.id,branch,date]);
 const complete=rows&&rows.length>0&&rows.every(r=>r.encounter&&r.billing);const sum=(field:keyof api.EncounterSummary)=>rows?.reduce((v,r)=>v+(typeof r.encounter?.[field]==='number'?r.encounter[field] as number:0),0)??0;
 return <section className="booking-panel reception-panel doctor-panel operations-panel"><h1>Tổng quan vận hành</h1><p>Dữ liệu tiếp nhận và thu phí từ các địa điểm được cấp quyền trong một phòng khám.</p>{busy&&<p role="status">Đang tải dữ liệu nguồn…</p>}{error&&<p role="alert" className="booking-error">{error}</p>}
 {!token&&shared?<SourceSessionState error={error} retry={()=>void login()}/>:!token?<form className="booking-form" onSubmit={e=>{e.preventDefault();void login();}}><label>Email tổng quan<input type="email" required autoComplete="username" disabled={busy} value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Mật khẩu tổng quan<input type="password" required autoComplete="current-password" disabled={busy} value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="booking-primary" disabled={busy}>Đăng nhập tổng quan</button><p>Chủ cơ sở hoặc Quản lý xem tổng quan theo quyền hiện tại.</p></form>:<>{!shared&&<button onClick={logout}>Đăng xuất tổng quan</button>}<div className="booking-form"><label>Địa điểm báo cáo<select value={branch} disabled={busy} onChange={e=>{epoch.current++;setRows(null);setBranch(e.target.value);}}><option value="ALL">Tất cả địa điểm được cấp quyền</option>{clinic?.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Ngày vận hành<input type="date" value={date} disabled={busy} onChange={e=>{epoch.current++;setRows(null);setDate(e.target.value);}}/></label></div><button disabled={busy||!date} onClick={()=>void reload()}>Tải tổng quan nguồn</button>
 {rows&&!complete&&<p role="alert">Chưa tải đủ dữ liệu nguồn. Tổng hợp toàn phạm vi đang chờ kiểm tra lại.</p>}
 {complete&&<article className="booking-confirm"><h2>Toàn phạm vi đang chọn</h2><p>Tiếp nhận trong ngày: {sum('checkedIn')} · Hoàn tất lâm sàng trong ngày: {sum('completed')}</p><p>Lượt khám còn mở: {sum('openVisits')} · Giữ qua ngày: {sum('overnight')}</p><p>Tiền đã nhận trong ngày: {money(rows.reduce((v,r)=>v+r.billing!.collectedCashVnd+r.billing!.collectedBankVnd+r.billing!.collectedPosVnd,0))}</p><p>Khoản còn phải thu hiện tại: {money(rows.reduce((v,r)=>v+r.billing!.outstandingVnd,0))}</p></article>}
 {rows?.map(r=><article className="booking-appointment" key={r.id}><h2>{r.name}</h2>{r.encounter?<><p>Chờ khám: {r.encounter.waitingTickets} · Đang phục vụ: {r.encounter.servingTickets} · Chờ kết quả: {r.encounter.awaitingResults}</p><p>Lượt khám chưa đóng: {r.encounter.openVisits} · Giữ qua ngày: {r.encounter.overnight} · Tiếp nhận đang chờ xác nhận: {r.encounter.arrivalPending}</p><small>Nguồn lượt khám lúc {new Date(r.encounter.measuredAt).toLocaleString('vi-VN')}</small></>:<p>Nguồn lượt khám chưa tải được.</p>}{r.billing?<><p>Tiền mặt: {money(r.billing.collectedCashVnd)} · Chuyển khoản: {money(r.billing.collectedBankVnd)} · POS: {money(r.billing.collectedPosVnd)}</p><p>Ca đang thu: {r.billing.openShifts} · Ca chờ người duyệt riêng: {r.billing.submittedShifts}</p><small>Nguồn thu phí lúc {new Date(r.billing.measuredAt).toLocaleString('vi-VN')}</small></>:<p>Nguồn thu phí chưa tải được.</p>}</article>)}
 <p>Chốt ca thu, đóng lượt khám và ký/phát hành hồ sơ là các bước riêng. Xử lý lượt khám còn mở và ca chờ duyệt trước khi kết thúc vận hành.</p></>}
 </section>;
}

