import {ArrowRight,CalendarDays,Clock3,MapPin,Stethoscope,ClipboardCheck,HeartPulse,UserRound,Check} from 'lucide-react';
import type {Clinic,Doctor,Offering} from '../api/booking';

const money=(amount:number)=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND'}).format(amount);
type Props={clinic:Clinic|null;doctors:Doctor[];offerings:Offering[];book:(doctor?:Doctor,offering?:Offering)=>void;openAccount:()=>void};
export function PublicClinicHome({clinic,doctors,offerings,book,openAccount}:Props){
 const team=[...new Map(doctors.map(d=>[d.doctorId,d])).values()];
 const services=[...new Map(offerings.map(o=>[o.offeringId,o])).values()];
 return <div className="clinic-home">
  <section className="clinic-home-hero"><div className="clinic-home-hero-inner"><div className="clinic-home-copy"><span className="eyebrow"><span className="clinic-eyebrow-line"/> CHĂM SÓC SỨC KHỎE NGOẠI TRÚ</span><h1>Chủ động chăm sóc<br/>sức khỏe <em>của bạn.</em></h1><p>{clinic?.description||'Tìm hiểu dịch vụ, gặp gỡ đội ngũ bác sĩ và chọn lịch khám phù hợp tại phòng khám.'}</p><div className="clinic-hero-actions"><button className="booking-primary" onClick={()=>book()}>Đặt lịch khám <ArrowRight size={18}/></button><a className="button-secondary" href="#about">Tìm hiểu phòng khám</a></div><div className="clinic-hero-note"><Check size={16}/> Chọn giờ khám và xem giá trước khi xác nhận</div></div>
   <div className="clinic-hero-visual"><svg viewBox="0 0 560 420" role="img" aria-label="Minh họa không gian chăm sóc sức khỏe"><rect x="20" y="20" width="520" height="380" rx="28" fill="#e3f2ec"/><circle cx="470" cy="82" r="54" fill="#d0e9dd"/><path d="M45 328Q178 285 262 328T538 328V400H45Z" fill="#cbe6d8"/><rect x="96" y="90" width="355" height="250" rx="16" fill="white"/><rect x="96" y="90" width="355" height="54" rx="16" fill="#087f62"/><path d="M246 109h18v-12h20v12h18v18h-18v12h-20v-12h-18Z" fill="white"/><rect x="128" y="177" width="77" height="96" rx="8" fill="#e5f2ed"/><rect x="339" y="177" width="77" height="96" rx="8" fill="#e5f2ed"/><path d="M167 177v96M128 225h77M377 177v96M339 225h77" stroke="#beddd0" strokeWidth="5"/><rect x="239" y="188" width="66" height="152" rx="8" fill="#b3d9c6"/><rect x="249" y="200" width="46" height="76" rx="4" fill="#eaf6ef"/><circle cx="293" cy="293" r="4" fill="#087f62"/><path d="M70 340V250M70 290Q35 285 39 248Q74 250 70 290M70 269Q102 265 100 233Q71 236 70 269" stroke="#4d9d7d" strokeWidth="5" fill="#73b897"/><rect x="45" y="330" width="51" height="24" rx="4" fill="#d8bc97"/><path d="M455 345V272M455 300Q421 299 427 265Q456 268 455 300M455 280Q490 275 484 245Q456 249 455 280" stroke="#4d9d7d" strokeWidth="5" fill="#73b897"/><rect x="433" y="333" width="43" height="21" rx="4" fill="#d8bc97"/><path d="M205 358h139" stroke="#a8ceb9" strokeWidth="10" strokeLinecap="round"/></svg><span className="clinic-visual-label">Minh họa</span><div className="clinic-visual-card"><span><HeartPulse size={25}/></span><div><strong>{clinic?.name??'Phòng khám'}</strong><small>Thông tin khám và lịch hẹn tại một nơi</small></div></div></div>
  </div></section>
  <div className="clinic-shortcuts" aria-label="Thông tin trước khi đến khám"><a href="#services"><Stethoscope size={24}/><span><strong>Dịch vụ khám</strong><small>Xem dịch vụ và mức giá</small></span><ArrowRight size={17}/></a><a href="#doctors"><UserRound size={24}/><span><strong>Đội ngũ bác sĩ</strong><small>Chọn bác sĩ phù hợp</small></span><ArrowRight size={17}/></a><a href="#contact"><MapPin size={24}/><span><strong>Thông tin đến khám</strong><small>Địa chỉ và giờ hoạt động</small></span><ArrowRight size={17}/></a></div>
  <section className="clinic-home-section clinic-about" id="about"><div><span className="eyebrow">VỀ PHÒNG KHÁM</span><h2>{clinic?.name??'Giới thiệu phòng khám'}</h2><p>{clinic?.description||'Thông tin phòng khám sẽ hiển thị khi được công bố.'}</p><button className="clinic-text-action" onClick={()=>book()}>Xem lịch khám <ArrowRight size={17}/></button></div><div className="clinic-about-features"><article><CalendarDays size={24}/><div><h3>Lịch khám rõ ràng</h3><p>Chọn bác sĩ, dịch vụ và khung giờ còn trống trước khi đến.</p></div></article><article><ClipboardCheck size={24}/><div><h3>Thông tin ngay trong tài khoản</h3><p>Theo dõi lịch hẹn và biên nhận của bạn tại phòng khám.</p></div></article><article><HeartPulse size={24}/><div><h3>Chuẩn bị cho buổi khám</h3><p>Xem địa chỉ, giờ hoạt động và hướng dẫn đặt lịch tại một nơi.</p></div></article></div></section>
  <section className="clinic-home-band" id="services"><div className="clinic-home-section"><div className="clinic-section-heading"><div><span className="eyebrow">DỊCH VỤ TẠI PHÒNG KHÁM</span><h2>Lựa chọn phù hợp với nhu cầu của bạn</h2></div><button className="clinic-text-action" onClick={()=>book()}>Xem giờ khám <ArrowRight size={17}/></button></div><div className="clinic-service-grid">{services.map(o=><article className="clinic-service-card" key={o.offeringId}><span className="clinic-service-icon"><Stethoscope size={27}/></span><h3>{o.name}</h3><p className="clinic-service-price">{money(o.amountVnd)}<small>Giá dịch vụ đang công bố</small></p><button className="clinic-text-action" onClick={()=>book(undefined,o)} aria-label={'Đặt lịch dịch vụ '+o.name}>Đặt lịch <ArrowRight size={17}/></button></article>)}</div>{!services.length&&<p className="clinic-source-empty">Dịch vụ đặt lịch trực tuyến sẽ hiển thị khi phòng khám mở lịch.</p>}</div></section>
  <section className="clinic-home-section" id="doctors"><div className="clinic-section-heading"><div><span className="eyebrow">ĐỘI NGŨ BÁC SĨ</span><h2>Chọn bác sĩ cho buổi khám của bạn</h2></div></div><div className="clinic-doctor-grid">{team.map(d=><article className="clinic-doctor-card" key={d.doctorId}><div className="clinic-doctor-avatar" aria-hidden="true"><UserRound size={48}/></div><div><span className="eyebrow">{d.specialtyName??'Bác sĩ tại phòng khám'}</span><h3>{d.displayName}</h3>{d.professionalTitle&&<p>{d.professionalTitle}</p>}<button className="clinic-text-action" onClick={()=>book(d)} aria-label={'Đặt lịch với '+d.displayName}>Đặt lịch với bác sĩ <ArrowRight size={17}/></button></div></article>)}</div>{!team.length&&<p className="clinic-source-empty">Thông tin bác sĩ nhận lịch trực tuyến sẽ được cập nhật tại đây.</p>}</section>
  <section className="clinic-home-band clinic-steps-band" id="guide"><div className="clinic-home-section"><span className="eyebrow">TRƯỚC KHI ĐẾN KHÁM</span><h2>Đặt lịch trong ba bước</h2><ol className="clinic-step-grid"><li><span>01</span><h3>Chọn lịch phù hợp</h3><p>Chọn bác sĩ, dịch vụ và xem giờ khám còn trống.</p></li><li><span>02</span><h3>Xác nhận thông tin của bạn</h3><p>Đăng nhập hoặc tạo tài khoản, kiểm tra hồ sơ bệnh nhân.</p></li><li><span>03</span><h3>Xác nhận lịch hẹn</h3><p>Xem mức giá và xác nhận trong thời gian giữ giờ.</p></li></ol></div></section>
  <section className="clinic-home-section clinic-contact" id="contact"><div><span className="eyebrow">ĐỊA CHỈ & GIỜ HOẠT ĐỘNG</span><h2>Hẹn gặp bạn tại phòng khám</h2><p>Xem thông tin trước khi đến và chọn một lịch khám phù hợp.</p><button className="booking-primary" onClick={()=>book()}>Đặt lịch trực tuyến <ArrowRight size={18}/></button></div><div className="clinic-contact-details">{clinic?.branches.map(b=><article key={b.branchId}><h3>{b.name}</h3>{b.address&&<p><MapPin size={19}/><span>{b.address}</span></p>}{b.openingHours&&<p><Clock3 size={19}/><span>{b.openingHours}</span></p>}</article>)}</div></section>
  <section className="clinic-home-section clinic-faq" id="faq"><div><span className="eyebrow">HƯỚNG DẪN ĐẶT LỊCH</span><h2>Những điều bạn có thể cần biết</h2></div><div><details><summary>Tôi có cần đăng nhập để xem dịch vụ và bác sĩ?</summary><p>Bạn có thể xem thông tin phòng khám và lịch trống trước. Khi giữ giờ và xác nhận lịch, hãy đăng nhập và kiểm tra hồ sơ của bạn.</p></details><details><summary>Đặt lịch trực tuyến có cần đặt cọc không?</summary><p>Luồng đặt lịch hiện tại không yêu cầu đặt cọc. Giá dịch vụ được hiển thị trước khi bạn xác nhận.</p></details><details><summary>Tôi xem hoặc thay đổi lịch đã đặt ở đâu?</summary><p>Mở Tài khoản bệnh nhân để xem lịch, đổi giờ hoặc hủy lịch đang được phép xử lý.</p><button className="clinic-text-action" onClick={openAccount}>Mở tài khoản bệnh nhân <ArrowRight size={17}/></button></details></div></section>
  <section className="clinic-home-cta"><div><span>CHỦ ĐỘNG SẮP XẾP BUỔI KHÁM</span><h2>Chọn một lịch khám phù hợp với bạn.</h2></div><button onClick={()=>book()}>Đặt lịch khám <ArrowRight size={20}/></button></section>
 </div>;
}
