import {usePanelSession,useSessionBranch} from '../auth/SessionProvider';
import {SourceSessionState} from '../auth/SourceSessionState';
import { useRef, useState } from 'react';
import * as api from '../api/reception';
import { signIn, RequestError } from '../api/booking';
import { stableOperationKey, forgetOperationKey } from '../api/idempotency';
import { AbsenceLifecyclePanel } from './AbsenceLifecyclePanel';
import { SupervisorArrivalPanel } from './SupervisorArrivalPanel';
import { OvernightQueuePanel } from './OvernightQueuePanel';
import type { IamContextView } from '../types/contracts';
import { useNavigationLock } from './useNavigationLock';
import { TaskJumpLinks } from './TaskJumpLinks';
const visitStatus:Record<string,string>={ARRIVAL_PENDING:'Đang chờ xác nhận',WAITING:'Chờ khám',IN_PROGRESS:'Đang khám',AWAITING_RESULTS:'Chờ kết quả',CLINICALLY_COMPLETED:'Hoàn tất chuyên môn',CLOSED:'Đã đóng',CANCELLED:'Đã hủy',INTERRUPTED:'Gián đoạn'};
const localDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export function ReceptionPanel({onClinic,onNavigationLock}:{onClinic?:(name:string)=>void;onNavigationLock?:(reason:string|null)=>void}){
 const shared=usePanelSession(()=>run(login));
 const [token,setToken]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState('');
 const [directory,setDirectory]=useState<api.Directory|null>(null),[branch,setBranch]=useState('');
 const [doctors,setDoctors]=useState<api.Doctor[]>([]),[doctor,setDoctor]=useState('');
 const [points,setPoints]=useState<api.Point[]>([]),[point,setPoint]=useState(''),[destination,setDestination]=useState('');
 const [patients,setPatients]=useState<api.Patient[]>([]),[patient,setPatient]=useState<api.Patient|null>(null);
 const [name,setName]=useState(''),[dob,setDob]=useState(''),[phone,setPhone]=useState(''),[reason,setReason]=useState(''),[evidence,setEvidence]=useState('');
 const [date,setDate]=useState(localDate),[appointments,setAppointments]=useState<api.Appointment[]>([]),[appointment,setAppointment]=useState<api.Appointment|null>(null);
 const [nextQueue,setNextQueue]=useState<number|null>(null);
 const [tickets,setTickets]=useState<api.Ticket[]|null>(null),[visit,setVisit]=useState<api.Visit|null>(null);
 const [recoveries,setRecoveries]=useState<api.ArrivalRecovery[]>([]);const newIntent=useRef('');
 const [exceptions,setExceptions]=useState<api.Exception[]>([]),[exceptionType,setExceptionType]=useState('LATE');
 const [absences,setAbsences]=useState<api.Absence[]>([]),[absenceStart,setAbsenceStart]=useState(''),[absenceEnd,setAbsenceEnd]=useState('');
 const [absenceRecovery,setAbsenceRecovery]=useState(false);const absenceAttempt=useRef<{scope:api.Scope;doctor:string;body:{startsAt:string;endsAt:string;reason:string};key:string}|null>(null);
 const [queuePending,setQueuePending]=useState(false);
 const [supervisorPending,setSupervisorPending]=useState(false);
 const [lifecyclePending,setLifecyclePending]=useState(false),[memberships,setMemberships]=useState<IamContextView[]>([]);
 const [pointCode,setPointCode]=useState(''),[pointName,setPointName]=useState('');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');const running=useRef(false);
 const [walkRecovery,setWalkRecovery]=useState(false);
 const navigationPending=walkRecovery||absenceRecovery||lifecyclePending||supervisorPending||queuePending;
 useNavigationLock(navigationPending?'Xác minh hoặc thử lại thao tác tiếp nhận đang chờ trước khi rời màn hình.':busy?'Đợi thao tác tiếp nhận xử lý xong trước khi rời màn hình.':null,onNavigationLock);
 const walkAttempt=useRef<{scope:api.Scope;payload:{clinic:string;branch:string;actorEmail:string;patientId:string;doctorId:string;servicePointId:string;reason:string;intent:string};key:string}|null>(null);
 const scope:api.Scope={token,clinic:directory?.id??'',branch};
 async function run(action:()=>Promise<void>){if(running.current)return;running.current=true;setBusy(true);setError('');setMessage('');try{await action();}catch(e){setError(e instanceof Error?e.message:'Chưa xác định được kết quả. Tải lại hoặc thử cùng yêu cầu.');}finally{running.current=false;setBusy(false);}}
 async function login(){const auth=shared?.session?.token??(await signIn(email,password)).data.accessToken;setEmail(shared?.session?.email??email);setPassword('');const memberships=await api.contexts(auth);setMemberships(memberships);const clinicIds=[...new Set(memberships.filter(m=>['CLINIC_OWNER','CLINIC_MANAGER','RECEPTIONIST'].includes(m.role)).map(m=>m.clinicId))];const requested=new URLSearchParams(location.search).get('clinicId');const id=requested?(clinicIds.includes(requested)?requested:null):clinicIds.length===1?clinicIds[0]:null;if(!id)throw new Error('Phiên này chưa xác định một phòng khám cho Workspace. Mở đường dẫn Workspace được cấp cho phòng khám của bạn.');const d=await api.directory(auth,id);setToken(auth);setDirectory(d);onClinic?.(d.name);setBranch('');setPatient(null);setPatients([]);setAppointments([]);setAppointment(null);setExceptions([]);setVisit(null);setTickets(null);setNextQueue(null);}
 useSessionBranch(shared,token,directory,branch,id=>run(()=>chooseBranch(id)));
 async function chooseBranch(id:string){walkAttempt.current=null;setRecoveries([]);setBranch(id);setAbsences([]);setPatient(null);setPatients([]);setVisit(null);setAppointments([]);setAppointment(null);setExceptions([]);setTickets(null);setNextQueue(null);setPoint('');setDoctor('');setDoctors([]);setPoints([]);if(!id)return;const s={...scope,branch:id};const [d,p,a]=await Promise.all([api.doctors(s),api.points(s),api.arrivals(s,date)]);setRecoveries(a);const today=localDate();setDoctors(d.filter(x=>x.active&&x.effectiveFrom<=today&&(!x.effectiveUntil||today<x.effectiveUntil)));setPoints(p);}
 async function reloadQueue(afterNumber=0){if(afterNumber===0){setTickets(null);setNextQueue(null);}const page=await api.queuePage(scope,point,date,afterNumber);setTickets(old=>afterNumber>0?[...(old??[]),...page.items]:page.items);setNextQueue(page.nextAfterNumber);}
 async function reportDoctorAbsence(){
  if(!absenceAttempt.current){const body={startsAt:new Date(absenceStart+':00+07:00').toISOString(),endsAt:new Date(absenceEnd+':00+07:00').toISOString(),reason};absenceAttempt.current={scope:{...scope},doctor,body,key:await stableOperationKey('doctor-absence',{clinic:scope.clinic,branch,actorEmail:email,doctor,...body})};}
  const attempt=absenceAttempt.current;setAbsenceRecovery(true);
  try{const result=await api.reportAbsence(attempt.scope,attempt.doctor,attempt.body,attempt.key);setAbsenceRecovery(false);absenceAttempt.current=null;setAbsences(old=>[result,...old.filter(a=>a.id!==result.id)]);setMessage('Đã ghi khoảng vắng và chặn đặt mới. Tiếp tục ghi ngoại lệ cho các lịch bị ảnh hưởng.');}catch(e){if(e instanceof RequestError&&e.status>=400&&e.status<500){setAbsenceRecovery(false);absenceAttempt.current=null;}throw e;}
 }
 async function arriveWalkIn(){
  if(!walkAttempt.current){if(!patient)return;const payload={clinic:scope.clinic,branch,actorEmail:email,patientId:patient.patientId,doctorId:doctor,servicePointId:point,reason,intent:newIntent.current};walkAttempt.current={scope:{...scope},payload,key:await stableOperationKey('walk-in',payload)};}
  const attempt=walkAttempt.current;setWalkRecovery(true);
  let confirmed:api.Visit;
  try{const p=attempt.payload;confirmed=await api.walkIn(attempt.scope,p.patientId,p.doctorId,p.servicePointId,p.reason,attempt.key);}
  catch(e){if(e instanceof RequestError&&e.status>=400&&e.status<500){setWalkRecovery(false);walkAttempt.current=null;}throw e;}
  setWalkRecovery(false);setVisit(confirmed);setMessage('Đã tiếp nhận walk-in · '+confirmed.ticket?.code);const page=await api.queuePage(attempt.scope,attempt.payload.servicePointId,date);setTickets(page.items);setNextQueue(page.nextAfterNumber);
 }
 async function newWalkIn(){if(!visit||walkRecovery)return;if(walkAttempt.current)await forgetOperationKey('walk-in',walkAttempt.current.payload);walkAttempt.current=null;newIntent.current=crypto.randomUUID();setVisit(null);setPatient(null);setPatients([]);setName('');setDob('');setPhone('');setReason('');setEvidence('');setMessage('Đối chiếu hồ sơ cho lượt tiếp nhận mới.');}
 const validScope=!!token&&!!directory&&!!branch;
 return <section className="booking-panel reception-panel"><span className="eyebrow">Tiếp nhận tại phòng khám</span><h1>Tiếp nhận & hàng đợi</h1>
 {!token&&shared?<SourceSessionState error={error} retry={()=>void run(login)}/>:!token?<form className="booking-form" onSubmit={e=>{e.preventDefault();void run(login);}}><label>Email nhân viên<input type="email" required autoComplete="username" disabled={busy} value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Mật khẩu nhân viên<input type="password" required autoComplete="current-password" disabled={busy} value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="booking-primary" disabled={busy}>Đăng nhập tiếp nhận</button></form>:<><p>Phòng khám: <strong>{directory?.name}</strong></p><label>Địa điểm tiếp nhận<select disabled={busy||walkRecovery||absenceRecovery||lifecyclePending||supervisorPending||queuePending} value={branch} onChange={e=>void run(()=>chooseBranch(e.target.value))}><option value="">Chọn địa điểm</option>{directory?.branches.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></label>{!shared&&<button className="button-secondary" disabled={busy||navigationPending} onClick={()=>{setToken('');setMemberships([]);setLifecyclePending(false);setSupervisorPending(false);setQueuePending(false);setDirectory(null);setRecoveries([]);setWalkRecovery(false);setAbsenceRecovery(false);absenceAttempt.current=null;setAbsences([]);setPatient(null);setPatients([]);setTickets(null);setNextQueue(null);setAppointments([]);setAppointment(null);setExceptions([]);setVisit(null);walkAttempt.current=null;onClinic?.('Phòng khám theo phiên đăng nhập');}}>Đăng xuất tiếp nhận</button>}</>}
 <div aria-live="polite">{busy&&<p role="status">Đang xử lý…</p>}{error&&<p role="alert" className="booking-error">{error}</p>}{message&&<p role="status">{message}</p>}</div>
 {walkRecovery&&<div className="booking-confirm"><p>Chưa xác định được kết quả tiếp nhận. Giữ nguyên bệnh nhân, bác sĩ, điểm phục vụ và lý do cho đến khi xác nhận lượt này.</p><button className="booking-primary" disabled={busy} onClick={()=>void run(arriveWalkIn)}>Thử lại lượt tiếp nhận đang chờ</button></div>}
 {absenceRecovery&&<div className="booking-confirm"><p>Chưa xác định được kết quả báo vắng. Thử lại cùng bác sĩ, khoảng thời gian và lý do đã gửi.</p><button className="booking-primary" disabled={busy} onClick={()=>void run(reportDoctorAbsence)}>Thử lại báo vắng đang chờ</button></div>}
 {validScope&&<TaskJumpLinks label="Chuyển nhanh bước tiếp nhận" items={[{id:"reception-patient",name:"Xác minh bệnh nhân"},{id:"reception-arrival",name:"Tiếp nhận"},{id:"reception-queue",name:"Hàng đợi"},{id:"reception-recovery",name:"Lượt đã gửi"}]}/>}
 {validScope&&<section className="public-section"><h2 id="reception-recovery" tabIndex={-1}>Tra cứu lượt đã gửi</h2><p>Các lượt của phiên nhân viên này tại địa điểm và ngày đã chọn. Kiểm tra kết quả trước khi tạo lượt mới sau khi tải lại trang.</p><button className="button-secondary" disabled={busy} onClick={()=>void run(async()=>setRecoveries(await api.arrivals(scope,date)))}>Tải lượt tiếp nhận từ server</button><div className="arrival-recoveries">{recoveries.map(a=><article className="booking-appointment" key={a.visit.id}><h3>{a.visit.ticket?.code??(a.visit.status==='ARRIVAL_PENDING'?'Check-in đang chờ xác nhận':'Lượt '+(visitStatus[a.visit.status]??a.visit.status).toLowerCase())}</h3><p>{a.operation==='walk-in'?'Walk-in':'Lịch đã đặt'} · {visitStatus[a.visit.status]??a.visit.status} · {new Intl.DateTimeFormat('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',timeStyle:'short'}).format(new Date(a.createdAt))}</p><button className="button-secondary" disabled={busy||!reason.trim()} onClick={()=>void run(async()=>{const v=await api.recoverArrival(scope,a.visit,reason);setVisit(v);setWalkRecovery(false);walkAttempt.current=null;setMessage('Đã xác nhận lượt tiếp nhận từ server · '+(v.ticket?.code??v.status));if(v.ticket){setPoint(v.ticket.servicePointId);const page=await api.queuePage(scope,v.ticket.servicePointId,date);setTickets(page.items);setNextQueue(page.nextAfterNumber);}setRecoveries(await api.arrivals(scope,date));})}>{a.visit.status==='ARRIVAL_PENDING'?'Tiếp tục check-in đang chờ':'Xác nhận kết quả lượt này'}</button></article>)}</div></section>}
 {validScope&&<fieldset className="reception-actions" aria-label="Thao tác tiếp nhận" disabled={walkRecovery||absenceRecovery||lifecyclePending||supervisorPending||queuePending}><section className="public-section"><h2 id="reception-patient" tabIndex={-1}>Xác minh bệnh nhân tại quầy</h2><p>Gợi ý trùng là hồ sơ trong phòng khám này. Kiểm tra trực tiếp với người bệnh trước khi chọn; cùng số điện thoại không xác nhận cùng một người.</p><form className="booking-form" onSubmit={e=>{e.preventDefault();void run(async()=>setPatients(await api.suggestions(scope,name,dob,phone)));}}><label>Họ tên bệnh nhân<input disabled={busy} maxLength={180} value={name} onChange={e=>setName(e.target.value)}/></label><label>Ngày sinh bệnh nhân<input disabled={busy} type="date" value={dob} onChange={e=>setDob(e.target.value)}/></label><label>Số điện thoại tìm hồ sơ<input disabled={busy} type="tel" maxLength={30} value={phone} onChange={e=>setPhone(e.target.value)}/></label><button className="button-secondary" disabled={busy}>Tìm gợi ý hồ sơ</button></form>
 {patients.map(p=><article key={p.patientId} className="booking-appointment"><h3>{p.fullName}</h3><p>{p.patientCode} · {p.dateOfBirth??'Chưa rõ ngày sinh'} · Điện thoại kết thúc {p.phoneLast4??'chưa có'} · {p.status}</p><button className="button-secondary" disabled={busy} onClick={()=>{setPatient(p);setVisit(null);walkAttempt.current=null;}}>Đã đối chiếu — chọn hồ sơ</button></article>)}
 <label>Lý do tiếp nhận hoặc điều phối<textarea required maxLength={500} disabled={busy} value={reason} onChange={e=>setReason(e.target.value)}/></label>
 <button className="button-secondary" disabled={busy||!name.trim()||!reason.trim()} onClick={()=>void run(async()=>{const input={fullName:name.trim(),dateOfBirth:dob||null,phone:phone.trim()||null,reason};const key=await stableOperationKey('provisional',{clinic:scope.clinic,branch,actorEmail:email,...input});const p=await api.provisional(scope,input,key);setPatient(p);setPatients([]);setVisit(null);walkAttempt.current=null;setMessage('Đã tạo hồ sơ tạm tại quầy. Không yêu cầu tài khoản web.');})}>Tạo hồ sơ walk-in mới</button>
 {patient&&<div className="booking-confirm"><h3>Hồ sơ đã chọn: {patient.fullName}</h3><p>{patient.patientCode} · {patient.status}</p>{patient.status==='PROVISIONAL'&&<><label>Tham chiếu bằng chứng đối chiếu<input maxLength={180} disabled={busy} value={evidence} onChange={e=>setEvidence(e.target.value)}/></label><button className="button-secondary" disabled={busy||!evidence.trim()||!reason.trim()} onClick={()=>void run(async()=>{setPatient(await api.review(scope,patient,evidence,reason));setMessage('Đã ghi nhận xác minh hồ sơ tại phòng khám.');})}>Ghi nhận đã xác minh</button></>}</div>}</section>
 <section className="public-section"><h2 id="reception-arrival" tabIndex={-1}>Đưa vào hàng đợi</h2><div className="booking-form"><label>Điểm phục vụ<select disabled={busy} value={point} onChange={e=>{setPoint(e.target.value);setTickets(null);setNextQueue(null);}}><option value="">Chọn điểm phục vụ</option>{points.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></label><label>Bác sĩ tiếp nhận<select disabled={busy} value={doctor} onChange={e=>setDoctor(e.target.value)}><option value="">Chọn bác sĩ</option>{doctors.map(d=><option key={d.practitionerId} value={d.practitionerId}>{d.displayName}</option>)}</select></label></div>
 <button className="booking-primary" disabled={busy||!!visit||!patient||!doctor||!point||!reason.trim()} onClick={()=>void run(arriveWalkIn)}>Tiếp nhận walk-in</button>
 {visit&&!visit.appointmentId&&<button className="button-secondary" disabled={busy} onClick={()=>void run(newWalkIn)}>Bắt đầu lượt walk-in mới</button>}
 <form className="booking-form" onSubmit={e=>{e.preventDefault();void run(async()=>{setAppointments(await api.appointments(scope,date));setAppointment(null);setExceptions([]);});}}><label>Ngày tiếp nhận<input type="date" required disabled={busy} value={date} onChange={e=>{setDate(e.target.value);setRecoveries([]);setAppointment(null);setExceptions([]);setAppointments([]);setTickets(null);setNextQueue(null);}}/></label><button className="button-secondary" disabled={busy}>Tải lịch đã đặt</button></form>
 {appointments.map(a=><p key={a.id}><button className="button-secondary" disabled={busy} onClick={()=>{setAppointment(a);setExceptions([]);setVisit(null);}}>{a.appointmentCode} · {new Intl.DateTimeFormat('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',timeStyle:'short'}).format(new Date(a.startsAt))} · {a.status}</button></p>)}
 {appointment&&<><p>Check-in lịch {appointment.appointmentCode}. Hồ sơ đã chọn phải khớp bệnh nhân của lịch này.</p><button className="booking-primary" disabled={busy||!patient||!point||!reason.trim()||!['CONFIRMED','CHECKED_IN'].includes(appointment.status)} onClick={()=>void run(async()=>{if(!patient)return;const key=await stableOperationKey('check-in',{clinic:scope.clinic,branch,actorEmail:email,appointmentId:appointment.id,patientId:patient.patientId,servicePointId:point,reason});const v=await api.checkIn(scope,appointment,patient.patientId,point,reason,key);setVisit(v);setMessage('Đã check-in · '+v.ticket?.code);await reloadQueue();})}>Check-in lịch đã chọn</button></>}
 {appointment&&<section className="public-section"><h3>Ngoại lệ lịch đã chọn</h3><p>Ngoại lệ được giữ để theo dõi. Bác sĩ vắng cần quyền quản lý; chưa có thao tác hoàn tiền tự động.</p><label>Loại ngoại lệ<select disabled={busy} value={exceptionType} onChange={e=>setExceptionType(e.target.value)}><option value="LATE">Đến muộn</option><option value="NO_SHOW">Không đến</option><option value="DOCTOR_ABSENT">Bác sĩ vắng</option></select></label><button className="button-secondary" disabled={busy||!reason.trim()||appointment.status!=='CONFIRMED'} onClick={()=>void run(async()=>{const key=await stableOperationKey('appointment-exception',{clinic:scope.clinic,branch,actorEmail:email,appointmentId:appointment.id,type:exceptionType,reason});const result=await api.recordException(scope,appointment,exceptionType,reason,key);setMessage('Đã ghi nhận ngoại lệ '+result.type+'. Cần theo dõi xử lý.');setExceptions(await api.exceptions(scope,appointment));setAppointments(await api.appointments(scope,date));})}>Ghi nhận ngoại lệ có lý do</button><button className="button-secondary" disabled={busy} onClick={()=>void run(async()=>setExceptions(await api.exceptions(scope,appointment)))}>Tải ngoại lệ lịch</button>{exceptions.map(x=><p key={x.id}>{x.type} · {x.state} · {x.notificationMode==='MANUAL_CONTACT_REQUIRED'?'Cần liên hệ bệnh nhân tại quầy':'Thông báo trong ứng dụng đang được giao'}</p>)}</section>}
 {visit&&<p role="status">Lượt tiếp nhận: {visit.status} · {visit.ticket?.code??'Đang chờ xác nhận lượt đến'}</p>}
  <details><summary>Báo bác sĩ vắng theo khoảng lịch</summary><p>Chủ phòng khám hoặc quản lý báo vắng theo giờ Việt Nam. Khoảng vắng chặn đặt mới tại nguồn. Ghi ngoại lệ cho lịch đã đặt theo từng nhóm tối đa 10 lịch, thử lại phần chưa thành công; giữ lịch và snapshot giá.</p><label>Bác sĩ báo vắng<select disabled={busy} value={doctor} onChange={e=>{setDoctor(e.target.value);setAbsences([]);}}><option value="">Chọn bác sĩ</option>{doctors.map(d=><option key={d.practitionerId} value={d.practitionerId}>{d.displayName}</option>)}</select></label><label>Bắt đầu vắng (giờ Việt Nam)<input type="datetime-local" disabled={busy} value={absenceStart} onChange={e=>setAbsenceStart(e.target.value)}/></label><label>Kết thúc vắng (giờ Việt Nam)<input type="datetime-local" disabled={busy} value={absenceEnd} onChange={e=>setAbsenceEnd(e.target.value)}/></label><button className="button-secondary" disabled={busy||!doctor||!absenceStart||!absenceEnd||!reason.trim()} onClick={()=>void run(reportDoctorAbsence)}>Ghi khoảng vắng có lý do</button><button className="button-secondary" disabled={busy||!doctor} onClick={()=>void run(async()=>setAbsences(await api.doctorAbsences(scope,doctor)))}>Tải khoảng vắng đã ghi</button>{absences.map(a=><article className="booking-appointment" key={a.id}><p>{new Date(a.startsAt).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'})} — {new Date(a.endsAt).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'})}</p><button className="button-secondary" disabled={busy} onClick={()=>void run(async()=>{const result=await api.applyAbsence(scope,a);setMessage(`Đã ghi ngoại lệ cho ${result.recorded} lịch. ${result.retryRequired.length} lịch cần kiểm tra và thử lại.${result.hasMore?' Còn lịch cần ghi ở nhóm tiếp theo.':' Đã hết nhóm lịch chưa ghi tại thời điểm tra cứu.'} Liên hệ bệnh nhân và theo dõi ngoại lệ đang mở.`);})}>Ghi ngoại lệ các lịch bị ảnh hưởng</button></article>)}</details>
 <details><summary>Cấu hình điểm phục vụ</summary><p>Chủ phòng khám hoặc quản lý được cấp quyền cấu hình điểm phục vụ.</p><form className="booking-form" onSubmit={e=>{e.preventDefault();void run(async()=>{await api.createPoint(scope,pointCode,pointName);setPoints(await api.points(scope));setMessage('Đã tạo điểm phục vụ.');});}}><label>Mã điểm phục vụ<input required pattern="[A-Z0-9]{1,8}" maxLength={8} disabled={busy} value={pointCode} onChange={e=>setPointCode(e.target.value.toUpperCase())}/></label><label>Tên điểm phục vụ<input required maxLength={100} disabled={busy} value={pointName} onChange={e=>setPointName(e.target.value)}/></label><button className="button-secondary" disabled={busy}>Tạo điểm phục vụ</button></form></details></section>
 <section className="public-section"><h2 id="reception-queue" tabIndex={-1}>Hàng đợi tại điểm phục vụ</h2><button className="button-secondary" disabled={busy||!point} onClick={()=>void run(reloadQueue)}>Tải lại hàng đợi</button>{nextQueue!==null&&<button className="button-secondary" disabled={busy} onClick={()=>void run(()=>reloadQueue(nextQueue))}>Tải thêm hàng đợi</button>}<label>Chuyển đến điểm phục vụ<select disabled={busy} value={destination} onChange={e=>setDestination(e.target.value)}><option value="">Chọn đích chuyển</option>{points.filter(p=>p.id!==point).map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label>{tickets?.length===0&&<p>Chưa có ticket trong phạm vi này.</p>}{tickets?.map(t=><article className="booking-appointment" key={t.id}><h3>{t.code}</h3><p>{t.state}</p>{['WAITING','CALLED','SKIPPED'].includes(t.state)&&<><button className="button-secondary" disabled={busy||!reason.trim()||t.state!=='WAITING'} onClick={()=>void run(async()=>{await api.move(scope,t,'call',reason);await reloadQueue();})}>Gọi {t.code}</button><button className="button-secondary" disabled={busy||!reason.trim()||t.state==='SKIPPED'} onClick={()=>void run(async()=>{await api.move(scope,t,'skip',reason);await reloadQueue();})}>Bỏ qua {t.code}</button><button className="button-secondary" disabled={busy||!reason.trim()||!destination} onClick={()=>void run(async()=>{await api.move(scope,t,'transfer',reason,destination);await reloadQueue();})}>Chuyển {t.code}</button></>}</article>)}</section></fieldset>}
 {validScope&&<AbsenceLifecyclePanel scope={scope} doctor={doctor} disabled={busy||walkRecovery||absenceRecovery||supervisorPending||queuePending} appointment={appointment} exceptions={exceptions} onPending={setLifecyclePending} canManage={memberships.some(m=>m.clinicId===scope.clinic && ['CLINIC_OWNER','CLINIC_MANAGER'].includes(m.role) && (m.allBranches||m.branchIds.includes(branch)))}/>}
 {validScope&&<SupervisorArrivalPanel scope={scope} disabled={busy||walkRecovery||absenceRecovery||lifecyclePending||queuePending} onPending={setSupervisorPending} canManage={memberships.some(m=>m.clinicId===scope.clinic && ['CLINIC_OWNER','CLINIC_MANAGER'].includes(m.role) && (m.allBranches||m.branchIds.includes(branch)))}/>}
 {validScope&&<OvernightQueuePanel scope={scope} tickets={tickets??[]} onPending={setQueuePending} disabled={busy||walkRecovery||absenceRecovery||lifecyclePending||supervisorPending}/>}
 </section>;
}








