import { requestJson } from './client';
import { unwrap } from './booking';
import type { Directory,Point,Scope,Visit } from './reception';
const clinic=import.meta.env.VITE_CLINIC_URL??'/s1/clinic';
const encounter=import.meta.env.VITE_ENCOUNTER_URL??'/s1/encounter';
const path=(s:Scope)=>`/api/clinics/${encodeURIComponent(s.clinic)}/branches/${encodeURIComponent(s.branch)}`;
const get=<T,>(url:string,token:string)=>unwrap(requestJson<T>(url,{headers:{Authorization:`Bearer ${token}`}}));
export type CareAction='call'|'start'|'await-results'|'resume-queue'|'complete'|'close';
export type CareInput={expectedVersion:number;reason:string;servicePointId?:string;medicalCaseVersion?:number;consultationConfirmed?:boolean};
export const directory=(token:string,id:string)=>get<Directory>(clinic+`/api/clinics/${encodeURIComponent(id)}/care-directory`,token);
export const worklist=(s:Scope)=>get<Visit[]>(encounter+path(s)+'/doctor/worklist',s.token);
export const worklistPage=(s:Scope,after:string)=>get<{items:Visit[];nextAfter:string|null}>(encounter+path(s)+'/doctor/worklist/page?'+new URLSearchParams({after}),s.token);
export const read=(s:Scope,id:string)=>get<Visit>(encounter+path(s)+`/doctor/visits/${encodeURIComponent(id)}`,s.token);
export const points=(s:Scope)=>get<Point[]>(encounter+path(s)+'/doctor/service-points',s.token);
export const command=(s:Scope,id:string,action:CareAction,input:CareInput,key:string)=>unwrap(requestJson<Visit>(encounter+path(s)+`/doctor/visits/${encodeURIComponent(id)}/${action}`,{method:'POST',headers:{Authorization:`Bearer ${s.token}`,'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify(input)}));
