import type {PatientSummary} from '../components/PatientIdentity';
import { requestJson } from './client';
import { unwrap } from './booking';
import type { Scope,Directory } from './reception';
const medical=import.meta.env.VITE_MEDICAL_URL??'/s1/medical';
const catalog=import.meta.env.VITE_CATALOG_URL??'/s1/catalog';
const clinic=import.meta.env.VITE_CLINIC_URL??'/s1/clinic';
const path=(s:Scope)=>`/api/clinics/${encodeURIComponent(s.clinic)}/branches/${encodeURIComponent(s.branch)}`;
const get=<T,>(url:string,token:string)=>unwrap(requestJson<T>(url,{headers:{Authorization:`Bearer ${token}`}}));
const query=<T,>(s:Scope,p:string,body:unknown)=>unwrap(requestJson<T>(medical+path(s)+p,{method:'POST',headers:{Authorization:`Bearer ${s.token}`,'Content-Type':'application/json'},body:JSON.stringify(body)}));
const change=<T,>(s:Scope,p:string,body:unknown,key:string,method='POST')=>unwrap(requestJson<T>(medical+path(s)+p,{method,headers:{Authorization:`Bearer ${s.token}`,'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify(body)}));
export type Note={reasonForVisit:string;medicalHistory:string;allergies:string;vitals:string;examination:string;preliminaryDiagnosis:string;conclusion:string;instructions:string;followUpDate:string|null};
export type Draft={encounterId:string;documentVersion:number;caseVersion:number;status:string;content:Note|null;authorUserId:string|null;savedAt:string|null;contentHash:string|null};
export type Order={id:string;encounterId:string;offeringId:string;name:string;state:string;version:number;resultVersion:number;acceptedBy:string|null;result:{id:string;version:number;sourceRef:string;content:string;authorUserId:string;createdAt:string}|null;reviewedBy:string|null;orderedAt?:string|null;reviewedAt?:string|null;patient?:PatientSummary|null;visitCode?:string|null};
export type WorklistSummary={encounterId:string;pendingOrderCount:number;unreviewedResultCount:number;latestResultAt:string|null;latestResultName:string|null};
export type Offering={offering:{id:string;name:string;active:boolean};active:boolean};
export const draft=(s:Scope,id:string)=>get<Draft>(medical+path(s)+`/visits/${id}/draft`,s.token);
export const orders=(s:Scope,id:string)=>get<Order[]>(medical+path(s)+`/visits/${id}/orders`,s.token);
export const worklistSummaries=(s:Scope,ids:string[])=>ids.length?query<WorklistSummary[]>(s,'/doctor/worklist-summaries',ids):Promise.resolve([]);
export const offerings=(s:Scope)=>get<Offering[]>(catalog+path(s)+'/offerings',s.token);
export const save=(s:Scope,id:string,body:{expectedDocumentVersion:number;content:Note;reason:string},key:string)=>change<Draft>(s,`/visits/${id}/draft`,body,key,'PUT');
export const order=(s:Scope,id:string,body:{expectedCaseVersion:number;offeringId:string;reason:string},key:string)=>change<Order>(s,`/visits/${id}/orders`,body,key);
export const review=(s:Scope,o:Order,reason:string,key:string)=>change<Order>(s,`/orders/${o.id}/reviews`,{expectedVersion:o.version,resultVersion:o.resultVersion,reason},key);
export const validate=(s:Scope,id:string,version:number,reason:string,key:string)=>change<Draft>(s,`/visits/${id}/validate`,{expectedVersion:version,reason},key);
export const labDirectory=(token:string,id:string)=>get<Directory>(clinic+`/api/clinics/${id}/lab-directory`,token);
export const lab=(s:Scope)=>get<Order[]>(medical+path(s)+'/lab/orders',s.token);
export type OrderHistoryPage={items:Order[];nextAfter:string|null};
export const labHistory=(s:Scope,from:string,to:string,after?:string)=>get<OrderHistoryPage>(medical+path(s)+'/lab/orders/history?'+new URLSearchParams({from,to,size:'50',...(after?{after}:{})}),s.token);
export const resultHistory=(s:Scope,id:string)=>get<NonNullable<Order['result']>[]>(medical+path(s)+`/orders/${id}/result-history`,s.token);
export const transition=(s:Scope,o:Order,action:string,reason:string,key:string)=>change<Order>(s,`/orders/${o.id}/${action}`,{expectedVersion:o.version,reason},key);
export const result=(s:Scope,o:Order,body:{sourceRef:string;content:string;reason:string},key:string)=>change<Order>(s,`/orders/${o.id}/results`,{expectedVersion:o.version,...body},key);
