// @vitest-environment jsdom
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {render,screen,cleanup} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {AbsenceLifecyclePanel} from '../components/AbsenceLifecyclePanel';
import * as api from '../api/reception';
vi.mock('../api/reception',()=>({doctorAbsences:vi.fn(),changeAbsence:vi.fn(),resolveException:vi.fn()}));
const scope={token:'synthetic-token',clinic:'clinic',branch:'branch'},source={id:'absence',doctorId:'doctor',startsAt:'2026-10-02T03:00:00Z',endsAt:'2026-10-02T04:00:00Z',state:'ACTIVE' as const,version:1};
beforeEach(()=>{vi.resetAllMocks();vi.mocked(api.doctorAbsences).mockResolvedValueOnce([source]).mockResolvedValue([{...source,state:'CANCELLED',version:2}]);vi.mocked(api.changeAbsence).mockResolvedValue({previous:{...source,state:'CANCELLED',version:2},replacement:null});});afterEach(cleanup);
it('locks the exact cancellation body and key across a lost response',async()=>{
 const user=userEvent.setup(),pending=vi.fn();vi.mocked(api.changeAbsence).mockRejectedValueOnce(new Error('Synthetic lost reply'));render(<AbsenceLifecyclePanel scope={scope} active doctor="doctor" canManage onPending={pending}/>);await screen.findByText(/Đang áp dụng/);await user.type(screen.getByLabelText('Lý do xử lý khoảng vắng hoặc ngoại lệ'),'Synthetic source review');await user.click(screen.getByRole('button',{name:'Hủy khoảng vắng này'}));await screen.findByRole('alert');expect(screen.getByLabelText('Lý do xử lý khoảng vắng hoặc ngoại lệ').closest('fieldset')?.disabled).toBe(true);await user.click(screen.getByRole('button',{name:'Thử lại yêu cầu xử lý đang chờ'}));await screen.findByText(/Hủy khoảng vắng đã được ghi nhận/);expect(vi.mocked(api.changeAbsence).mock.calls[0]).toEqual(vi.mocked(api.changeAbsence).mock.calls[1]);expect(pending).toHaveBeenLastCalledWith(false);expect(screen.queryByRole('button',{name:'Hủy khoảng vắng này'})).toBeNull();
});
it('omits manager mutations for reception and ignores source data arriving after logout',async()=>{
 let complete!:(v:api.Absence[])=>void;vi.mocked(api.doctorAbsences).mockImplementation(()=>new Promise(resolve=>{complete=resolve;}));const view=render(<AbsenceLifecyclePanel scope={scope} active doctor="doctor" canManage={false}/>);view.rerender(<AbsenceLifecyclePanel scope={{...scope,token:''}} doctor="doctor" canManage={false}/>);expect(api.doctorAbsences).not.toHaveBeenCalled();await screen.findByText(/Cần quyền Quản trị/);expect(screen.queryByText(/Đang áp dụng/)).toBeNull();expect(api.changeAbsence).not.toHaveBeenCalled();
});
it('freezes the selected appointment version for an uncertain exception resolution',async()=>{
 const user=userEvent.setup();vi.mocked(api.resolveException).mockRejectedValueOnce(new Error('Synthetic unknown')).mockResolvedValue({id:'exception',appointmentId:'booking',type:'DOCTOR_ABSENT',state:'RESOLVED',notificationMode:'IN_APP'});render(<AbsenceLifecyclePanel scope={scope} active doctor="doctor" canManage appointment={{id:'booking',appointmentCode:'SYN-AP',patientId:'patient',startsAt:source.startsAt,status:'CANCELLED',version:7}} exceptions={[{id:'exception',appointmentId:'booking',type:'DOCTOR_ABSENT',state:'OPEN',notificationMode:'IN_APP'}]}/>);await user.type(screen.getByLabelText('Lý do xử lý khoảng vắng hoặc ngoại lệ'),'Synthetic cancelled booking');await user.click(screen.getByRole('button',{name:'Khép ngoại lệ DOCTOR_ABSENT'}));await screen.findByRole('alert');await user.click(screen.getByRole('button',{name:'Thử lại yêu cầu xử lý đang chờ'}));await screen.findByText(/Khép ngoại lệ đã được ghi nhận/);expect(vi.mocked(api.resolveException).mock.calls[0]).toEqual(vi.mocked(api.resolveException).mock.calls[1]);expect(vi.mocked(api.resolveException).mock.calls[0][3]).toEqual({expectedVersion:7,reason:'Synthetic cancelled booking'});
});
