server:
  port: 8088

spring:
  application:
    name: billing-service
  datasource:
    url: jdbc:postgresql://localhost:5432/clinic_db?currentSchema=billing
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: billing
  flyway:
    enabled: true
    schemas: billing
    locations: classpath:db/migration

services:
  appointment:
    url: http://localhost:8086
  patient:
    url: http://localhost:8084

app:
  security:
    jwt:
      secret: 0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF
      access-token-expiration-minutes: 60
      refresh-token-expiration-days: 7

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
