package com.clinic.billing.service;
import com.clinic.billing.api.*;
import com.clinic.billing.api.BillingDto.*;
import com.clinic.billing.security.*;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import java.time.Instant;
import java.util.*;
import java.security.*;
import java.util.function.Supplier;
@Service public class BillingService {
 private final JdbcTemplate jdbc;private final BillingDb db;private final IamAuthorizationClient iam;private final BillingSources sources;private final ObjectMapper json;private final TransactionTemplate tx;private final ChargeSnapshots snapshots;
 public BillingService(JdbcTemplate jdbc,BillingDb db,IamAuthorizationClient iam,BillingSources sources,ObjectMapper json,PlatformTransactionManager manager,ChargeSnapshots snapshots){this.jdbc=jdbc;this.db=db;this.iam=iam;this.sources=sources;this.json=json;this.snapshots=snapshots;tx=new TransactionTemplate(manager);}
 private boolean allowed(Actor a,UUID c,UUID b,String capability){return a!=null&&iam.decide(a.id(),capability,c,b).allowed();}
 private void require(Actor a,UUID c,UUID b,String capability){if(!allowed(a,c,b,capability))throw ApiProblem.forbidden();}
 private void requireRead(Actor a,UUID c,UUID b){if(!allowed(a,c,b,"BILLING")&&!allowed(a,c,b,"FINANCE_VIEW"))throw ApiProblem.forbidden();}
 private <T>T local(UUID c,UUID b,Supplier<T> body){return tx.execute(t->{db.scope(c,b);return body.get();});}
 private void check(String key,String reason){if(key==null||key.isBlank()||key.length()>120||reason==null||reason.isBlank()||reason.length()>500)throw ApiProblem.invalid("Bounded idempotency key and reason required");}
 private void commandLock(Actor a,String operation,String key){db.lock("billing-command:"+a.id()+":"+operation+":"+key);}
 private UUID replay(Actor a,String operation,String key,String digest){var rows=jdbc.queryForList("select resource_id,payload_hash from billing_v2.commands where actor_user_id=? and operation=? and key=?",a.id(),operation,key);if(rows.isEmpty())return null;if(!digest.equals(rows.getFirst().get("payload_hash")))throw ApiProblem.conflict("Idempotency key payload changed");return (UUID)rows.getFirst().get("resource_id");}
 private void receipt(Actor a,UUID c,UUID b,String op,String key,String digest,UUID id){jdbc.update("insert into billing_v2.commands(clinic_id,branch_id,actor_user_id,operation,key,payload_hash,resource_id) values(?,?,?,?,?,?,?)",c,b,a.id(),op,key,digest,id);}
 public void authorizeFinanceRealtime(Actor actor,UUID clinic,UUID branch){requireRead(actor,clinic,branch);}
 public void authorizeBilling(Actor a,UUID c,UUID b){require(a,c,b,"BILLING");}
 public Bill issue(Actor a,UUID c,UUID b,String key,IssueInput in){
  require(a,c,b,"BILLING");check(key,in.reason());String digest=hash(in);
  Bill previous=local(c,b,()->{commandLock(a,"issue",key);UUID old=replay(a,"issue",key,digest);if(old!=null)return bill(old);db.lock("bill-encounter:"+in.encounterId());var existing=jdbc.queryForList("select id from billing_v2.bills where encounter_id=?",UUID.class,in.encounterId());if(existing.isEmpty())return null;receipt(a,c,b,"issue",key,digest,existing.getFirst());return bill(existing.getFirst());});if(previous!=null)return previous;
  var proof=sources.proof(a,c,b,in.encounterId());
  if(proof==null||!in.encounterId().equals(proof.encounterId())||proof.patientId()==null||proof.charges()==null)throw ApiProblem.invalid("Source billing evidence required");
  if(proof.charges().isEmpty())throw ApiProblem.conflict("Chưa có dịch vụ đã thực hiện để lập phiếu thu. Đối chiếu dịch vụ khám với bác sĩ; phiếu rỗng không có nghĩa là miễn phí.");
  long subtotal=0;try{for(var charge:proof.charges())subtotal=Math.addExact(subtotal,charge.price().amountVnd());}catch(ArithmeticException e){throw ApiProblem.invalid("Bill amount exceeds supported range");}if(subtotal>9000000000000L)throw ApiProblem.invalid("Bill exceeds supported VND range");final long total=subtotal;
  return local(c,b,()->{
   commandLock(a,"issue",key);db.lock("bill-encounter:"+in.encounterId());UUID old=replay(a,"issue",key,digest);if(old!=null)return bill(old);
   var existing=jdbc.queryForList("select id from billing_v2.bills where encounter_id=?",UUID.class,in.encounterId());if(!existing.isEmpty()){receipt(a,c,b,"issue",key,digest,existing.getFirst());return bill(existing.getFirst());}
   UUID id=UUID.randomUUID();jdbc.update("insert into billing_v2.bills(id,clinic_id,branch_id,encounter_id,patient_id,subtotal_vnd,status,issued_by) values(?,?,?,?,?,?,?,?)",id,c,b,in.encounterId(),proof.patientId(),total,total==0?"PAID":"ISSUED",a.id());
   for(var ch:proof.charges()){UUID charge=snapshots.merge(c,b,in.encounterId(),ch);jdbc.update("insert into billing_v2.bill_lines(id,clinic_id,branch_id,bill_id,charge_id) values(?,?,?,?,?)",UUID.randomUUID(),c,b,id,charge);}
   journal(a,c,b,"BILL",id,in.reason(),"RECEIVABLE","REVENUE",total);receipt(a,c,b,"issue",key,digest,id);history(a,c,b,id,"BILL_ISSUED",in.reason());emit(a,c,b,id,id,"clinic.billing.bill_issued.v1");return bill(id);
  });
 }
 public List<Bill> list(Actor a,UUID c,UUID b){requireRead(a,c,b);return local(c,b,()->jdbc.queryForList("select id from billing_v2.bills order by created_at desc limit 100",UUID.class).stream().map(this::bill).toList());}
 public Bill read(Actor a,UUID c,UUID b,UUID id){requireRead(a,c,b);return local(c,b,()->bill(id));}
 public record NotificationState(long pending,long delivered,long manualContact,long failed){}
 private NotificationState notificationState(UUID id){return jdbc.queryForObject("select count(*) filter(where status in ('PENDING','CLAIMED')) pending,count(*) filter(where status='DELIVERED') delivered,count(*) filter(where status='MANUAL_CONTACT') manual,count(*) filter(where status='DLQ') failed from billing_v2.notification_deliveries where bill_id=?",(rs,n)->new NotificationState(rs.getLong("pending"),rs.getLong("delivered"),rs.getLong("manual"),rs.getLong("failed")),id);}
 public NotificationState notifications(Actor a,UUID c,UUID b,UUID id){requireRead(a,c,b);return local(c,b,()->{bill(id);return notificationState(id);});}
 public NotificationState retryNotifications(Actor a,UUID c,UUID b,UUID id,String key,String reason){
  require(a,c,b,"FINANCE_MANAGE");check(key,reason);String digest=hash(List.of(id,reason));return local(c,b,()->{commandLock(a,"notification-retry",key);UUID old=replay(a,"notification-retry",key,digest);bill(id);if(old!=null)return notificationState(old);
   int changed=jdbc.update("update billing_v2.notification_deliveries set status='PENDING',attempts=0,next_attempt_at=now(),last_error=null where bill_id=? and status in ('DLQ','MANUAL_CONTACT')",id);
   receipt(a,c,b,"notification-retry",key,digest,id);if(changed>0){jdbc.update("update billing_v2.bills set row_version=row_version+1 where id=?",id);history(a,c,b,id,"NOTIFICATION_RETRY_REQUESTED",reason);emit(a,c,b,id,id,"clinic.billing.notification_retry_requested.v1");}return notificationState(id);
  });
 }
 private Map<String,Object> row(String table,UUID id){var rows=jdbc.queryForList("select * from billing_v2."+table+" where id=?"+(Set.of("bills","shifts").contains(table)?" for update":""),id);if(rows.isEmpty())throw ApiProblem.missing();return rows.getFirst();}
 private long amount(Map<String,Object> r,String key){return ((Number)r.get(key)).longValue();}
 private Long nullable(Map<String,Object> r,String key){return r.get(key)==null?null:amount(r,key);}
 private Bill bill(UUID id){var r=row("bills",id);var lines=jdbc.query("select ch.* from billing_v2.bill_lines l join billing_v2.charges ch on ch.id=l.charge_id where l.bill_id=? order by ch.created_at,ch.id",(rs,n)->new Line(rs.getObject("id",UUID.class),rs.getString("source_type"),rs.getObject("source_id",UUID.class),rs.getObject("offering_id",UUID.class),rs.getString("name"),rs.getLong("amount_vnd")),id);long subtotal=amount(r,"subtotal_vnd"),adjustment=amount(r,"adjustment_vnd"),paid=amount(r,"paid_vnd");return new Bill(id,(UUID)r.get("encounter_id"),(UUID)r.get("patient_id"),"VND",subtotal,adjustment,paid,subtotal-adjustment-paid,r.get("status").toString(),amount(r,"row_version"),lines);}
 public Shift open(Actor a,UUID c,UUID b,String key,ShiftInput in){require(a,c,b,"BILLING");check(key,in.reason());String digest=hash(in);return local(c,b,()->{commandLock(a,"shift-open",key);UUID old=replay(a,"shift-open",key,digest);if(old!=null)return shift(old);db.lock("shift-collector:"+a.id());if(jdbc.queryForObject("select count(*) from billing_v2.shifts where collector_user_id=? and state='OPEN'",Integer.class,a.id())>0)throw ApiProblem.conflict("Collector already has an open shift");UUID id=UUID.randomUUID();jdbc.update("insert into billing_v2.shifts(id,clinic_id,branch_id,collector_user_id) values(?,?,?,?)",id,c,b,a.id());receipt(a,c,b,"shift-open",key,digest,id);history(a,c,b,id,"SHIFT_OPENED",in.reason());return shift(id);});}
 public List<Shift> shifts(Actor a,UUID c,UUID b){boolean approver=allowed(a,c,b,"FINANCE_MANAGE");if(!approver&&!allowed(a,c,b,"BILLING"))throw ApiProblem.forbidden();return local(c,b,()->jdbc.queryForList("select id from billing_v2.shifts where (? or collector_user_id=?) order by opened_at desc limit 100",UUID.class,approver,a.id()).stream().map(this::shift).toList());}
 private Shift shift(UUID id){var r=row("shifts",id);return new Shift(id,(UUID)r.get("collector_user_id"),r.get("state").toString(),amount(r,"row_version"),"OPEN".equals(r.get("state"))?shiftTotal(id,"CASH"):nullable(r,"expected_cash_vnd"),"OPEN".equals(r.get("state"))?shiftTotal(id,"BANK_TRANSFER"):nullable(r,"expected_bank_vnd"),"OPEN".equals(r.get("state"))?shiftTotal(id,"POS"):nullable(r,"expected_pos_vnd"),nullable(r,"declared_cash_vnd"),nullable(r,"declared_bank_vnd"),nullable(r,"declared_pos_vnd"),nullable(r,"variance_vnd"),(UUID)r.get("approved_by"));}
 public Receipt collect(Actor a,UUID c,UUID b,UUID id,String key,PaymentInput in){
  require(a,c,b,"BILLING");check(key,in.reason());if(in.amountVnd()<1||in.amountVnd()>9000000000000L||!Set.of("CASH","BANK_TRANSFER","POS").contains(in.method()))throw ApiProblem.invalid("Positive onsite VND amount and supported method required");
  String reference=in.externalRef()==null||in.externalRef().isBlank()?null:in.externalRef().trim();if(!"CASH".equals(in.method())&&reference==null)throw ApiProblem.invalid("Bank/POS collection requires a verified onsite transaction reference");String digest=hash(List.of(id,in));
  return local(c,b,()->{commandLock(a,"collect",key);UUID old=replay(a,"collect",key,digest);if(old!=null)return payment(old);
   var shift=row("shifts",in.shiftId());if(!a.id().equals(shift.get("collector_user_id"))||!"OPEN".equals(shift.get("state")))throw ApiProblem.forbidden();
   var current=bill(id);OnlinePaymentService.ensureUnreserved(jdbc,id);if(current.version()!=in.expectedVersion()||in.amountVnd()>current.remainingVnd())throw ApiProblem.conflict("Bill changed or payment exceeds remaining amount");
   if("BANK_TRANSFER".equals(in.method())){db.lock("incoming-bank:"+reference);if(jdbc.queryForObject("select count(*) from billing_v2.payments where external_ref=? and method in ('BANK_TRANSFER','PAYOS')",Integer.class,reference)>0)throw ApiProblem.conflict("Mã giao dịch ngân hàng đã được ghi nhận qua payOS hoặc tại quầy. Đối chiếu biên nhận trước khi thu thêm.");}
   UUID payment=UUID.randomUUID();jdbc.update("insert into billing_v2.payments(id,clinic_id,branch_id,bill_id,shift_id,collector_user_id,amount_vnd,method,external_ref,reason,receipt_code) values(?,?,?,?,?,?,?,?,?,?,?)",payment,c,b,id,in.shiftId(),a.id(),in.amountVnd(),in.method(),reference,in.reason().trim(),"RCT-"+payment);
   long paid=current.paidVnd()+in.amountVnd();jdbc.update("update billing_v2.bills set paid_vnd=?,status=?,row_version=row_version+1 where id=?",paid,in.amountVnd()==current.remainingVnd()?"PAID":"PARTIALLY_PAID",id);
   journal(a,c,b,"PAYMENT",payment,in.reason(),switch(in.method()){case "CASH"->"CASH";case "POS"->"POS";default->"BANK";},"RECEIVABLE",in.amountVnd());
   receipt(a,c,b,"collect",key,digest,payment);history(a,c,b,payment,"ONSITE_COLLECTED",in.reason());emit(a,c,b,id,payment,"clinic.billing.onsite_collected.v1");return payment(payment);
  });
 }
 public static String receiptLabel(boolean sandbox){return sandbox?"BIÊN NHẬN THỬ NGHIỆM VNPAY — KHÔNG PHẢI TIỀN THỰC":"BIÊN NHẬN NỘI BỘ — KHÔNG PHẢI HÓA ĐƠN THUẾ";}
 private Receipt payment(UUID id){var r=row("payments",id);return new Receipt(id,(UUID)r.get("bill_id"),(UUID)r.get("shift_id"),(UUID)r.get("collector_user_id"),amount(r,"amount_vnd"),"VND",r.get("method").toString(),(String)r.get("external_ref"),r.get("receipt_code").toString(),((java.sql.Timestamp)r.get("created_at")).toInstant(),receiptLabel(jdbc.queryForObject("select exists(select 1 from billing_v2.payment_intents where receipt_id=? and checkout_url like 'https://sandbox.vnpayment.vn/%')",Boolean.class,id)));}
 public List<Receipt> payments(Actor a,UUID c,UUID b,UUID billId){requireRead(a,c,b);return local(c,b,()->{bill(billId);return jdbc.queryForList("select id from billing_v2.payments where bill_id=? order by created_at",UUID.class,billId).stream().map(this::payment).toList();});}
 public Bill adjust(Actor a,UUID c,UUID b,UUID id,String key,AdjustmentInput in){require(a,c,b,"FINANCE_MANAGE");check(key,in.reason());if(in.amountVnd()<1)throw ApiProblem.invalid("Positive reduction required");String digest=hash(List.of(id,in));return local(c,b,()->{commandLock(a,"adjust",key);UUID old=replay(a,"adjust",key,digest);if(old!=null)return bill(old);var current=bill(id);OnlinePaymentService.ensureUnreserved(jdbc,id);if(current.version()!=in.expectedVersion()||in.amountVnd()>current.remainingVnd())throw ApiProblem.conflict("Adjustment cannot reduce below money already collected");UUID adjustment=UUID.randomUUID();jdbc.update("insert into billing_v2.adjustments(id,clinic_id,branch_id,bill_id,amount_vnd,approved_by,reason) values(?,?,?,?,?,?,?)",adjustment,c,b,id,in.amountVnd(),a.id(),in.reason().trim());jdbc.update("update billing_v2.bills set adjustment_vnd=adjustment_vnd+?,status=?,row_version=row_version+1 where id=?",in.amountVnd(),in.amountVnd()==current.remainingVnd()?"PAID":current.paidVnd()>0?"PARTIALLY_PAID":"ISSUED",id);journal(a,c,b,"ADJUSTMENT",adjustment,in.reason(),"DISCOUNT","RECEIVABLE",in.amountVnd());receipt(a,c,b,"adjust",key,digest,id);history(a,c,b,adjustment,"ADJUSTMENT_APPROVED",in.reason());emit(a,c,b,id,adjustment,"clinic.billing.adjustment_approved.v1");return bill(id);});}
 public Shift submit(Actor a,UUID c,UUID b,UUID id,String key,ShiftSubmit in){require(a,c,b,"BILLING");check(key,in.reason());String digest=hash(List.of(id,in));return local(c,b,()->{commandLock(a,"shift-submit",key);UUID old=replay(a,"shift-submit",key,digest);if(old!=null)return shift(old);var current=shift(id);if(!a.id().equals(current.collectorUserId()))throw ApiProblem.forbidden();if(!"OPEN".equals(current.state())||current.version()!=in.expectedVersion())throw ApiProblem.conflict("Shift changed or already submitted");long cash=shiftTotal(id,"CASH"),bank=shiftTotal(id,"BANK_TRANSFER"),pos=shiftTotal(id,"POS");if((in.expectedCashVnd()!=null||in.expectedBankVnd()!=null||in.expectedPosVnd()!=null)&&(in.expectedCashVnd()==null||in.expectedCashVnd()!=cash||in.expectedBankVnd()==null||in.expectedBankVnd()!=bank||in.expectedPosVnd()==null||in.expectedPosVnd()!=pos))throw ApiProblem.conflict("Tổng tiền đã thu thay đổi sau khi xem lại. Tải ca thu và kiểm đếm lại trước khi chốt.");long variance;try{variance=Math.subtractExact(Math.addExact(Math.addExact(in.declaredCashVnd(),in.declaredBankVnd()),in.declaredPosVnd()),Math.addExact(Math.addExact(cash,bank),pos));}catch(ArithmeticException e){throw ApiProblem.invalid("Shift totals exceed supported range");}if(in.declaredCashVnd()<0||in.declaredBankVnd()<0||in.declaredPosVnd()<0)throw ApiProblem.invalid("Nonnegative declared totals required");jdbc.update("update billing_v2.shifts set state='SUBMITTED',expected_cash_vnd=?,expected_bank_vnd=?,expected_pos_vnd=?,declared_cash_vnd=?,declared_bank_vnd=?,declared_pos_vnd=?,variance_vnd=?,submitted_at=now(),row_version=row_version+1 where id=?",cash,bank,pos,in.declaredCashVnd(),in.declaredBankVnd(),in.declaredPosVnd(),variance,id);receipt(a,c,b,"shift-submit",key,digest,id);history(a,c,b,id,"SHIFT_SUBMITTED",in.reason());emit(a,c,b,id,id,"clinic.billing.shift_submitted.v1");return shift(id);});}
 private long shiftTotal(UUID id,String method){return jdbc.queryForObject("select coalesce(sum(amount_vnd),0) from billing_v2.payments where shift_id=? and method=?",Long.class,id,method);}
 public Shift approve(Actor a,UUID c,UUID b,UUID id,String key,ApproveInput in){require(a,c,b,"FINANCE_MANAGE");check(key,in.reason());String digest=hash(List.of(id,in));return local(c,b,()->{commandLock(a,"shift-approve",key);UUID old=replay(a,"shift-approve",key,digest);if(old!=null)return shift(old);var current=shift(id);if(a.id().equals(current.collectorUserId()))throw ApiProblem.forbidden();if(!"SUBMITTED".equals(current.state())||current.version()!=in.expectedVersion())throw ApiProblem.conflict("Submitted shift version required");jdbc.update("update billing_v2.shifts set state='APPROVED',approved_by=?,approved_at=now(),row_version=row_version+1 where id=?",a.id(),id);receipt(a,c,b,"shift-approve",key,digest,id);history(a,c,b,id,"SHIFT_APPROVED",in.reason());emit(a,c,b,id,id,"clinic.billing.shift_approved.v1");return shift(id);});}
 private void journal(Actor a,UUID c,UUID b,String type,UUID source,String reason,String debit,String credit,long amount){if(amount==0)return;UUID id=UUID.randomUUID();jdbc.update("insert into billing_v2.journals(id,clinic_id,branch_id,source_type,source_id,actor_user_id,reason) values(?,?,?,?,?,?,?)",id,c,b,type,source,a.id(),reason.trim());for(String side:List.of("D","C"))jdbc.update("insert into billing_v2.journal_lines(id,clinic_id,branch_id,journal_id,account,side,amount_vnd) values(?,?,?,?,?,?,?)",UUID.randomUUID(),c,b,id,"D".equals(side)?debit:credit,side,amount);}
 private void history(Actor a,UUID c,UUID b,UUID id,String action,String reason){jdbc.update("insert into billing_v2.history(id,clinic_id,branch_id,resource_id,actor_user_id,action,reason) values(?,?,?,?,?,?,?)",UUID.randomUUID(),c,b,id,a.id(),action,reason.trim());}
 private void emit(Actor a,UUID c,UUID b,UUID aggregate,UUID resource,String type){UUID id=UUID.randomUUID();var event=new LinkedHashMap<String,Object>();event.put("specversion","1.0");event.put("id",id.toString());event.put("source","/services/billing");event.put("type",type);event.put("subject","billing/"+aggregate);event.put("time",Instant.now().toString());event.put("datacontenttype","application/json");event.put("clinicid",c.toString());event.put("branchid",b.toString());event.put("correlationid",UUID.randomUUID().toString());String table=type.startsWith("clinic.billing.shift_")?"shifts":"bills";event.put("aggregateversion",amount(row(table,aggregate),"row_version")+1);event.put("data",Map.of("billingId",aggregate.toString(),"resourceId",resource.toString(),"actorUserId",a.id().toString()));jdbc.update("insert into billing_v2.outbox_events(event_id,clinic_id,branch_id,aggregate_id,event_type,payload_json) values(?,?,?,?,?,?)",id,c,b,aggregate,type,write(event));}
 private String write(Object body){try{return json.writeValueAsString(body);}catch(Exception e){throw new IllegalStateException(e);}}
 private String hash(Object body){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(json.writeValueAsBytes(body)));}catch(Exception e){throw new IllegalStateException(e);}}
}
