import { Building2,ShieldAlert,ShieldCheck,Stethoscope,LogOut,ArrowUpRight } from 'lucide-react';
import type { UiState } from '../types/contracts';
import { UiStatePanel } from '../components/UiStatePanel';
import { PlatformReviewPanel } from '../components/PlatformReviewPanel';
import {useSession} from '../auth/SessionProvider';
export function PlatformShell({state}:{state:UiState}){
 const auth=useSession();
 if(auth?.session&&!auth.session.actor.platformOperator)return <main id="main-content" className="workspace-content"><h1>Chưa có quyền Platform Console</h1><p>Tài khoản này chưa được cấp quyền quản trị nền tảng.</p><button className="button-secondary" onClick={()=>auth.navigate('/public')}>Về trang Public</button><button className="button-secondary" onClick={()=>auth.signOut()}>Đăng xuất</button></main>;
 return <div className="platform-shell"><aside className="platform-sidebar"><div className="workspace-brand platform-brand"><span className="brand-mark"><Stethoscope size={21}/></span><span><strong>Clinic V2</strong><small>Platform Console</small></span></div><nav className="workspace-nav" aria-label="Điều hướng Platform Console"><a className="nav-active" href="#main-content"><Building2 size={18}/> Hồ sơ kiểm duyệt</a></nav><div className="sidebar-footer"><span>Không có quyền bệnh án mặc định</span></div></aside><div className="workspace-main"><header className="workspace-topbar platform-topbar"><div className="platform-context"><ShieldCheck size={18}/><span><strong>Platform Console</strong><small>Quyền nền tảng tách khỏi vai trò phòng khám</small></span></div>{auth?.session&&<div className="workspace-account"><span>{auth.session.email}</span><button aria-label="Mở trang Public" title="Mở trang Public" onClick={()=>auth.navigate("/public")}><ArrowUpRight size={17}/></button><button aria-label="Đăng xuất" title="Đăng xuất" onClick={()=>auth.signOut()}><LogOut size={17}/></button></div>}</header><main id="main-content" className="workspace-content"><div className="privacy-banner" role="note"><ShieldAlert size={20}/><div><strong>Phạm vi Platform Ops</strong><span>Console này không hiển thị ghi chú lâm sàng, encounter detail hoặc hồ sơ bệnh án theo mặc định.</span></div></div>{state!=='ready'?<UiStatePanel state={state}/>:<PlatformReviewPanel/>}</main></div></div>;
}
