server:
  port: 8083

spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:postgresql://localhost:5432/clinic_management
    username: postgres
    password: "0000"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_schema: identity
    open-in-view: false

  flyway:
    enabled: true
    default-schema: identity
    schemas: identity
    locations: classpath:db/migration
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

app:
  security:
    jwt:
      secret: 0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF
      access-token-expiration-minutes: 60
      refresh-token-expiration-days: 7