package com.clinic.iam.api;
public enum Capability {
 PLATFORM_CLINIC_REVIEW,
 CLINIC_MEMBER, CLINIC_READ, CLINIC_CONFIG, MEMBERSHIP_READ, MEMBERSHIP_MANAGE,
 RECEPTION, BILLING, DOCTOR_WORK, LAB_WORK, CATALOG_READ, CATALOG_MANAGE,
 SCHEDULE_READ, SCHEDULE_MANAGE
}
