import {test,expect} from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
const config=JSON.parse(fs.readFileSync(process.env.CLINIC_V2_REAL_E2E_CONFIG!,'utf8'));
test('new patient registers through the real Public form and owns a new Patient profile',async({page})=>{
 const email='synthetic-public-'+crypto.randomUUID()+'@example.invalid',password=crypto.randomUUID();await page.goto('/public/account');await page.getByRole('button',{name:'Tạo tài khoản bệnh nhân',exact:true}).click();await page.getByLabel('Họ tên',{exact:true}).fill('Synthetic Public Registration');await page.getByLabel('Họ tên',{exact:true}).press('Tab');await expect(page.getByLabel('Email',{exact:true})).toBeFocused();await page.keyboard.type(email);await page.keyboard.press('Tab');await expect(page.getByLabel('Mật khẩu',{exact:true})).toBeFocused();await page.keyboard.type(password);await page.keyboard.press('Tab');await expect(page.getByRole('button',{name:'Hiện mật khẩu',exact:true})).toBeFocused();await page.keyboard.press('Tab');await expect(page.getByRole('button',{name:'Tạo tài khoản',exact:true})).toBeFocused();
 const registration=page.waitForResponse(response=>response.url().endsWith('/api/auth/register')&&response.request().method()==='POST');await page.keyboard.press('Enter');expect((await registration).status()).toBe(200);await expect(page.getByRole('button',{name:'Lưu hồ sơ'})).toBeVisible();await page.getByLabel('Ngày sinh',{exact:true}).fill('1990-01-01');await page.getByLabel('Số điện thoại',{exact:true}).fill('0009988776');const profileResponse=page.waitForResponse(response=>response.url().endsWith('/api/v2/me/patient-profile')&&response.request().method()==='PUT');await page.getByRole('button',{name:'Lưu hồ sơ'}).click();const response=await profileResponse;expect(response.status()).toBe(200);const profile=await response.json();expect(profile.patientId).toBeTruthy();expect(profile.fullName).toBe('Synthetic Public Registration');const storage=await page.evaluate(()=>JSON.stringify([localStorage,sessionStorage]));expect(storage).not.toContain(password);expect(storage).not.toContain(email);expect(storage).not.toContain('accessToken');
 fs.writeFileSync(path.join(config.evidence,'actual-public-registration.json'),JSON.stringify({status:'PASS',http:'actual-Public-register-Patient-profile-no-route-fixtures',registrationStatus:200,profileStatus:200,patientId:profile.patientId,credentialsPersisted:false,keyboardRegistration:'Tab-focus-Enter-submit'},null,2));
});
test('actual registered patient logs in and books through real Search and source APIs without deposit',async({page})=>{
 const failures:string[]=[];page.on('pageerror',error=>failures.push(error.message));
 await page.goto('/public/booking');await expect(page.getByRole('heading',{name:'Chọn lịch khám',exact:true})).toBeVisible();await expect(page.getByRole('searchbox')).toHaveCount(0);await page.getByRole('button',{name:'Đăng nhập để đặt lịch',exact:true}).click();
 await page.getByLabel('Email',{exact:true}).fill(config.email);await page.getByLabel('Mật khẩu',{exact:true}).fill(config.password);await page.getByRole('button',{name:'Đăng nhập',exact:true}).click();await expect(page.getByRole('button',{name:'Lưu hồ sơ'})).toBeVisible();
 const branch=page.getByRole('combobox',{name:'Địa điểm khám',exact:true});if(await branch.count())await branch.selectOption(config.branch);await page.getByRole('combobox',{name:'Bác sĩ',exact:true}).selectOption(config.doctor);await page.getByRole('combobox',{name:'Dịch vụ',exact:true}).selectOption(config.offering);await page.getByLabel('Ngày khám',{exact:true}).fill(config.date);await page.getByRole('button',{name:'Xem giờ còn trống'}).click();
 const held=page.waitForResponse(response=>response.url().endsWith('/api/v2/appointments/holds')&&response.request().method()==='POST');await page.locator('[aria-label="Giờ khám còn trống"]').getByRole('button').first().click();const holdResponse=await held;expect(holdResponse.status()).toBe(201);const hold=await holdResponse.json();await expect(page.getByText('Không yêu cầu đặt cọc cho lượt đặt lịch này.')).toBeVisible();
 const confirmed=page.waitForResponse(response=>response.url().endsWith('/api/v2/appointments')&&response.request().method()==='POST');await page.getByRole('button',{name:'Xác nhận đặt lịch',exact:true}).click();const confirmResponse=await confirmed;expect(confirmResponse.status()).toBe(201);const booking=await confirmResponse.json();expect(booking.status).toBe('CONFIRMED');expect(booking.clinicId).toBe(config.clinic);expect(booking.price.amountVnd).toBe(100000);await expect(page.getByRole('status').filter({hasText:'Đã xác nhận:'})).toBeVisible();await page.getByRole('link',{name:'Tài khoản bệnh nhân',exact:true}).click();await expect(page.getByRole('heading',{name:booking.appointmentCode})).toBeVisible();
 expect(failures).toEqual([]);expect(await page.evaluate(()=>JSON.stringify([localStorage,sessionStorage]))).not.toContain('accessToken');await page.setViewportSize({width:375,height:812});expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.evaluate(()=>{(document.activeElement as HTMLElement)?.blur();});await page.screenshot({path:path.join(config.evidence,'actual-public-booking-mobile.png'),fullPage:true});
 fs.writeFileSync(path.join(config.evidence,'actual-public-booking.json'),JSON.stringify({status:'PASS',http:'real-services-no-route-fixtures',hold,booking,holdKey:holdResponse.request().headers()['idempotency-key'],confirmKey:confirmResponse.request().headers()['idempotency-key']},null,2));
});


