function Peer-Environment {
 $taskPeer=$taskConfig.peerSecret;$taskPorts=$taskConfig.ports
 $taskEnv=@{SERVER_ADDRESS='127.0.0.1';SPRING_FLYWAY_ENABLED='true';SPRING_FLYWAY_USER='postgres';SPRING_FLYWAY_PASSWORD=$taskConfig.databasePassword;SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE='4';SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE='1'}
 foreach($taskService in $taskServices){
  $taskPrefix=if($taskService -eq 'identity'){'IAM'}else{$taskService.ToUpperInvariant()}
  $taskEnv["${taskPrefix}_IAM_URL"]="http://127.0.0.1:$($taskPorts.identity)/modules/identity"
  $taskEnv["${taskPrefix}_IDENTITY_URL"]="http://127.0.0.1:$($taskPorts.identity)/modules/identity"
  $taskEnv["${taskPrefix}_CLINIC_URL"]="http://127.0.0.1:$($taskPorts.clinic)/modules/clinic"
  $taskEnv["${taskPrefix}_IAM_SERVICE_SECRET"]=$taskPeer
  $taskEnv["${taskPrefix}_CLINIC_SERVICE_SECRET"]=$taskPeer
 }
 foreach($taskKey in @('PROJECTION_RELAY_SECRET','SEARCH_CLINIC_SECRET','SEARCH_DOCTOR_SECRET','SEARCH_CATALOG_SECRET','AUDIT_SECURITY_ENCOUNTER_SECRET','AUDIT_SECURITY_APPOINTMENT_SECRET','AUDIT_SECURITY_MEDICAL_SECRET','AUDIT_SECURITY_BILLING_SECRET','AUDIT_IDENTITY_SECRET','AUDIT_CLINIC_SECRET','AUDIT_DOCTOR_SECRET','AUDIT_CATALOG_SECRET','NOTIFICATION_APPOINTMENT_SECRET','NOTIFICATION_BILLING_SECRET','PATIENT_APPOINTMENT_SECRET','PATIENT_BILLING_SECRET','CLINIC_IAM_DIRECTORY_SECRET','CLINIC_DOCTOR_SERVICE_SECRET','CLINIC_CATALOG_SERVICE_SECRET','CLINIC_APPOINTMENT_SERVICE_SECRET','CLINIC_SECURITY_PATIENT_SERVICE_SECRET','CLINIC_SECURITY_ENCOUNTER_SERVICE_SECRET','ABSENCE_RELAY_SECRET','APPOINTMENT_SECURITY_ABSENCE_SECRET','PATIENT_SECURITY_ENCOUNTER_SECRET','DOCTOR_SECURITY_ENCOUNTER_SECRET','APPOINTMENT_SECURITY_ENCOUNTER_SECRET','ENCOUNTER_SERVICE_SECRET','MEDICAL_SERVICE_SECRET','BILLING_SERVICE_SECRET','ENCOUNTER_SECURITY_BILLING_SECRET','MEDICAL_SECURITY_BILLING_SECRET','APPOINTMENT_SECURITY_BILLING_SECRET','BILLING_CHARGES_MEDICAL_SECRET','BILLING_CHARGES_ENCOUNTER_SECRET','APPOINTMENT_WORKLOAD_SECRET','IAM_WORKLOAD_INBOUND_SECRET','IAM_CLINIC_INBOUND_SECRET','IAM_CLINIC_OUTBOUND_SECRET')){$taskEnv[$taskKey]=$taskPeer}
 foreach($taskLink in @(
  @('PROJECTION_RELAY_SEARCH_URL','search'),@('APPOINTMENT_RELAY_NOTIFICATION_URL','notification'),@('APPOINTMENT_RELAY_AUDIT_URL','audit'),@('ENCOUNTER_RELAY_AUDIT_URL','audit'),@('MEDICAL_RELAY_AUDIT_URL','audit'),@('BILLING_RELAY_AUDIT_URL','audit'),
  @('APPOINTMENT_PATIENT_URL','patient'),@('APPOINTMENT_DOCTOR_URL','doctor'),@('APPOINTMENT_CATALOG_URL','catalog'),@('ABSENCE_RELAY_APPOINTMENT_URL','appointment'),
  @('ENCOUNTER_PATIENT_URL','patient'),@('ENCOUNTER_DOCTOR_URL','doctor'),@('ENCOUNTER_APPOINTMENT_URL','appointment'),@('ENCOUNTER_MEDICAL_URL','medical'),
  @('BILLING_PATIENT_URL','patient'),@('CLINIC_PATIENT_URL','patient'),@('ENCOUNTER_PORTAL_PATIENT_URL','patient'),@('MEDICAL_PORTAL_PATIENT_URL','patient'),
  @('APPOINTMENT_FOLLOW_UP_ENCOUNTER_URL','encounter'),@('APPOINTMENT_FOLLOW_UP_MEDICAL_URL','medical'),@('BILLING_NOTIFICATION_PATIENT_URL','patient'),@('BILLING_NOTIFICATION_NOTIFICATION_URL','notification'),
  @('MEDICAL_CHARGES_BILLING_URL','billing'),@('ENCOUNTER_CHARGES_BILLING_URL','billing'),@('MEDICAL_ENCOUNTER_URL','encounter'),@('MEDICAL_CATALOG_URL','catalog'),
  @('BILLING_ENCOUNTER_URL','encounter'),@('BILLING_MEDICAL_URL','medical'),@('BILLING_APPOINTMENT_URL','appointment'),@('IAM_LEGACY_IDENTITY_URL','auth')
 )){$taskEnv[$taskLink[0]]="http://127.0.0.1:$($taskPorts[$taskLink[1]])/modules/$($taskLink[1])"}
 foreach($taskKey in @('APPOINTMENT_RELAY_ENABLED','ENCOUNTER_RELAY_ENABLED','MEDICAL_RELAY_ENABLED','BILLING_RELAY_ENABLED','ABSENCE_RELAY_ENABLED','PATIENT_RECEPTION_ENABLED','BILLING_NOTIFICATION_ENABLED','BILLING_CHARGES_ENABLED','MEDICAL_CHARGES_ENABLED','ENCOUNTER_CHARGES_ENABLED')){$taskEnv[$taskKey]='true'}
 # Publication is enabled for the locally bound clinic; clinical release and
 # online payment retain their disabled defaults.
 $taskEnv.CLINIC_PUBLICATION_ENABLED='true';$taskEnv.PROJECTION_RELAY_SEARCH_URL="http://127.0.0.1:$($taskPorts.search)/modules/search";$taskEnv.PROJECTION_RELAY_REFRESH_MS='60000';$taskEnv.IAM_JWT_SECRET=$taskConfig.userSecret
 return $taskEnv
}
