// @vitest-environment jsdom
import { beforeEach,afterEach,it,expect,vi } from 'vitest';
import { render,screen,cleanup } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { CashierPanel } from '../components/CashierPanel';
import * as api from '../api/billing';
import { contexts } from '../api/reception';
import { signIn,RequestError } from '../api/booking';
vi.mock('../api/billing',()=>({directory:vi.fn(),current:vi.fn(),visits:vi.fn(),bills:vi.fn(),shifts:vi.fn(),receipts:vi.fn(),issue:vi.fn(),open:vi.fn(),collect:vi.fn(),adjust:vi.fn(),submit:vi.fn(),approve:vi.fn()}));
vi.mock('../api/reception',()=>({contexts:vi.fn()}));
vi.mock('../api/booking',async original=>({...await original<typeof import('../api/booking')>(),signIn:vi.fn()}));
vi.mock('../api/idempotency',()=>({stableOperationKey:vi.fn(async()=>crypto.randomUUID())}));
const scope={token:'synthetic-token',clinic:'clinic',branch:'branch'};
const bill={id:'bill',encounterId:'visit',patientId:'patient',currency:'VND',subtotalVnd:100000,adjustmentVnd:0,paidVnd:0,remainingVnd:100000,status:'ISSUED',version:0,lines:[{chargeId:'charge',sourceType:'MEDICAL_ORDER',sourceId:'order',name:'Synthetic performed service',amountVnd:100000}]};
const shift={id:'shift',collectorUserId:'cashier',state:'OPEN',version:0,expectedCashVnd:null,expectedBankVnd:null,expectedPosVnd:null,declaredCashVnd:null,declaredBankVnd:null,declaredPosVnd:null,varianceVnd:null,approvedBy:null};
const receipt={id:'receipt',billId:'bill',shiftId:'shift',collectorUserId:'cashier',amountVnd:40000,currency:'VND',method:'CASH',externalRef:null,receiptCode:'RCT-SYN-001',createdAt:'2026-10-01T14:00:00Z',label:'BIÊN NHẬN NỘI BỘ — KHÔNG PHẢI HÓA ĐƠN THUẾ'};
beforeEach(()=>{vi.resetAllMocks();vi.mocked(signIn).mockResolvedValue({data:{accessToken:'synthetic-token'}});vi.mocked(contexts).mockResolvedValue([{membershipId:'m',clinicId:'clinic',role:'CASHIER',allBranches:false,branchIds:['branch'],version:1}]);vi.mocked(api.directory).mockResolvedValue({id:'clinic',name:'Synthetic Clinic',branches:[{id:'branch',name:'Synthetic Branch',active:true},{id:'other',name:'Other granted branch',active:true}]});vi.mocked(api.current).mockResolvedValue({userId:'cashier'});vi.mocked(api.visits).mockResolvedValue([{id:'visit',patientId:'patient',appointmentId:null,status:'CLOSED',medicalCaseVersion:7,visitCode:'S2-20261001-0001'}]);vi.mocked(api.bills).mockResolvedValue([bill]);vi.mocked(api.shifts).mockResolvedValue([shift]);vi.mocked(api.receipts).mockResolvedValue([]);});
afterEach(cleanup);
it('rejects the requested clinic after losing its grant even when another clinic is allowed',async()=>{const previous=location.href;history.replaceState(null,'','/workspace?view=billing&clinicId=revoked-clinic');try{const user=userEvent.setup();render(<CashierPanel/>);await user.type(screen.getByLabelText('Email thu ngân'),'cashier@example.invalid');await user.type(screen.getByLabelText('Mật khẩu thu ngân'),'synthetic-password');await user.click(screen.getByRole('button',{name:'Đăng nhập thu phí'}));await screen.findByRole('alert');expect(api.directory).not.toHaveBeenCalled();expect(api.current).not.toHaveBeenCalled();expect(screen.queryByLabelText('Địa điểm thu phí')).toBeNull();}finally{history.replaceState(null,'',previous);}});
async function desk(){const user=userEvent.setup();render(<CashierPanel/>);await user.type(screen.getByLabelText('Email thu ngân'),'cashier@example.invalid');await user.type(screen.getByLabelText('Mật khẩu thu ngân'),'synthetic-password');await user.click(screen.getByRole('button',{name:'Đăng nhập thu phí'}));await user.selectOptions(await screen.findByLabelText('Địa điểm thu phí'),'branch');await user.selectOptions(await screen.findByLabelText('Phiếu thu'),'bill');await user.selectOptions(screen.getByLabelText('Ca thu'),'shift');await user.type(screen.getByLabelText('Lý do lập phiếu hoặc xử lý'),'Synthetic collection');await user.type(screen.getByLabelText('Số tiền VND'),'40000');return user;}
it('collects a partial onsite payment with server version and an accurately labeled internal receipt',async()=>{vi.mocked(api.collect).mockResolvedValue(receipt);const user=await desk();vi.mocked(api.bills).mockResolvedValue([{...bill,paidVnd:40000,remainingVnd:60000,version:1,status:'PARTIALLY_PAID'}]);await user.click(screen.getByRole('button',{name:'Ghi nhận tiền đã nhận'}));await screen.findByRole('heading',{name:receipt.label});expect(api.collect).toHaveBeenCalledWith(scope,'bill',{expectedVersion:0,shiftId:'shift',amountVnd:40000,method:'CASH',externalRef:null,reason:'Synthetic collection'},expect.any(String));expect(api.adjust).not.toHaveBeenCalled();expect(screen.queryByRole('button',{name:'Duyệt giảm khoản phải thu'})).toBeNull();expect(screen.getByLabelText('Số tiền VND')).toHaveProperty('value','');});
it('retains the exact amount, version and key after an unknown collection response',async()=>{vi.mocked(api.collect).mockRejectedValueOnce(new Error('Synthetic response lost')).mockResolvedValueOnce(receipt);const user=await desk();await user.click(screen.getByRole('button',{name:'Ghi nhận tiền đã nhận'}));await screen.findByRole('alert');expect(screen.getByLabelText('Số tiền VND').closest('fieldset')?.disabled).toBe(true);await user.click(screen.getByRole('button',{name:'Thử lại thu phí đang chờ'}));await screen.findByRole('heading',{name:receipt.label});expect(vi.mocked(api.collect).mock.calls[0]).toEqual(vi.mocked(api.collect).mock.calls[1]);});
it('keeps acknowledged collection when a later balance refresh fails and does not reissue it',async()=>{vi.mocked(api.collect).mockResolvedValue(receipt);const user=await desk();vi.mocked(api.bills).mockRejectedValueOnce(new Error('Synthetic balance refresh failed'));await user.click(screen.getByRole('button',{name:'Ghi nhận tiền đã nhận'}));await screen.findByRole('heading',{name:receipt.label});expect((await screen.findByRole('alert')).textContent).toContain('Thao tác đã được ghi nhận');expect(screen.queryByRole('button',{name:'Thử lại thu phí đang chờ'})).toBeNull();expect(screen.getByLabelText('Số tiền VND').closest('fieldset')?.disabled).toBe(true);await user.click(screen.getByRole('button',{name:'Tải lại thu phí'}));expect(api.collect).toHaveBeenCalledTimes(1);});
it('rejects a fractional VND amount or missing confirmed POS reference before sending money mutation',async()=>{const user=await desk();await user.clear(screen.getByLabelText('Số tiền VND'));await user.type(screen.getByLabelText('Số tiền VND'),'0.5');await user.click(screen.getByRole('button',{name:'Ghi nhận tiền đã nhận'}));await screen.findByRole('alert');expect(api.collect).not.toHaveBeenCalled();await user.clear(screen.getByLabelText('Số tiền VND'));await user.type(screen.getByLabelText('Số tiền VND'),'40000');await user.selectOptions(screen.getByLabelText('Hình thức nhận tiền'),'POS');await user.click(screen.getByRole('button',{name:'Ghi nhận tiền đã nhận'}));await screen.findByText('Nhập mã giao dịch đã xác nhận tại quầy.');expect(api.collect).not.toHaveBeenCalled();});
it('submits counted shift totals and preserves the server variance for separate approval',async()=>{vi.mocked(api.submit).mockResolvedValue({...shift,state:'SUBMITTED',version:1,varianceVnd:-100,expectedCashVnd:40000,expectedBankVnd:0,expectedPosVnd:0});const user=await desk();vi.mocked(api.shifts).mockResolvedValue([{...shift,state:'SUBMITTED',version:1,varianceVnd:-100,expectedCashVnd:40000}]);await user.clear(screen.getByLabelText('Tiền mặt kiểm đếm VND'));await user.type(screen.getByLabelText('Tiền mặt kiểm đếm VND'),'39900');await user.click(screen.getByRole('button',{name:'Gửi chốt ca'}));await screen.findByText(/Chênh lệch kiểm đếm/);expect(api.submit).toHaveBeenCalledWith(scope,'shift',expect.objectContaining({expectedVersion:0,declaredCashVnd:39900,declaredBankVnd:0,declaredPosVnd:0}),expect.any(String));expect(screen.queryByRole('button',{name:'Duyệt chốt ca và chênh lệch'})).toBeNull();});
it('clears previous branch bills and receipts when the new branch is denied',async()=>{const user=await desk();vi.mocked(api.visits).mockRejectedValueOnce(new RequestError('Synthetic branch revoked',403));await user.selectOptions(screen.getByLabelText('Địa điểm thu phí'),'other');await screen.findByText('Synthetic branch revoked');expect(screen.queryByText('Khoản phải thu')).toBeNull();expect(screen.queryByRole('button',{name:'Ghi nhận tiền đã nhận'})).toBeNull();});
