// @vitest-environment jsdom
import { afterEach,beforeEach,expect,it,vi } from 'vitest';
import { act,cleanup,fireEvent,render,screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { ConfigurationPanel,type ConfigurationMode } from '../components/ConfigurationPanel';
import { AccountSettingsPanel } from '../components/AccountSettingsPanel';
import { RequestError,signIn } from '../api/booking';
import { contexts } from '../api/reception';
import * as api from '../api/configuration';
vi.mock('../api/booking',async original=>({...await original<typeof import('../api/booking')>(),signIn:vi.fn()}));
vi.mock('../api/reception',()=>({contexts:vi.fn()}));
vi.mock('../api/configuration',()=>({current:vi.fn(),mine:vi.fn(),clinic:vi.fn(),createClinic:vi.fn(),saveClinic:vi.fn(),saveBranch:vi.fn(),submitClinic:vi.fn(),bootstrap:vi.fn(),memberships:vi.fn(),invite:vi.fn(),grant:vi.fn(),revokeGrant:vi.fn(),revoke:vi.fn(),affiliations:vi.fn(),schedules:vi.fn(),saveAffiliation:vi.fn(),saveSchedule:vi.fn(),offerings:vi.fn(),assignments:vi.fn(),prices:vi.fn(),saveOffering:vi.fn(),saveAssignment:vi.fn(),addPrice:vi.fn(),ownInvitations:vi.fn(),acceptInvitation:vi.fn(),revokeSession:vi.fn()}));
const clinic:api.Clinic={id:'clinic',ownerUserId:'owner',name:'Synthetic owned clinic',slug:'synthetic-owned',reviewStatus:'DRAFT',publicationStatus:'UNPUBLISHED',evidenceVerified:false,version:3,contactName:'',contactEmail:'',contactPhone:'',license:null,branches:[{id:'branch',name:'Synthetic local point',address:'Synthetic address',openingHours:'08-17',active:true}]};
const offering:api.Offering={id:'offering',code:'SYN',name:'Synthetic source offering',description:null,specialtyCode:null,active:true,version:4};
beforeEach(()=>{vi.resetAllMocks();sessionStorage.clear();vi.mocked(signIn).mockResolvedValue({data:{accessToken:'synthetic-owner-token'}});vi.mocked(contexts).mockResolvedValue([{membershipId:'m',clinicId:'clinic',role:'CLINIC_OWNER',allBranches:true,branchIds:[],version:1}]);vi.mocked(api.current).mockResolvedValue({userId:'owner',legacyRoles:['ROLE_USER'],platformOperator:false});vi.mocked(api.mine).mockResolvedValue([clinic]);vi.mocked(api.clinic).mockResolvedValue(clinic);vi.mocked(api.offerings).mockResolvedValue([offering]);vi.mocked(api.assignments).mockResolvedValue([{id:'assignment',offering,durationMinutes:30,active:true,publicVisible:false,version:2}]);vi.mocked(api.prices).mockResolvedValue([{id:'old-price',amountVnd:100000,currency:'VND',effectiveFrom:'2026-10-01T00:00:00Z',taxPolicyCode:null,discountPolicyCode:null}]);vi.mocked(api.memberships).mockResolvedValue([]);vi.mocked(api.ownInvitations).mockResolvedValue([]);});
afterEach(cleanup);
async function login(mode:ConfigurationMode){const user=userEvent.setup();render(<ConfigurationPanel mode={mode}/>);await user.type(screen.getByLabelText('Email cấu hình'),'synthetic@example.invalid');await user.type(screen.getByLabelText('Mật khẩu cấu hình'),'synthetic-password');await user.click(screen.getByRole('button',{name:'Đăng nhập cấu hình'}));await screen.findByRole('button',{name:'Tải lại dữ liệu cấu hình'});return user;}
async function priceForm(){const user=await login('catalog');await screen.findByLabelText('Dịch vụ cấu hình');await user.selectOptions(screen.getByLabelText('Dịch vụ cấu hình'),'offering');await screen.findByRole('heading',{name:'Phiên bản giá'});await user.type(screen.getByLabelText('Giá mới (VND)'),'120000');fireEvent.change(screen.getByLabelText('Giá có hiệu lực từ'),{target:{value:'2026-10-03T08:00'}});return user;}
it('appends a price version in the granted scope and leaves the prior source history visible',async()=>{
 vi.mocked(api.addPrice).mockResolvedValue({id:'new-price',amountVnd:120000,currency:'VND',effectiveFrom:'2026-10-03T01:00:00Z',taxPolicyCode:null,discountPolicyCode:null});const user=await priceForm();await user.click(screen.getByRole('button',{name:'Thêm phiên bản giá'}));await screen.findByText('Đã lưu tại dịch vụ nguồn.');expect(api.addPrice).toHaveBeenCalledWith({token:'synthetic-owner-token',clinic:'clinic',branch:'branch'},{offeringId:'offering',amountVnd:120000,effectiveFrom:new Date('2026-10-03T08:00').toISOString()});expect(screen.getByText(/100.000/)).toBeTruthy();
});
it('freezes an unknown write across a remount until a source read and explicit reconciliation',async()=>{
 vi.mocked(api.addPrice).mockRejectedValue(new RequestError('Synthetic lost response',0));const user=await priceForm();await user.click(screen.getByRole('button',{name:'Thêm phiên bản giá'}));await screen.findByText(/Chưa xác định được kết quả lưu/);await user.click(screen.getByRole('button',{name:'Thêm phiên bản giá'}));expect(api.addPrice).toHaveBeenCalledTimes(1);cleanup();const next=await login('catalog');await screen.findByText(/Chưa xác định được kết quả lưu/);expect(screen.queryByRole('button',{name:'Đã đối chiếu dữ liệu nguồn'})).toBeNull();await next.click(screen.getByRole('button',{name:'Tải lại dữ liệu cấu hình'}));await screen.findByRole('button',{name:'Đã đối chiếu dữ liệu nguồn'});await next.click(screen.getByRole('button',{name:'Đã đối chiếu dữ liệu nguồn'}));expect(screen.queryByText(/Chưa xác định được kết quả lưu/)).toBeNull();expect(api.addPrice).toHaveBeenCalledTimes(1);expect(sessionStorage.length).toBe(0);
});
it('discards a late profile mutation after logout and sends the server version when saving',async()=>{
 let resolve!:(c:api.Clinic)=>void;vi.mocked(api.saveClinic).mockReturnValue(new Promise(r=>{resolve=r;}));const user=await login('profile');await user.click(screen.getByRole('button',{name:'Lưu hồ sơ phòng khám'}));expect(api.saveClinic).toHaveBeenCalledWith({token:'synthetic-owner-token',clinic:'clinic',branch:'branch'},expect.objectContaining({expectedVersion:3}));await user.click(screen.getByRole('button',{name:'Đăng xuất cấu hình'}));await act(async()=>resolve({...clinic,name:'Late response'}));expect(screen.queryByText('Late response')).toBeNull();expect(screen.getByRole('button',{name:'Đăng nhập cấu hình'})).toBeTruthy();
});
it('recovers an existing creator draft without creating another clinic before IAM bootstrap',async()=>{
 vi.mocked(contexts).mockResolvedValue([]);const user=await login('profile');await screen.findByText(/Quyền chủ cơ sở đang chờ liên kết/);expect(screen.queryByRole('button',{name:'Tạo hồ sơ phòng khám'})).toBeNull();await user.click(screen.getByRole('button',{name:'Lưu hồ sơ phòng khám'}));expect(api.saveClinic).not.toHaveBeenCalled();expect(api.createClinic).not.toHaveBeenCalled();
});
it('accepts only the displayed own invitation and reloads authoritative active contexts',async()=>{
 const invitation:api.Membership={id:'own-invite',userId:'owner',clinicId:'clinic',role:'DOCTOR',status:'INVITED',allBranches:false,version:0,branchIds:['branch']};vi.mocked(api.ownInvitations).mockResolvedValueOnce([invitation]).mockResolvedValue([]);vi.mocked(api.acceptInvitation).mockResolvedValue({...invitation,status:'ACTIVE'});const user=userEvent.setup();render(<AccountSettingsPanel/>);await user.type(screen.getByLabelText('Email tài khoản'),'synthetic@example.invalid');await user.type(screen.getByLabelText('Mật khẩu tài khoản'),'synthetic-password');await user.click(screen.getByRole('button',{name:'Đăng nhập tài khoản'}));await screen.findByRole('button',{name:'Chấp nhận lời mời DOCTOR'});await user.click(screen.getByRole('button',{name:'Chấp nhận lời mời DOCTOR'}));await screen.findByText('Không có lời mời đang chờ.');expect(api.acceptInvitation).toHaveBeenCalledWith('synthetic-owner-token','own-invite');expect(api.current).toHaveBeenCalledTimes(2);
});
