// @vitest-environment jsdom
import { afterEach,beforeEach,expect,it,vi } from 'vitest';
import { render,screen,cleanup,within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { ReceptionPanel } from '../components/ReceptionPanel';
import * as api from '../api/reception';
import { signIn, RequestError } from '../api/booking';
import { forgetOperationKey } from '../api/idempotency';
vi.mock('../api/reception',()=>({contexts:vi.fn(),directory:vi.fn(),doctors:vi.fn(),points:vi.fn(),arrivals:vi.fn(),recoverArrival:vi.fn(),createPoint:vi.fn(),suggestions:vi.fn(),provisional:vi.fn(),review:vi.fn(),appointments:vi.fn(),walkIn:vi.fn(),checkIn:vi.fn(),queue:vi.fn(),queuePage:vi.fn(),move:vi.fn(),doctorAbsences:vi.fn(),reportAbsence:vi.fn(),applyAbsence:vi.fn()}));
vi.mock('../api/booking',async importOriginal=>({...await importOriginal<typeof import('../api/booking')>(),signIn:vi.fn()}));
vi.mock('../api/idempotency',()=>({stableOperationKey:vi.fn(async()=>crypto.randomUUID()),forgetOperationKey:vi.fn()}));
const patient={patientId:'patient',clinicPatientLinkId:'link',patientCode:'PT-SYN',fullName:'Synthetic Patient',dateOfBirth:null,phoneLast4:'4567',status:'PROVISIONAL',version:0};
const ticket={id:'ticket',visitId:'visit',servicePointId:'point',date:'2026-10-01',number:1,code:'R1-20261001-0001',state:'WAITING',version:0};
beforeEach(()=>{vi.resetAllMocks();vi.mocked(signIn).mockResolvedValue({data:{accessToken:'synthetic-token'}});vi.mocked(api.contexts).mockResolvedValue([{membershipId:'m',clinicId:'clinic',role:'RECEPTIONIST',allBranches:false,branchIds:['branch'],version:1}]);vi.mocked(api.directory).mockResolvedValue({id:'clinic',name:'Synthetic Clinic',branches:[{id:'branch',name:'Synthetic Branch',active:true}]});vi.mocked(api.doctors).mockResolvedValue([{practitionerId:'doctor',displayName:'Synthetic Doctor',active:true,effectiveFrom:'2020-01-01',effectiveUntil:null}]);vi.mocked(api.arrivals).mockResolvedValue([]);vi.mocked(api.points).mockResolvedValue([{id:'point',code:'R1',name:'Synthetic Room',active:true}]);vi.mocked(api.suggestions).mockResolvedValue([patient]);vi.mocked(api.provisional).mockResolvedValue(patient);vi.mocked(api.walkIn).mockResolvedValue({id:'visit',appointmentId:null,status:'WAITING',version:0,ticket});vi.mocked(api.queuePage).mockResolvedValue({items:[ticket],nextAfterNumber:null});});
afterEach(cleanup);
it('labels a closed arrival without a live ticket as closed rather than pending',async()=>{
 vi.mocked(api.arrivals).mockResolvedValue([{operation:'walk-in',createdAt:'2026-10-02T00:00:00Z',visit:{id:'closed',appointmentId:null,status:'CLOSED',version:4,ticket:null}}]);
 await desk();await screen.findByRole('heading',{name:'Lượt đã đóng'});expect(screen.queryByText('Check-in đang chờ xác nhận')).toBeNull();expect(screen.getByText(/Walk-in · Đã đóng/)).toBeTruthy();
});
it('loads queue continuation from its server cursor while retaining the first page',async()=>{
 const second={...ticket,id:'second-ticket',visitId:'second-visit',number:2,code:'R1-SECOND'};vi.mocked(api.queuePage).mockResolvedValueOnce({items:[ticket],nextAfterNumber:1}).mockResolvedValueOnce({items:[second],nextAfterNumber:null});const user=await desk();await user.selectOptions(screen.getByLabelText('Điểm phục vụ'),'point');await user.click(screen.getByRole('button',{name:'Tải lại hàng đợi'}));await screen.findByRole('heading',{name:ticket.code});await user.click(screen.getByRole('button',{name:'Tải thêm hàng đợi'}));await screen.findByRole('heading',{name:'R1-SECOND'});expect(screen.getByRole('heading',{name:ticket.code})).toBeTruthy();expect(vi.mocked(api.queuePage).mock.calls[1][3]).toBe(1);expect(screen.queryByRole('button',{name:'Tải thêm hàng đợi'})).toBeNull();
});
async function desk(){const user=userEvent.setup();render(<ReceptionPanel/>);await user.type(screen.getByLabelText('Email nhân viên'),'synthetic@example.invalid');await user.type(screen.getByLabelText('Mật khẩu nhân viên'),'synthetic-password');await user.click(screen.getByRole('button',{name:'Đăng nhập tiếp nhận'}));await user.selectOptions(await screen.findByLabelText('Địa điểm tiếp nhận'),'branch');await within(screen.getByLabelText('Bác sĩ tiếp nhận')).findByRole('option',{name:'Synthetic Doctor'});return user;}
it('requires explicit patient selection and makes walk-in without an appointment',async()=>{const user=await desk();expect((screen.getByRole('button',{name:'Tiếp nhận walk-in'}) as HTMLButtonElement).disabled).toBe(true);await user.type(screen.getByLabelText('Số điện thoại tìm hồ sơ'),'0001234567');await user.click(screen.getByRole('button',{name:'Tìm gợi ý hồ sơ'}));await screen.findByText('Synthetic Patient');expect(api.walkIn).not.toHaveBeenCalled();await user.click(screen.getByRole('button',{name:'Đã đối chiếu — chọn hồ sơ'}));await user.type(screen.getByLabelText('Lý do tiếp nhận hoặc điều phối'),'Synthetic intake');await user.selectOptions(screen.getByLabelText('Điểm phục vụ'),'point');await user.selectOptions(screen.getByLabelText('Bác sĩ tiếp nhận'),'doctor');await user.click(screen.getByRole('button',{name:'Tiếp nhận walk-in'}));await screen.findByText(/Đã tiếp nhận walk-in/);expect(api.walkIn).toHaveBeenCalledWith(expect.objectContaining({clinic:'clinic',branch:'branch'}),'patient','doctor','point','Synthetic intake',expect.any(String));expect(api.checkIn).not.toHaveBeenCalled();expect((screen.getByRole('button',{name:'Tiếp nhận walk-in'}) as HTMLButtonElement).disabled).toBe(true);await user.click(screen.getByRole('button',{name:'Bắt đầu lượt walk-in mới'}));expect(forgetOperationKey).toHaveBeenCalledWith('walk-in',expect.objectContaining({patientId:'patient'}));expect(screen.queryByText(/Hồ sơ đã chọn/)).toBeNull();});
it('keeps uncertain walk-in retry key and exposes a recoverable error',async()=>{vi.mocked(api.walkIn).mockRejectedValueOnce(new Error('Synthetic uncertain outcome'));const user=await desk();await user.type(screen.getByLabelText('Họ tên bệnh nhân'),'Synthetic Patient');await user.type(screen.getByLabelText('Lý do tiếp nhận hoặc điều phối'),'Synthetic intake');await user.click(screen.getByRole('button',{name:'Tạo hồ sơ walk-in mới'}));await screen.findByText(/Hồ sơ đã chọn/);await user.selectOptions(screen.getByLabelText('Điểm phục vụ'),'point');await user.selectOptions(screen.getByLabelText('Bác sĩ tiếp nhận'),'doctor');await user.click(screen.getByRole('button',{name:'Tiếp nhận walk-in'}));await screen.findByRole('alert');expect((screen.getByLabelText('Lý do tiếp nhận hoặc điều phối') as HTMLTextAreaElement).disabled).toBe(false);expect((screen.getByLabelText('Lý do tiếp nhận hoặc điều phối') as HTMLTextAreaElement).closest('fieldset')?.disabled).toBe(true);await user.click(screen.getByRole('button',{name:'Thử lại lượt tiếp nhận đang chờ'}));await screen.findByText(/Đã tiếp nhận walk-in/);expect(vi.mocked(api.walkIn).mock.calls[0]).toEqual(vi.mocked(api.walkIn).mock.calls[1]);});
it('keeps a confirmed arrival when only the queue refresh fails',async()=>{
 vi.mocked(api.queuePage).mockRejectedValueOnce(new RequestError('Synthetic queue forbidden',403));
 const user=await desk();await user.type(screen.getByLabelText('Họ tên bệnh nhân'),'Synthetic Patient');await user.type(screen.getByLabelText('Lý do tiếp nhận hoặc điều phối'),'Synthetic intake');await user.click(screen.getByRole('button',{name:'Tạo hồ sơ walk-in mới'}));await screen.findByText(/Hồ sơ đã chọn/);await user.selectOptions(screen.getByLabelText('Điểm phục vụ'),'point');await user.selectOptions(screen.getByLabelText('Bác sĩ tiếp nhận'),'doctor');await user.click(screen.getByRole('button',{name:'Tiếp nhận walk-in'}));await screen.findByRole('alert');expect(screen.getByText(/Đã tiếp nhận walk-in/)).toBeTruthy();expect(screen.queryByRole('button',{name:'Thử lại lượt tiếp nhận đang chờ'})).toBeNull();expect(api.walkIn).toHaveBeenCalledTimes(1);expect((screen.getByRole('button',{name:'Bắt đầu lượt walk-in mới'}) as HTMLButtonElement).disabled).toBe(false);
});
it('recovers a server pending arrival after losing browser inputs without creating another visit',async()=>{
 const pending={id:'server-visit',appointmentId:'booking',status:'ARRIVAL_PENDING',version:0,ticket:null};vi.mocked(api.arrivals).mockResolvedValue([{operation:'check-in',createdAt:new Date().toISOString(),visit:pending}]);vi.mocked(api.recoverArrival).mockResolvedValue({...pending,status:'WAITING',version:1,ticket});
 const user=await desk();await screen.findByText('Check-in đang chờ xác nhận');await user.type(screen.getByLabelText('Lý do tiếp nhận hoặc điều phối'),'Synthetic reload review');await user.click(screen.getByRole('button',{name:'Tiếp tục check-in đang chờ'}));await screen.findByText(/Đã xác nhận lượt tiếp nhận từ server/);expect(api.recoverArrival).toHaveBeenCalledWith(expect.objectContaining({clinic:'clinic',branch:'branch'}),pending,'Synthetic reload review');expect(api.walkIn).not.toHaveBeenCalled();expect(api.checkIn).not.toHaveBeenCalled();
});
it('freezes uncertain source absence and reports incomplete affected-booking work',async()=>{
 const absence={id:'absence',doctorId:'doctor',startsAt:'2026-10-01T03:00:00.000Z',endsAt:'2026-10-01T04:00:00.000Z'};vi.mocked(api.reportAbsence).mockRejectedValueOnce(new Error('Synthetic uncertain source')).mockResolvedValueOnce(absence);vi.mocked(api.applyAbsence).mockResolvedValue({recorded:5,retryRequired:['retry'],hasMore:true});
 const user=await desk();await user.type(screen.getByLabelText('Lý do tiếp nhận hoặc điều phối'),'Synthetic absence');await user.click(screen.getByText('Báo bác sĩ vắng theo khoảng lịch'));await user.selectOptions(screen.getByLabelText('Bác sĩ báo vắng'),'doctor');await user.type(screen.getByLabelText('Bắt đầu vắng (giờ Việt Nam)'),'2026-10-01T10:00');await user.type(screen.getByLabelText('Kết thúc vắng (giờ Việt Nam)'),'2026-10-01T11:00');await user.click(screen.getByRole('button',{name:'Ghi khoảng vắng có lý do'}));await screen.findByRole('alert');await user.click(screen.getByRole('button',{name:'Thử lại báo vắng đang chờ'}));await screen.findByText(/Đã ghi khoảng vắng/);expect(vi.mocked(api.reportAbsence).mock.calls[0]).toEqual(vi.mocked(api.reportAbsence).mock.calls[1]);expect(vi.mocked(api.reportAbsence).mock.calls[0][2].startsAt).toBe(absence.startsAt);await user.click(screen.getByRole('button',{name:'Ghi ngoại lệ các lịch bị ảnh hưởng'}));await screen.findByText(/1 lịch cần kiểm tra và thử lại/);expect(screen.getByText(/Còn lịch cần ghi ở nhóm tiếp theo/)).toBeTruthy();
});

