import { test,expect } from '@playwright/test';
import path from 'node:path';
const evidence=path.resolve('../../../docs/audits/clinic-v2/P05-S3/medical-verification');
test('doctor draft, lab result and doctor review stay separate on desktop and mobile',async({page,context})=>{
 const note={reasonForVisit:'',medicalHistory:'',allergies:'',vitals:'',examination:'',preliminaryDiagnosis:'',conclusion:'',instructions:'',followUpDate:null};
 let draft={encounterId:'visit',documentVersion:0,caseVersion:0,status:'DRAFT',content:note};let order:any=null;const writes:{path:string;key?:string}[]=[];
 let visit={id:'visit',appointmentId:null,status:'IN_PROGRESS',version:2,ticket:{id:'ticket',visitId:'visit',servicePointId:'point',date:'2026-10-01',number:1,code:'R1-20261001-0001',state:'SERVING',version:2} as any};
 await context.route('**/s1/**',async route=>{
  const req=route.request(),url=req.url(),body=req.postDataJSON();const isLab=req.headers().authorization==='Bearer synthetic-lab-token';let json:any={};
  if(url.endsWith('/auth/login'))json={data:{accessToken:body.email.startsWith('lab')?'synthetic-lab-token':'synthetic-doctor-token'}};
  else if(url.endsWith('/me/current'))json={userId:isLab?'lab':'doctor',legacyRoles:['ROLE_USER'],platformOperator:false};
  else if(url.endsWith('/me/contexts'))json=[{membershipId:'m',clinicId:'clinic',role:isLab?'LAB':'DOCTOR',allBranches:false,branchIds:['branch'],version:1}];
  else if(url.endsWith('/care-directory')||url.endsWith('/lab-directory'))json={id:'clinic',name:'Synthetic Clinic',branches:[{id:'branch',name:'Synthetic Branch',active:true}]};
  else if(url.endsWith('/doctor/service-points'))json=[{id:'point',code:'R1',name:'Synthetic Room',active:true}];
  else if(url.endsWith('/doctor/worklist'))json=[visit];
  else if(url.endsWith('/doctor/visits/visit/complete')){expect(draft.status).toBe('VALIDATED');expect(body.medicalCaseVersion).toBe(draft.caseVersion);expect(body.expectedVersion).toBe(visit.version);writes.push({path:url,key:req.headers()['idempotency-key']});visit={...visit,status:'CLINICALLY_COMPLETED',version:visit.version+1,ticket:null};json=visit;}
  else if(url.endsWith('/doctor/visits/visit/close')){expect(visit.status).toBe('CLINICALLY_COMPLETED');expect(body.expectedVersion).toBe(visit.version);writes.push({path:url,key:req.headers()['idempotency-key']});visit={...visit,status:'CLOSED',version:visit.version+1};json=visit;}
  else if(url.endsWith('/offerings'))json=[{active:true,offering:{id:'offering',name:'Synthetic Lab',active:true}}];
  else if(url.endsWith('/visits/visit/draft')){
   if(req.method()==='PUT'){writes.push({path:url,key:req.headers()['idempotency-key']});expect(body.expectedDocumentVersion).toBe(draft.documentVersion);draft={...draft,documentVersion:draft.documentVersion+1,caseVersion:draft.caseVersion+1,content:body.content};}json=draft;
  }else if(url.endsWith('/visits/visit/orders')){
   if(req.method()==='POST'){writes.push({path:url,key:req.headers()['idempotency-key']});expect(body.offeringId).toBe('offering');order={id:'order',encounterId:'visit',offeringId:'offering',name:'Synthetic Lab',state:'ORDERED',version:0,resultVersion:0,result:null,acceptedBy:null,reviewedBy:null};draft.caseVersion++;json=order;}else json=order?[order]:[];
  }else if(url.endsWith('/lab/orders'))json=order?[order]:[];
  else if(url.includes('/orders/order/')){
   writes.push({path:url,key:req.headers()['idempotency-key']});expect(body.expectedVersion).toBe(order.version);order={...order,version:order.version+1};draft.caseVersion++;
   if(url.endsWith('/accept')){expect(isLab).toBe(true);order.state='ACCEPTED';order.acceptedBy='lab';}
   else if(url.endsWith('/process'))order.state='PROCESSING';
   else if(url.endsWith('/results')){expect(isLab).toBe(true);order.state='RESULTED';order.resultVersion++;order.result={id:'result',version:order.resultVersion,sourceRef:body.sourceRef,content:body.content,authorUserId:'lab',createdAt:'2026-10-01T14:00:00Z'};}
   else if(url.endsWith('/reviews')){expect(isLab).toBe(false);order.state='REVIEWED';order.reviewedBy='doctor';}
   json=order;
  }else if(url.endsWith('/visits/visit/validate')){expect(order.state).toBe('REVIEWED');writes.push({path:url,key:req.headers()['idempotency-key']});draft={...draft,status:'VALIDATED',caseVersion:draft.caseVersion+1};json=draft;}
  else throw new Error('Unexpected medical route '+url);
  await route.fulfill({json});
 });
 await page.goto('/workspace?view=doctor');await page.getByLabel('Email',{exact:true}).fill('doctor@example.invalid');await page.getByLabel('Mật khẩu',{exact:true}).fill('synthetic-password');await page.getByRole('button',{name:'Đăng nhập'}).click();await page.getByLabel('Địa điểm khám').selectOption('branch');await page.getByRole('button',{name:'Chọn lượt R1-20261001-0001',exact:true}).click();
 await page.getByLabel('Lý do khám',{exact:true}).fill('Synthetic private chief complaint');await page.getByLabel('Kết luận',{exact:true}).fill('Synthetic private conclusion');await page.getByLabel('Hướng dẫn',{exact:true}).fill('Synthetic private instructions');await page.getByRole('button',{name:'Lưu bản nháp',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Đã lưu bản nháp phiên bản 1.'})).toBeVisible();
 await page.getByLabel('Lý do lưu hoặc duyệt hồ sơ').fill('Synthetic clinical workflow');await page.getByLabel('Dịch vụ chỉ định').selectOption('offering');await page.getByRole('button',{name:'Tạo chỉ định',exact:true}).click();await expect(page.getByText('ORDERED',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Xác nhận nội dung chuyên môn'})).toBeDisabled();
 const lab=await context.newPage();await lab.goto('/workspace?view=lab');await lab.getByLabel('Email',{exact:true}).fill('lab@example.invalid');await lab.getByLabel('Mật khẩu',{exact:true}).fill('synthetic-password');await lab.getByRole('button',{name:'Đăng nhập'}).click();await lab.getByLabel('Địa điểm xét nghiệm').selectOption('branch');await lab.getByRole('button',{name:'Chọn chỉ định Synthetic Lab',exact:true}).click();await lab.getByLabel('Lý do xử lý xét nghiệm').fill('Synthetic work');await lab.getByRole('button',{name:'Nhận chỉ định',exact:true}).click();await lab.getByRole('button',{name:'Bắt đầu xử lý xét nghiệm',exact:true}).click();await lab.getByLabel('Nguồn kết quả',{exact:true}).fill('SYN-001');await lab.getByLabel('Nội dung kết quả',{exact:true}).fill('Synthetic private result');await expect(lab.getByRole('button',{name:'Cài đặt tài khoản',exact:true})).toBeDisabled();await expect(lab.getByLabel('Địa điểm xét nghiệm')).toBeDisabled();await expect(lab.getByRole('button',{name:'Đăng xuất',exact:true})).toBeDisabled();await lab.getByRole('button',{name:'Ghi phiên bản kết quả',exact:true}).click();await expect(lab.getByRole('button',{name:'Cài đặt tài khoản',exact:true})).toBeEnabled();await expect(lab.getByRole('status').filter({hasText:'Chờ bác sĩ duyệt'})).toBeVisible();await expect(lab.getByLabel('Kết luận',{exact:true})).toHaveCount(0);
 await lab.setViewportSize({width:375,height:812});expect(await lab.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(375);await lab.evaluate(()=>{(document.activeElement as HTMLElement)?.blur();window.scrollTo(0,0);});await lab.screenshot({path:path.join(evidence,'lab-mobile.png'),fullPage:true});
 await page.getByRole('button',{name:'Tải phiên bản để đối chiếu'}).click();await expect(page.getByText('Synthetic private result',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Duyệt kết quả Synthetic Lab',exact:true}).click();await expect(page.getByText('REVIEWED',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Xác nhận nội dung chuyên môn',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Hồ sơ chưa ký và chưa phát hành'})).toBeVisible();
 await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>{(document.activeElement as HTMLElement)?.blur();window.scrollTo(0,0);});await page.screenshot({path:path.join(evidence,'medical-desktop.png'),fullPage:true});
 await page.setViewportSize({width:375,height:812});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(375);await page.evaluate(()=>{(document.activeElement as HTMLElement)?.blur();window.scrollTo(0,0);});await page.screenshot({path:path.join(evidence,'medical-mobile.png'),fullPage:true});
 await page.getByLabel('Lý do chuyển trạng thái khám').fill('Synthetic unsigned completion');await page.getByRole('button',{name:'Hoàn tất chuyên môn',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Đã hoàn tất chuyên môn'})).toBeVisible();
 await page.getByLabel('Lý do chuyển trạng thái khám').fill('Synthetic operational closure');await page.getByRole('button',{name:'Đóng lượt khám',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Đã đóng lượt khám'})).toBeVisible();
 expect(writes.every(w=>!!w.key)).toBe(true);const storage=await page.evaluate(()=>JSON.stringify({...sessionStorage,...localStorage}));expect(storage).not.toContain('Synthetic private');expect(storage).not.toContain('synthetic-doctor-token');await lab.close();
});
