import {test,expect} from '@playwright/test';
import path from 'node:path';
const evidence=path.resolve('../../../docs/audits/clinic-v2/P05-S2');
test('supervisor recovery and prior-day queue continuation preserve original requests on mobile',async({page})=>{
 const pending={id:'pending',appointmentId:'booking',status:'ARRIVAL_PENDING',version:0,ticket:null};const old={id:'old',visitId:'old-visit',servicePointId:'point',date:'2000-01-01',number:1,code:'SYN-OLD',state:'WAITING',version:3};const requests:{operation:string;body:unknown;key:string|undefined}[]=[];
 await page.route('**/s1/**',async route=>{const req=route.request(),url=req.url();let json:unknown=[];
  if(url.endsWith('/auth/login'))json={data:{accessToken:'synthetic-token'}};
  else if(url.endsWith('/me/current'))json={userId:'fixture-user',legacyRoles:['ROLE_USER'],platformOperator:false};
  else if(url.endsWith('/me/contexts'))json=[{membershipId:'manager',clinicId:'clinic',role:'ADMIN',allBranches:false,branchIds:['branch'],version:1}];
  else if(url.endsWith('/reception-directory'))json={id:'clinic',name:'Synthetic Clinic',branches:[{id:'branch',name:'Synthetic Branch',active:true}]};
  else if(url.endsWith('/service-points'))json=[{id:'point',code:'R1',name:'Synthetic Room',active:true}];
  else if(url.includes('/pending-arrivals?'))json={items:[pending],nextAfter:null};
  else if(url.endsWith('/pending/recover')){requests.push({operation:'recovery',body:req.postDataJSON(),key:req.headers()['idempotency-key']});if(requests.filter(r=>r.operation==='recovery').length===1){await route.abort('failed');return;}json={...pending,status:'WAITING',version:2};}
  else if(url.includes('/queue/page?'))json={items:[old],nextAfterNumber:null};
  else if(url.endsWith('/old/roll-forward')){requests.push({operation:'roll',body:req.postDataJSON(),key:req.headers()['idempotency-key']});if(requests.filter(r=>r.operation==='roll').length===1){await route.abort('failed');return;}json={...old,id:'today',code:'SYN-TODAY',version:0};}
  await route.fulfill({json});
 });
 await page.setViewportSize({width:375,height:812});await page.goto('/workspace?view=reception');await page.getByLabel('Email',{exact:true}).fill('synthetic@example.invalid');await page.getByLabel('Mật khẩu',{exact:true}).fill('synthetic-password');await page.getByRole('button',{name:'Đăng nhập'}).click();await page.getByLabel('Địa điểm tiếp nhận').selectOption('branch');await page.getByRole('button',{name:'Tải lượt chờ của phòng khám'}).click();await page.getByLabel('Lý do quản lý phục hồi tiếp nhận').fill('Synthetic manager takeover');await page.getByRole('button',{name:'Phục hồi lượt pending'}).click();await expect(page.getByRole('button',{name:'Thử lại phục hồi đang chờ'})).toBeVisible();await expect(page.getByLabel('Địa điểm tiếp nhận')).toBeDisabled();await expect(page.getByRole('button',{name:'Cài đặt tài khoản',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Đăng xuất',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Thử lại phục hồi đang chờ'}).click();await expect(page.getByRole('status').filter({hasText:'phục hồi cùng lượt pending'})).toBeVisible();expect(requests[0]).toEqual(requests[1]);
 await page.getByRole('combobox',{name:'Điểm phục vụ',exact:true}).selectOption('point');await page.getByRole('button',{name:'Tải lại hàng đợi'}).click();await page.getByLabel('Lý do chuyển lượt chờ sang hôm nay').fill('Synthetic patient returned');await page.getByRole('button',{name:'Chuyển SYN-OLD sang hôm nay'}).click();await expect(page.getByRole('button',{name:'Thử lại chuyển hàng đợi đang chờ'})).toBeVisible();await expect(page.getByLabel('Địa điểm tiếp nhận')).toBeDisabled();await expect(page.getByRole('button',{name:'Cài đặt tài khoản',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Đăng xuất',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Thử lại chuyển hàng đợi đang chờ'}).click();await expect(page.getByRole('status').filter({hasText:'cùng lượt sang hàng đợi hôm nay: SYN-TODAY'})).toBeVisible();expect(requests[2]).toEqual(requests[3]);await expect(page.getByRole('button',{name:'Chuyển SYN-OLD sang hôm nay'})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(375);await page.locator('[aria-label="Lượt chờ từ ngày trước"]').screenshot({path:path.join(evidence,'overnight-queue-mobile.png')});await page.locator('[aria-label="Quản lý phục hồi tiếp nhận"]').screenshot({path:path.join(evidence,'supervisor-arrival-mobile.png')});
});

