import { test,expect } from '@playwright/test';
import path from 'node:path';
import {writeFileSync} from 'node:fs';
const evidence=path.resolve('../../../docs/audits/clinic-v2/P05-S2/verification');
test('reception uses an explicit patient selection and supports mobile queue actions',async({page})=>{
 const requests:{url:string,body:unknown,key?:string}[]=[];
 const patient={patientId:'patient',clinicPatientLinkId:'link',patientCode:'PT-SYN',fullName:'Synthetic Patient',dateOfBirth:null,phoneLast4:'4567',status:'PROVISIONAL',version:0};
 const ticket={id:'ticket',visitId:'visit',servicePointId:'point',date:'2026-10-01',number:1,code:'R1-20261001-0001',state:'WAITING',version:0};let arrived=false;
 await page.route('**/s1/**',async route=>{
  const req=route.request(),url=req.url(),body=req.postDataJSON();requests.push({url,body,key:req.headers()['idempotency-key']});let json:unknown={};
  if(url.endsWith('/auth/login'))json={data:{accessToken:'synthetic-token'}};
  else if(url.endsWith('/me/current'))json={userId:'fixture-user',legacyRoles:['ROLE_USER'],platformOperator:false};
  else if(url.endsWith('/me/contexts'))json=[{membershipId:'membership',clinicId:'clinic',role:'ADMIN',allBranches:false,branchIds:['branch'],version:1}];
  else if(url.endsWith('/reception-directory'))json={id:'clinic',name:'Synthetic Clinic',branches:[{id:'branch',name:'Synthetic Branch',active:true}]};
  else if(url.endsWith('/doctor-affiliations'))json=[{practitionerId:'doctor',displayName:'Synthetic Doctor',active:true,effectiveFrom:'2020-01-01',effectiveUntil:null}];
  else if(url.includes('/reception/arrivals?'))json=arrived?[{operation:'walk-in',createdAt:'2026-10-01T03:00:00Z',visit:{id:'visit',appointmentId:null,status:'WAITING',version:0,ticket}}]:[];
  else if(url.endsWith('/reception/arrivals/visit/recover')){expect(body).toEqual({expectedVersion:0,reason:'Synthetic reload review'});json={id:'visit',appointmentId:null,status:'WAITING',version:0,ticket};}
  else if(url.endsWith('/service-points'))json=[{id:'point',code:'R1',name:'Synthetic Room',active:true}];
  else if(url.includes('/match-suggestions?'))json=[patient];
  else if(url.endsWith('/visits/walk-in')){arrived=true;json={id:'visit',appointmentId:null,status:'WAITING',version:0,ticket};}
  else if(url.includes('/queue/page?'))json={items:arrived?[ticket]:[],nextAfterNumber:null};
  else if(url.endsWith('/queue/ticket/call')){expect(body.expectedVersion).toBe(0);ticket.state='CALLED';ticket.version=1;json=ticket;}
  else if(url.endsWith('/doctors/doctor/absences')){expect(body.startsAt).toBe('2026-10-01T03:00:00.000Z');expect(body.endsAt).toBe('2026-10-01T04:00:00.000Z');json={id:'absence',doctorId:'doctor',startsAt:body.startsAt,endsAt:body.endsAt};}
  else if(url.endsWith('/doctor-absences/absence/apply'))json={recorded:2,retryRequired:['retry-required'],hasMore:false};
  await route.fulfill({json});
 });
 await page.goto('/workspace?view=reception');await page.getByLabel('Email',{exact:true}).fill('synthetic@example.invalid');await page.getByLabel('Mật khẩu',{exact:true}).fill('synthetic-password');await page.getByRole('button',{name:'Đăng nhập'}).click();await page.getByLabel('Địa điểm tiếp nhận').selectOption('branch');
 await page.getByRole('link',{name:'Hàng đợi',exact:true}).click();await expect(page.getByRole('heading',{name:'Hàng đợi tại điểm phục vụ',exact:true})).toBeFocused();await page.getByRole('link',{name:'Xác minh bệnh nhân',exact:true}).click();await expect(page.getByRole('heading',{name:'Xác minh bệnh nhân tại quầy',exact:true})).toBeFocused();await page.getByLabel('Số điện thoại tìm hồ sơ').fill('0001234567');await page.getByRole('button',{name:'Tìm gợi ý hồ sơ'}).click();await expect(page.getByRole('button',{name:'Tiếp nhận walk-in'})).toBeDisabled();await page.getByRole('button',{name:'Đã đối chiếu — chọn hồ sơ'}).click();await page.getByLabel('Lý do tiếp nhận hoặc điều phối').fill('Synthetic intake');await page.getByRole('combobox',{name:'Điểm phục vụ',exact:true}).selectOption('point');await page.getByRole('combobox',{name:'Bác sĩ tiếp nhận',exact:true}).selectOption('doctor');await page.getByRole('button',{name:'Tiếp nhận walk-in'}).click();await expect(page.getByRole('status').filter({hasText:'Đã tiếp nhận walk-in'})).toBeVisible();
 const walk=requests.find(x=>x.url.endsWith('/visits/walk-in'));expect(walk?.key).toBeTruthy();expect(walk?.body).not.toHaveProperty('appointmentId');
 await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>{(document.activeElement as HTMLElement)?.blur();window.scrollTo(0,0);});await page.screenshot({path:path.join(evidence,'reception-desktop.png'),fullPage:true});await page.setViewportSize({width:375,height:812});await page.evaluate(()=>{(document.activeElement as HTMLElement)?.blur();window.scrollTo(0,0);});await page.screenshot({path:path.join(evidence,'reception-mobile.png'),fullPage:true});const layout=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,wide:Array.from(document.querySelectorAll('*')).map(e=>({tag:e.tagName,cls:e.className,right:e.getBoundingClientRect().right})).filter(e=>e.right>innerWidth+1).slice(0,20)}));writeFileSync(path.join(evidence,'reception-layout.json'),JSON.stringify(layout,null,2));expect(layout.scrollWidth).toBeLessThanOrEqual(layout.width);await page.reload();await page.getByLabel('Email',{exact:true}).fill('synthetic@example.invalid');await page.getByLabel('Mật khẩu',{exact:true}).fill('synthetic-password');await page.getByRole('button',{name:'Đăng nhập'}).click();await page.getByLabel('Địa điểm tiếp nhận').selectOption('branch');await page.getByLabel('Lý do tiếp nhận hoặc điều phối').fill('Synthetic reload review');await page.getByRole('button',{name:'Xác nhận kết quả lượt này',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Đã xác nhận lượt tiếp nhận từ server'})).toBeVisible();expect(requests.filter(x=>x.url.endsWith('/visits/walk-in'))).toHaveLength(1);await page.getByRole('button',{name:'Gọi R1-20261001-0001',exact:true}).click();await expect(page.getByText('CALLED',{exact:true})).toBeVisible();
 await page.getByText('Báo bác sĩ vắng theo khoảng lịch',{exact:true}).click();await page.getByLabel('Bác sĩ báo vắng').selectOption('doctor');await page.getByLabel('Lý do tiếp nhận hoặc điều phối').fill('Synthetic absence');await page.getByLabel('Bắt đầu vắng (giờ Việt Nam)').fill('2026-10-01T10:00');await page.getByLabel('Kết thúc vắng (giờ Việt Nam)').fill('2026-10-01T11:00');await page.getByRole('button',{name:'Ghi khoảng vắng có lý do',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Đã ghi khoảng vắng'})).toBeVisible();await page.getByRole('button',{name:'Ghi ngoại lệ các lịch bị ảnh hưởng',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'1 lịch cần kiểm tra và thử lại'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(375);await page.evaluate(()=>{(document.activeElement as HTMLElement)?.blur();window.scrollTo(0,0);});await page.locator('details').filter({has:page.getByText('Báo bác sĩ vắng theo khoảng lịch',{exact:true})}).screenshot({path:path.join(evidence,'reception-absence-mobile.png')});
});



