function Invoke-ReceptionOperationsFlow {
 param($evidence,$ports,$clinic,$branch,$otherBranch,$patientId,$doctorId,$doctorUser,$receptionId,$pointId,$originalBooking,$tokens,$today)
 $base="http://127.0.0.1:$($ports.encounter)/api/v2/clinics/$clinic/branches/$branch";$owner=@{Authorization="Bearer $($tokens.owner)";'Idempotency-Key'=[guid]::NewGuid().ToString()};$staff=@{Authorization="Bearer $($tokens.reception)";'Idempotency-Key'=[guid]::NewGuid().ToString()}
 $pending=[guid]::NewGuid().ToString();$booking=[guid]::NewGuid().ToString();$hold=[guid]::NewGuid().ToString();$slot=[guid]::NewGuid().ToString()
 # Explicit isolated fault fixture: source claim committed, staff local arrival ACK lost.
 # Existing actual Patient/Catalog/Doctor identifiers are preserved; no production data.
 Query 'appointment' @"
INSERT INTO appointment_v2.capacity_slots(id,clinic_id,branch_id,offering_id,doctor_id,starts_at,ends_at,capacity,schedule_version,offering_version) SELECT '$slot',clinic_id,branch_id,offering_id,doctor_id,now()-interval '5 minutes',now()+interval '25 minutes',1,1,1 FROM appointment_v2.appointments WHERE id='$originalBooking';
INSERT INTO appointment_v2.slot_reservations(id,slot_id,clinic_id,branch_id,patient_id,price_version_id,amount_vnd,currency,price_effective_from,state,expires_at,idempotency_key,payload_hash) SELECT '$hold','$slot',clinic_id,branch_id,patient_id,price_version_id,amount_vnd,currency,price_effective_from,'CONSUMED',now()+interval '10 minutes','synthetic-manager-hold','synthetic-hash' FROM appointment_v2.appointments WHERE id='$originalBooking';
INSERT INTO appointment_v2.appointments(id,appointment_code,clinic_id,branch_id,patient_id,clinic_patient_link_id,offering_id,doctor_id,slot_id,reservation_id,price_version_id,amount_vnd,currency,price_effective_from,status,confirmation_key,encounter_id) SELECT '$booking','AP-SYN-MANAGER',clinic_id,branch_id,patient_id,clinic_patient_link_id,offering_id,doctor_id,'$slot','$hold',price_version_id,amount_vnd,currency,price_effective_from,'CHECKED_IN','synthetic-manager-confirm','$pending' FROM appointment_v2.appointments WHERE id='$originalBooking';
"@
 Query 'encounter' @"
INSERT INTO encounter_v2.visits(id,clinic_id,branch_id,patient_id,clinic_patient_link_id,appointment_id,doctor_id,doctor_user_id,service_point_id,status) SELECT '$pending',clinic_id,branch_id,patient_id,clinic_patient_link_id,'$booking',doctor_id,doctor_user_id,service_point_id,'ARRIVAL_PENDING' FROM encounter_v2.visits WHERE appointment_id='$originalBooking';
INSERT INTO encounter_v2.command_receipts(clinic_id,branch_id,actor_user_id,operation,key,payload_hash,visit_id,service_point_id,arrival_reason) VALUES('$clinic','$branch','$receptionId','check-in','synthetic-original-staff','synthetic-hash','$pending','$pointId','Synthetic staff claim acknowledgement lost');
"@
 $page=Invoke-RestMethod "$base/reception/pending-arrivals?limit=1" -Headers $owner;if(@($page.items|Where-Object id -eq $pending).Count -ne 1){throw 'Manager scoped pending page did not expose owned pending source'}
 $input=@{expectedVersion=0;reason='Synthetic supervisor takes over after staff shift'};$forbidden=Invoke-WebRequest "$base/reception/pending-arrivals/$pending/recover" -Method Post -Headers $staff -ContentType 'application/json' -Body ($input|ConvertTo-Json) -SkipHttpErrorCheck;if($forbidden.StatusCode -ne 403){throw 'Reception bypassed supervisor-only handoff'}
 $result=Post "$base/reception/pending-arrivals/$pending/recover" $owner $input;$again=Post "$base/reception/pending-arrivals/$pending/recover" $owner $input;if($result.id -ne $pending -or $result.status -ne 'WAITING' -or $result.ticket.id -ne $again.ticket.id){throw 'Supervisor recovery created another visit or ticket'}
 $changed=Invoke-WebRequest "$base/reception/pending-arrivals/$pending/recover" -Method Post -Headers $owner -ContentType 'application/json' -Body (@{expectedVersion=0;reason='Changed manager reason'}|ConvertTo-Json) -SkipHttpErrorCheck;if($changed.StatusCode -ne 409){throw 'Supervisor receipt accepted changed payload'}
 $new=Post "$base/visits/walk-in" $staff @{patientId=$patientId;doctorId=$doctorId;servicePointId=$pointId;reason='Synthetic returned waiting walk-in'}
 Query 'encounter' "UPDATE encounter_v2.queue_tickets SET queue_date=DATE '$today'-1 WHERE id='$($new.ticket.id)'; UPDATE encounter_v2.visits SET created_at=now()-interval '1 day' WHERE id='$($new.id)';"
 $staff['Idempotency-Key']=[guid]::NewGuid().ToString();$roll=@{expectedVersion=$new.ticket.version;reason='Synthetic patient is present today';destinationPointId=$pointId};$ticket=Post "$base/queue/$($new.ticket.id)/roll-forward" $staff $roll;$ticketReplay=Post "$base/queue/$($new.ticket.id)/roll-forward" $staff $roll
 if($ticket.visitId -ne $new.id -or $ticket.id -eq $new.ticket.id -or $ticket.id -ne $ticketReplay.id -or $ticket.date -ne $today){throw 'Overnight queue replaced visit or duplicated fresh ticket'}
 $pages=@();$after=0;do{$part=Invoke-RestMethod "$base/queue/page?servicePointId=$pointId&date=$today&afterNumber=$after&limit=2" -Headers $staff;$pages+=@($part.items);$after=$part.nextAfterNumber}while($null -ne $after)
 if(@($pages|Where-Object id -eq $ticket.id).Count -ne 1 -or @($pages|Where-Object id -eq $result.ticket.id).Count -ne 1 -or (@($pages.id|Select-Object -Unique).Count -ne $pages.Count)){throw 'Keyset queue pages skipped or duplicated a ticket'}
 $denied=Invoke-WebRequest "http://127.0.0.1:$($ports.encounter)/api/v2/clinics/$clinic/branches/$otherBranch/queue/page?servicePointId=$pointId&date=$today" -Headers $staff -SkipHttpErrorCheck;if($denied.StatusCode -ne 403){throw 'Queue paging bypassed branch grant'}
 Poll { $sql="SELECT count(*) FROM audit_v2.audit_events WHERE resource_type='encounter' AND resource_id='$pending' AND action='clinic.encounter.arrival_recovered.v1';";$count=$sql|& (Join-Path $PostgresBin 'psql.exe') -X -t -A -h 127.0.0.1 -p $databasePort -U postgres -d clinic_v2_s1_audit_sandbox;$LASTEXITCODE -eq 0 -and [int]$count -eq 1 } 'one real supervisor recovery Audit effect'
 $sql="SELECT (SELECT count(*) FROM encounter_v2.check_ins WHERE visit_id='$pending'),(SELECT count(*) FROM encounter_v2.queue_tickets WHERE visit_id='$pending'),(SELECT count(*) FROM encounter_v2.check_ins WHERE visit_id='$($new.id)'),(SELECT count(*) FROM encounter_v2.queue_tickets WHERE visit_id='$($new.id)'),(SELECT count(*) FROM encounter_v2.command_receipts WHERE actor_user_id='$receptionId' AND visit_id='$pending');";$counts=$sql|& (Join-Path $PostgresBin 'psql.exe') -X -t -A -h 127.0.0.1 -p $databasePort -U postgres -d clinic_v2_s1_encounter_sandbox;if($LASTEXITCODE -ne 0 -or ($counts -join '') -ne '1|1|1|2|1'){throw 'Reception recovery lost original receipt or duplicated business effect'}
 @{status='PASS';identity=$taskIdentityMode;fault='isolated-source-claim-committed-local-ACK-lost';supervisor='same-visit-original-staff-receipt-preserved';recoveryReplay='one-checkin-one-ticket-one-recovery-audit';wrongRole=403;changedPayload=409;overnight='same-visit-old-ticket-retained-new-day-ticket';queuePaging='keyset-no-duplicates';branchDenied=403;clinicalCompletion='UNCHANGED';onlinePayment='DISABLED'}|ConvertTo-Json|Set-Content (Join-Path $evidence 'reception-operations-summary.json')
}
