function Invoke-AbsenceLifecycleFlow {
 param($evidence,$ports,$clinic,$branch,$doctor,$absence,$booking,$patientId,$tokens,$today)
 $doctorBase="http://127.0.0.1:$($ports.doctor)/api/v2/clinics/$clinic/branches/$branch/doctors/$doctor/absences"
 $base="http://127.0.0.1:$($ports.encounter)/api/v2/clinics/$clinic/branches/$branch"
 $owner=@{Authorization="Bearer $($tokens.owner)";'Idempotency-Key'=[guid]::NewGuid().ToString()};$reception=@{Authorization="Bearer $($tokens.reception)"};$wrong=@{Authorization="Bearer $($tokens.doctor)";'Idempotency-Key'=[guid]::NewGuid().ToString()}
 function CurrentBooking { $rows=Invoke-RestMethod "$base/reception/appointments?date=$today" -Headers $reception;return @($rows|Where-Object id -eq $booking)[0] }
 Poll { $sql="SELECT count(*) FROM doctor.absence_deliveries WHERE absence_id='$($absence.id)' AND status='PUBLISHED';";$count=$sql|& (Join-Path $PostgresBin 'psql.exe') -X -t -A -h 127.0.0.1 -p $databasePort -U postgres -d clinic_v2_s1_doctor_sandbox;$LASTEXITCODE -eq 0 -and [int]$count -eq 1 } 'real Doctor absence relay acknowledgement'
 $exceptions=Invoke-RestMethod "$base/appointments/$booking/exceptions" -Headers $reception;$old=@($exceptions|Where-Object state -eq 'OPEN')[0];if(-not $old){throw 'Source absence exception not visible'}
 $current=CurrentBooking;$body=@{expectedVersion=$current.version;reason='Synthetic investigate active source'}
 $unsafe=Invoke-WebRequest "$base/appointments/$booking/exceptions/$($old.id)/resolve" -Method Post -Headers $owner -ContentType 'application/json' -Body ($body|ConvertTo-Json) -SkipHttpErrorCheck;if($unsafe.StatusCode -ne 409){throw 'Manager acknowledgement bypassed active absence source'}
 $denied=Invoke-WebRequest "$doctorBase/$($absence.id)/cancel" -Method Post -Headers $wrong -ContentType 'application/json' -Body (@{expectedVersion=1;reason='Synthetic wrong role'}|ConvertTo-Json) -SkipHttpErrorCheck;if($denied.StatusCode -ne 404){throw 'Wrong role changed Doctor absence source'}
 $owner['Idempotency-Key']=[guid]::NewGuid().ToString();$amend=@{expectedVersion=1;startsAt=[DateTimeOffset]::UtcNow.AddMinutes(1).ToString('o');endsAt=[DateTimeOffset]::UtcNow.AddHours(3).ToString('o');reason='Synthetic corrected source window'}
 $changed=Post "$doctorBase/$($absence.id)/amend" $owner $amend;$again=Post "$doctorBase/$($absence.id)/amend" $owner $amend
 if($changed.previous.state -ne 'CANCELLED' -or $changed.previous.startsAt -ne $absence.startsAt -or $changed.replacement.id -ne $again.replacement.id){throw 'Absence amendment replaced its immutable history or replay duplicated source'}
 $replacement=$changed.replacement
 Poll { $rows=Invoke-RestMethod "$base/appointments/$booking/exceptions" -Headers $reception;@($rows|Where-Object state -eq 'OPEN').Count -eq 1 -and @($rows|Where-Object state -eq 'RESOLVED').Count -eq 1 } 'real amendment cancels old exception and records replacement'
 $owner['Idempotency-Key']=[guid]::NewGuid().ToString();$cancel=@{expectedVersion=1;reason='Synthetic doctor available again'}
 $cancelled=Post "$doctorBase/$($replacement.id)/cancel" $owner $cancel;$replay=Post "$doctorBase/$($replacement.id)/cancel" $owner $cancel
 if($cancelled.previous.id -ne $replay.previous.id -or $cancelled.previous.state -ne 'CANCELLED'){throw 'Absence cancellation replay failed'}
 $changedBody=@{expectedVersion=1;reason='Changed reason'};$conflict=Invoke-WebRequest "$doctorBase/$($replacement.id)/cancel" -Method Post -Headers $owner -ContentType 'application/json' -Body ($changedBody|ConvertTo-Json) -SkipHttpErrorCheck;if($conflict.StatusCode -ne 409){throw 'Absence key accepted a changed payload'}
 Poll { $rows=Invoke-RestMethod "$base/appointments/$booking/exceptions" -Headers $reception;@($rows).Count -eq 2 -and @($rows|Where-Object state -eq 'OPEN').Count -eq 0 } 'real cancellation automatically resolves its own source exception'
 $manualSource=Post $doctorBase (@{Authorization="Bearer $($tokens.owner)";'Idempotency-Key'=[guid]::NewGuid().ToString()}) @{startsAt=[DateTimeOffset]::UtcNow.ToString('o');endsAt=[DateTimeOffset]::UtcNow.AddHours(2).ToString('o');reason='Synthetic patient cancellation resolution source'}
 Poll { $rows=Invoke-RestMethod "$base/appointments/$booking/exceptions" -Headers $reception;@($rows|Where-Object state -eq 'OPEN').Count -eq 1 } 'background records new source without manual apply'
 $rows=Invoke-RestMethod "$base/appointments/$booking/exceptions" -Headers $reception;$manual=@($rows|Where-Object state -eq 'OPEN')[0]
 $patientBase="http://127.0.0.1:$($ports.appointment)/api/v2/appointments/$booking/cancel"
 $null=Post $patientBase $reception @{clinicId=$clinic;patientId=$patientId;reason='Synthetic patient opts to cancel';correlationId=[guid]::NewGuid().ToString()}
 $current=CurrentBooking;$body=@{expectedVersion=$current.version;reason='Synthetic source cancellation checked'}
 $bad=Invoke-WebRequest "$base/appointments/$booking/exceptions/$($manual.id)/resolve" -Method Post -Headers ($reception+@{'Idempotency-Key'=[guid]::NewGuid().ToString()}) -ContentType 'application/json' -Body ($body|ConvertTo-Json) -SkipHttpErrorCheck;if($bad.StatusCode -ne 403){throw 'Reception resolved manager-only exception'}
 $owner['Idempotency-Key']=[guid]::NewGuid().ToString();$resolved=Post "$base/appointments/$booking/exceptions/$($manual.id)/resolve" $owner $body;$resolvedAgain=Post "$base/appointments/$booking/exceptions/$($manual.id)/resolve" $owner $body
 if($resolved.id -ne $resolvedAgain.id -or $resolved.state -ne 'RESOLVED'){throw 'Manual resolution replay failed'}
 $null=Post "$doctorBase/$($manualSource.id)/cancel" (@{Authorization="Bearer $($tokens.owner)";'Idempotency-Key'=[guid]::NewGuid().ToString()}) @{expectedVersion=1;reason='Synthetic source cleanup by cancellation'}
 Poll { $sql="SELECT count(*) FROM audit_v2.audit_events WHERE resource_type='appointment' AND resource_id='$booking' AND action='clinic.appointment.exception_resolved.v1';";$count=$sql|& (Join-Path $PostgresBin 'psql.exe') -X -t -A -h 127.0.0.1 -p $databasePort -U postgres -d clinic_v2_s1_audit_sandbox;$LASTEXITCODE -eq 0 -and [int]$count -eq 3 } 'three exact real resolution Audit effects'
 $sql="SELECT status,amount_vnd,(SELECT count(*) FROM appointment_v2.exception_resolution_commands WHERE exception_id IN(SELECT id FROM appointment_v2.reception_exceptions WHERE appointment_id='$booking')) FROM appointment_v2.appointments WHERE id='$booking';";$result=$sql|& (Join-Path $PostgresBin 'psql.exe') -X -t -A -h 127.0.0.1 -p $databasePort -U postgres -d clinic_v2_s1_appointment_sandbox;if($LASTEXITCODE -ne 0 -or ($result -join '') -ne 'CANCELLED|100000|3'){throw 'Resolution changed booking state/price or duplicated commands'}
 @{status='PASS';identity=$taskIdentityMode;propagation='actual-Doctor-lease-relay-Appointment-consumer';amendment='old-interval-cancelled-new-source-appended';replay='same-source-and-key';wrongDoctorRole=$denied.StatusCode;wrongReceptionRole=$bad.StatusCode;activeSourceBypass=409;changedPayload=409;resolutionEffects=3;frozenPriceVnd=100000;finalBooking='patient-cancelled-not-resurrected';clinicalRelease='DISABLED';onlinePayment='DISABLED'}|ConvertTo-Json|Set-Content (Join-Path $evidence 'absence-lifecycle-summary.json')
}
